-- T13193 R-2 (S5 rebase, journal spec §3.5 Rules 2, 4, 6) — what a scoped
-- rebase writes back after it replays a local transaction.
--
-- _sync_row_undo.values_json: the row's values (canonical JSON of wire
-- values, references as uids) just before a REPLAYED local op wrote them:
-- the columns a U changed, or the whole row for an I's re-insert. A rewind
-- prefers it over the sealed op's own before-image, because a replay can sit
-- on top of stream writes from earlier pages (D2) that a second rewind must
-- not undo. NULL until the op is replayed once.
--
-- _sync_sequenced.outcome: how the stream decided an own transaction's echo:
-- 'applied', or 'void' when its replay was refused (it stays rewound, §3.5
-- Rule 6, and keeps its undo until its conflict resolves).
--
-- Do not edit this file once applied: its hash is recorded per store.
ALTER TABLE _sync_row_undo ADD COLUMN values_json TEXT;
ALTER TABLE _sync_sequenced ADD COLUMN outcome TEXT NOT NULL DEFAULT 'applied';
