-- SCHEMA REFACTOR MARKER — T1174 (T-MSR-W2A-09) Hybrid Path A+ proof-of-concept.
--
-- idx_tasks_sentient_proposals_today was already created by T1126 migration
-- (20260421000002_t1126-sentient-proposal-index/migration.sql) with:
--
--   CREATE INDEX IF NOT EXISTS `idx_tasks_sentient_proposals_today`
--   ON `tasks` (date(`created_at`))
--   WHERE `labels_json` LIKE '%sentient-tier2%';
--
-- T1174 adopts the index into tasks-schema.ts as a schema-level .where() expression:
--
--   index('idx_tasks_sentient_proposals_today')
--     .on(sql`date(${table.createdAt})`)
--     .where(sql`${table.labelsJson} LIKE '%sentient-tier2%'`)
--
-- No DDL is emitted here because the index already exists on all databases that
-- have applied the T1126 migration. The snapshot.json in this folder is the
-- authoritative drizzle-kit anchor for future incremental migrations — it reflects
-- the schema-level expression of the partial index.
--
-- On fresh installs: migrations run in order; T1126 creates the index, this marker
-- runs as a no-op comment, and drizzle skips any DDL (empty statement list).
-- On existing installs: reconcileJournal probeAndMarkApplied detects the index
-- already exists and marks this migration applied without re-running DDL.
--
-- ADR-054 Hybrid Path A+ — schema-as-source-of-truth for partial indexes.
-- Migration T1126 folder remains in place for journal continuity.
