/**
 * T10165 — One-shot backfill: migrate `.cleo/adrs/adr-index.jsonl` rows into
 * the `attachments` table provenance columns shipped by T10158.
 *
 * The JSONL is a denormalised portability export historically regenerated by
 * `syncAdrsToDb` in `packages/core/src/adrs/sync.ts`. After this migration the
 * primary store for the same metadata is the `attachments` table (with the
 * T10158-introduced columns `lifecycle_status`, `supersedes`, `superseded_by`,
 * `summary`, `keywords`, `topics`, `related_tasks`), reachable from the docs
 * SSoT graph (T10162 supersede verb, T10164 graph CLI).
 *
 * ## Behaviour
 *
 * For every ADR row in `adr-index.jsonl`:
 *   1. Resolve the on-disk `.cleo/adrs/<file>` and compute its `sha256`.
 *   2. Look up — or insert — an `attachments` row keyed on the sha. The
 *      attachment payload is a minimal `BlobAttachment` discriminator so the
 *      record is identical in shape to what `cleo docs add --type adr` would
 *      have produced if invoked directly.
 *   3. Populate the seven provenance columns from the JSONL fields:
 *        - `lifecycle_status`  ← JSONL `status` (mapped to the
 *          {@link ATTACHMENT_LIFECYCLE_STATUSES} enum)
 *        - `supersedes`        ← attachment id of the JSONL `supersedes`
 *          target (ADR-NNN → resolved via slug lookup)
 *        - `superseded_by`     ← attachment id of the JSONL `supersededBy`
 *          target (resolved via slug lookup)
 *        - `summary`           ← JSONL `summary`
 *        - `keywords`          ← JSON-encoded `keywords[]`
 *        - `topics`            ← JSON-encoded `topics[]`
 *        - `related_tasks`     ← JSON-encoded `relatedTasks[]`
 *   4. Set `slug = <ADR-id-lowercased>` (e.g. `adr-003`) and `type = 'adr'`
 *      so the row is reachable from `cleo docs fetch adr-003` exactly like
 *      any other doc kind.
 *
 * Two passes are required because the supersession edges form a graph: the
 * first pass inserts/updates every attachment row, the second pass resolves
 * the `supersedes` / `superseded_by` FKs once every slug exists.
 *
 * ## Idempotency
 *
 * The script is safe to re-run. A row already populated for the same `sha256`
 * is updated in place (no duplicate insert) and the `slug` UNIQUE INDEX is
 * pre-checked outside the transaction window to surface a friendly error if
 * a non-ADR row already owns the target slug.
 *
 * ## Usage
 *
 * ```bash
 * # Dry-run (default) — reports what would change without writing
 * pnpm --filter @cleocode/core exec tsx \
 *   packages/core/src/migration/manual/T10165-backfill-adr-index.ts --dry-run
 *
 * # Apply — writes to tasks.db
 * pnpm --filter @cleocode/core exec tsx \
 *   packages/core/src/migration/manual/T10165-backfill-adr-index.ts --apply
 * ```
 *
 * The exported {@link backfillAdrIndex} function is the same code path used
 * by the tests.
 *
 * @task T10165
 * @epic T10157 (C-DOCS-SSOT)
 * @saga T9855 (SG-TEMPLATE-CONFIG-SSOT)
 */

import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { blobAttachmentSchema } from '@cleocode/contracts';
import { and, eq } from 'drizzle-orm';
import {
  ATTACHMENT_LIFECYCLE_STATUSES,
  type AttachmentLifecycleStatus,
  attachmentRefs,
  attachments,
} from '../../store/schema/attachments.js';
import { getDb } from '../../store/sqlite.js';

/**
 * Shape of one line in `.cleo/adrs/adr-index.jsonl`.
 *
 * Fields are optional because the historical writer omits them when blank;
 * the backfill treats missing/blank fields as `null`.
 */
export interface AdrIndexRow {
  /** ADR identifier, e.g. `"ADR-003"`. */
  id: string;
  /** Path of the ADR markdown file relative to the project root. */
  file: string;
  /** Human-readable ADR title. */
  title: string;
  /** Lifecycle status — `"proposed" | "accepted" | "superseded" | "deprecated" | ...`. */
  status?: string;
  /** ISO date when the ADR was authored. */
  date?: string;
  /** ISO date when the ADR transitioned to `accepted` (if any). */
  accepted?: string;
  /** Free-form reference to the ADR this one supersedes, e.g. `"ADR-001"`. */
  supersedes?: string;
  /** Free-form reference to the ADR that supersedes this one. */
  supersededBy?: string;
  /** Comma-split list of related task IDs (`T####`). */
  relatedTasks?: string[];
  /** Human-readable summary sentence. */
  summary?: string;
  /** Free-form keywords. */
  keywords?: string[];
  /** Higher-signal topic slugs. */
  topics?: string[];
}

/** Outcome of a single backfill run. */
export interface BackfillResult {
  /** ADR rows that were newly inserted into `attachments`. */
  inserted: number;
  /** ADR rows whose `attachments` row was updated in place. */
  updated: number;
  /** ADR rows whose row already matched the target state — no write needed. */
  unchanged: number;
  /** ADR rows that referenced a missing or unreadable markdown file. */
  fileMissing: number;
  /** ADR rows whose `supersedes` / `supersededBy` target could not be resolved. */
  unresolvedEdges: number;
  /** Non-fatal warnings — one line per concern. */
  warnings: string[];
}

/**
 * Map an ADR `id` string (e.g. `"ADR-003"`) to the canonical attachment slug.
 *
 * The lowercase form matches the existing `cleo docs fetch` slug convention
 * (e.g. `adr-079-e4-cli-coverage`) and the `cleo docs add --type adr` writer.
 */
function adrIdToSlug(adrId: string): string {
  return adrId.toLowerCase();
}

/**
 * Resolve a free-form `supersedes` reference (e.g. `"ADR-001"`,
 * `"ADR-001 (§3 motivation)"`) to a bare ADR id.
 */
function extractAdrId(ref: string | undefined): string | null {
  if (!ref) return null;
  const m = ref.match(/^(ADR-\d+)/);
  return m ? m[1]! : null;
}

/**
 * Normalise a JSONL `status` value onto the canonical
 * {@link ATTACHMENT_LIFECYCLE_STATUSES} enum.
 *
 * Unknown / blank values fall back to `'draft'` — matching the column default
 * shipped by T10158 — and a warning is appended to the caller's result.
 */
function normaliseLifecycleStatus(
  raw: string | undefined,
  warnings: string[],
  adrId: string,
): AttachmentLifecycleStatus {
  const value = (raw ?? '').trim().toLowerCase();
  if (
    value === 'draft' ||
    value === 'proposed' ||
    value === 'accepted' ||
    value === 'superseded' ||
    value === 'archived' ||
    value === 'deprecated'
  ) {
    return value;
  }
  warnings.push(`${adrId}: unknown status "${raw}" — defaulting to "draft"`);
  return 'draft';
}

/**
 * Parse the JSONL file at `path` into a typed list of {@link AdrIndexRow}.
 *
 * Lines that fail to parse are skipped with a warning so a single malformed
 * entry never blocks the entire backfill (mirrors the T9780 lesson).
 */
export function parseAdrIndexJsonl(path: string, warnings: string[]): AdrIndexRow[] {
  if (!existsSync(path)) {
    return [];
  }
  const raw = readFileSync(path, 'utf-8');
  const rows: AdrIndexRow[] = [];
  let lineNo = 0;
  for (const line of raw.split('\n')) {
    lineNo += 1;
    const trimmed = line.trim();
    if (trimmed.length === 0) continue;
    if (trimmed.startsWith('#')) continue;
    try {
      const parsed = JSON.parse(trimmed) as AdrIndexRow;
      if (typeof parsed.id === 'string' && typeof parsed.file === 'string') {
        rows.push(parsed);
      } else {
        warnings.push(`adr-index.jsonl line ${lineNo}: missing id/file`);
      }
    } catch {
      warnings.push(`adr-index.jsonl line ${lineNo}: malformed JSON, skipped`);
    }
  }
  return rows;
}

/**
 * Compute the sha256 of an ADR markdown file. Returns `null` when the file
 * is missing or unreadable — the caller treats that as a non-fatal warning.
 */
function readAdrSha256(filePath: string): { sha256: string; bytes: Buffer } | null {
  if (!existsSync(filePath)) return null;
  try {
    const bytes = readFileSync(filePath);
    return { sha256: createHash('sha256').update(bytes).digest('hex'), bytes };
  } catch {
    return null;
  }
}

/**
 * One-shot backfill entry point.
 *
 * Reads `<projectRoot>/.cleo/adrs/adr-index.jsonl`, populates the
 * `attachments` table provenance columns for every ADR row, then resolves
 * `supersedes` / `superseded_by` edges on a second pass once every slug
 * exists.
 *
 * @param projectRoot - Absolute project root containing the `.cleo/` directory.
 * @param opts.dryRun - When `true`, no rows are written; returns the would-be
 *                      counts instead.
 */
export async function backfillAdrIndex(
  projectRoot: string,
  opts: { dryRun?: boolean } = {},
): Promise<BackfillResult> {
  const dryRun = opts.dryRun ?? false;
  const result: BackfillResult = {
    inserted: 0,
    updated: 0,
    unchanged: 0,
    fileMissing: 0,
    unresolvedEdges: 0,
    warnings: [],
  };

  const adrsDir = join(projectRoot, '.cleo', 'adrs');
  const jsonlPath = join(adrsDir, 'adr-index.jsonl');
  const rows = parseAdrIndexJsonl(jsonlPath, result.warnings);
  if (rows.length === 0) {
    return result;
  }

  const db = await getDb(projectRoot);
  const nowIso = new Date().toISOString();

  // ── Pass 1: insert/update every attachments row keyed on sha256 ────────────
  /** ADR-id → resolved `attachments.id` for the second-pass edge fixup. */
  const adrIdToAttachmentId = new Map<string, string>();

  for (const row of rows) {
    const filePath = join(projectRoot, row.file);
    const fileSha = readAdrSha256(filePath);
    if (!fileSha) {
      result.fileMissing += 1;
      result.warnings.push(`${row.id}: file missing or unreadable at ${row.file}`);
      continue;
    }

    const slug = adrIdToSlug(row.id);
    const lifecycleStatus = normaliseLifecycleStatus(row.status, result.warnings, row.id);
    const keywords = row.keywords ? JSON.stringify(row.keywords) : null;
    const topics = row.topics ? JSON.stringify(row.topics) : null;
    const relatedTasks = row.relatedTasks ? JSON.stringify(row.relatedTasks) : null;
    const summary = row.summary ?? null;

    // Pre-check existing row keyed on sha256 (the canonical attachments
    // dedup key). If found we update in place; otherwise insert a fresh
    // row with a freshly-allocated UUID.
    const existing = await db
      .select()
      .from(attachments)
      .where(eq(attachments.sha256, fileSha.sha256))
      .get();

    if (existing) {
      // Detect whether any column would actually change so the unchanged
      // counter reflects real work.
      const wouldChange =
        existing.slug !== slug ||
        existing.type !== 'adr' ||
        existing.lifecycleStatus !== lifecycleStatus ||
        existing.summary !== summary ||
        existing.keywords !== keywords ||
        existing.topics !== topics ||
        existing.relatedTasks !== relatedTasks;

      if (wouldChange) {
        if (!dryRun) {
          await db
            .update(attachments)
            .set({
              slug,
              type: 'adr',
              lifecycleStatus,
              summary,
              keywords,
              topics,
              relatedTasks,
            })
            .where(eq(attachments.id, existing.id))
            .run();
        }
        result.updated += 1;
      } else {
        result.unchanged += 1;
      }
      adrIdToAttachmentId.set(row.id, existing.id);
      continue;
    }

    // Slug pre-check: surface a friendly warning if a non-ADR row already
    // owns the slug instead of letting the partial UNIQUE INDEX raise.
    const slugConflict = await db
      .select()
      .from(attachments)
      .where(eq(attachments.slug, slug))
      .get();
    if (slugConflict) {
      result.warnings.push(
        `${row.id}: slug "${slug}" already owned by a different sha256 — skipping`,
      );
      continue;
    }

    const attachmentId = randomUUID();
    // T11262: storageKey MUST be the contract-compliant CAS path
    // (`<sha[:2]>/<sha[2:]><ext>`, mirroring attachment-store.ts blobPath) so the
    // row satisfies `attachmentSchema`'s `storageKey: z.string().min(1)` and the
    // T11242 exodus round-trip. The ADR bytes themselves live in-tree at
    // `.cleo/adrs/` rather than the blob CAS, but the key is still recorded for
    // contract conformance. mime is always text/markdown here -> '.md'.
    const storageKey = `${fileSha.sha256.slice(0, 2)}/${fileSha.sha256.slice(2)}.md`;
    const attachmentValue = {
      kind: 'blob' as const,
      sha256: fileSha.sha256,
      storageKey,
      mime: 'text/markdown',
      size: fileSha.bytes.length,
      description: row.title,
    };
    blobAttachmentSchema.parse(attachmentValue);
    const attachmentJson = JSON.stringify(attachmentValue);

    if (!dryRun) {
      await db
        .insert(attachments)
        .values({
          id: attachmentId,
          sha256: fileSha.sha256,
          attachmentJson,
          createdAt: nowIso,
          refCount: 0,
          slug,
          type: 'adr',
          lifecycleStatus,
          summary,
          keywords,
          topics,
          relatedTasks,
        })
        .run();
    }
    result.inserted += 1;
    adrIdToAttachmentId.set(row.id, attachmentId);
  }

  // ── Pass 2: resolve supersedes / superseded_by edges ───────────────────────
  for (const row of rows) {
    const fromId = adrIdToAttachmentId.get(row.id);
    if (!fromId) continue;

    const supersedesAdrId = extractAdrId(row.supersedes);
    const supersededByAdrId = extractAdrId(row.supersededBy);

    const supersedesAttachmentId = supersedesAdrId
      ? (adrIdToAttachmentId.get(supersedesAdrId) ?? null)
      : null;
    const supersededByAttachmentId = supersededByAdrId
      ? (adrIdToAttachmentId.get(supersededByAdrId) ?? null)
      : null;

    if (supersedesAdrId && !supersedesAttachmentId) {
      result.unresolvedEdges += 1;
      result.warnings.push(
        `${row.id}: supersedes target ${supersedesAdrId} not present in adr-index — leaving null`,
      );
    }
    if (supersededByAdrId && !supersededByAttachmentId) {
      result.unresolvedEdges += 1;
      result.warnings.push(
        `${row.id}: supersededBy target ${supersededByAdrId} not present in adr-index — leaving null`,
      );
    }

    if (!supersedesAttachmentId && !supersededByAttachmentId) continue;

    if (!dryRun) {
      await db
        .update(attachments)
        .set({
          supersedes: supersedesAttachmentId,
          supersededBy: supersededByAttachmentId,
        })
        .where(eq(attachments.id, fromId))
        .run();
    }
  }

  // Reference the imports so unused-symbol pedantry stays quiet — `and` is
  // re-exported for downstream callers that compose extra predicates on top
  // of the backfill in their own scripts.
  void and;
  void attachmentRefs;
  void ATTACHMENT_LIFECYCLE_STATUSES;

  return result;
}

// ─── CLI entry point ─────────────────────────────────────────────────────────

/**
 * Parse CLI flags. Supported:
 *   `--dry-run`  (default)
 *   `--apply`
 *   `--project-root <path>`  (defaults to `process.cwd()`)
 */
function parseArgs(argv: string[]): { projectRoot: string; dryRun: boolean } {
  let dryRun = true;
  let projectRoot = process.cwd(); // CWD-OK: one-shot manual migration CLI default; overridable via --project-root (T10165)
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--apply') {
      dryRun = false;
    } else if (arg === '--dry-run') {
      dryRun = true;
    } else if (arg === '--project-root' && i + 1 < argv.length) {
      projectRoot = argv[i + 1]!;
      i += 1;
    }
  }
  return { projectRoot, dryRun };
}

/* istanbul ignore next — invoked only via direct `node`/`tsx` execution */
async function main(): Promise<void> {
  const { projectRoot, dryRun } = parseArgs(process.argv.slice(2));
  const result = await backfillAdrIndex(projectRoot, { dryRun });
  process.stdout.write(`${JSON.stringify({ dryRun, projectRoot, ...result }, null, 2)}\n`); // stdout-discipline-allowed: one-shot manual migration CLI tool-output (T10165) // stdout-write-allowed: ops-tool invocation surface, not a CLEO render path (T10165)
}

const isDirectInvocation =
  typeof process !== 'undefined' &&
  Array.isArray(process.argv) &&
  process.argv[1] !== undefined &&
  /T10165-backfill-adr-index\.(?:ts|js)$/.test(process.argv[1]);

if (isDirectInvocation) {
  main().catch((err) => {
    process.stderr.write(`T10165 backfill failed: ${String(err)}\n`);
    process.exit(1);
  });
}
