/**
 * Validation system barrel exports.
 *
 * Provides the complete validation system ported from lib/validation/*,
 * plus canonical Zod enum schemas for all domain enums so consumers can
 * import them from `@cleocode/core` instead of duplicating.
 *
 * @task T4523
 * @epic T4454
 */

// Core validation engine — also re-export registry constants for convenience
export { TASK_STATUSES } from '@cleocode/contracts';
// Inferred types
export type {
  AuditLogInsert,
  AuditLogSelect,
  InsertArchitectureDecision,
  InsertAuditLog,
  InsertExternalTaskLink,
  InsertLifecycleEvidence,
  InsertLifecycleGateResult,
  InsertLifecyclePipeline,
  InsertLifecycleStage,
  InsertLifecycleTransition,
  InsertManifestEntry,
  InsertPipelineManifest,
  InsertReleaseManifest,
  InsertSchemaMeta,
  InsertSession,
  InsertTask,
  InsertTaskDependency,
  InsertTaskRelation,
  InsertTokenUsage,
  InsertWorkHistory,
  SelectArchitectureDecision,
  SelectAuditLog,
  SelectExternalTaskLink,
  SelectLifecycleEvidence,
  SelectLifecycleGateResult,
  SelectLifecyclePipeline,
  SelectLifecycleStage,
  SelectLifecycleTransition,
  SelectManifestEntry,
  SelectPipelineManifest,
  SelectReleaseManifest,
  SelectSchemaMeta,
  SelectSession,
  SelectTask,
  SelectTaskDependency,
  SelectTaskRelation,
  SelectTokenUsage,
  SelectWorkHistory,
} from '../store/validation-schemas.js';
// ---------------------------------------------------------------------------
// Canonical Zod enum schemas (from validation-schemas.ts)
// ---------------------------------------------------------------------------
// Task enums
// Session enums
// Lifecycle enums
// Governance enums
// Token usage enums
// Relation / link enums
// Brain enums
// Insert/select schemas for all tables
export {
  AuditLogInsertSchema,
  AuditLogSelectSchema,
  adrStatusSchema,
  brainConfidenceLevelSchema,
  brainDecisionTypeSchema,
  brainEdgeTypeSchema,
  brainImpactLevelSchema,
  brainLinkTypeSchema,
  brainMemoryTypeSchema,
  brainNodeTypeSchema,
  brainObservationSourceTypeSchema,
  brainObservationTypeSchema,
  brainOutcomeTypeSchema,
  brainPatternTypeSchema,
  brainStickyColorSchema,
  brainStickyPrioritySchema,
  brainStickyStatusSchema,
  externalLinkTypeSchema,
  gateStatusSchema,
  insertArchitectureDecisionSchema,
  insertAuditLogSchema,
  insertExternalTaskLinkSchema,
  insertLifecycleEvidenceSchema,
  insertLifecycleGateResultSchema,
  insertLifecyclePipelineSchema,
  insertLifecycleStageSchema,
  insertLifecycleTransitionSchema,
  insertManifestEntrySchema,
  insertPipelineManifestSchema,
  insertReleaseManifestSchema,
  insertSchemaMetaSchema,
  insertSessionSchema,
  insertTaskDependencySchema,
  insertTaskRelationSchema,
  insertTaskSchema,
  insertTokenUsageSchema,
  insertWorkHistorySchema,
  lifecycleEvidenceTypeSchema,
  lifecycleGateResultSchema,
  lifecyclePipelineStatusSchema,
  lifecycleStageNameSchema,
  lifecycleStageStatusSchema,
  lifecycleTransitionTypeSchema,
  manifestStatusSchema,
  selectArchitectureDecisionSchema,
  selectAuditLogSchema,
  selectExternalTaskLinkSchema,
  selectLifecycleEvidenceSchema,
  selectLifecycleGateResultSchema,
  selectLifecyclePipelineSchema,
  selectLifecycleStageSchema,
  selectLifecycleTransitionSchema,
  selectManifestEntrySchema,
  selectPipelineManifestSchema,
  selectReleaseManifestSchema,
  selectSchemaMetaSchema,
  selectSessionSchema,
  selectTaskDependencySchema,
  selectTaskRelationSchema,
  selectTaskSchema,
  selectTokenUsageSchema,
  selectWorkHistorySchema,
  sessionStatusSchema,
  syncDirectionSchema,
  taskPrioritySchema,
  taskRelationTypeSchema,
  taskSizeSchema,
  taskStatusSchema,
  taskTypeSchema,
  tokenUsageConfidenceSchema,
  tokenUsageMethodSchema,
  tokenUsageTransportSchema,
} from '../store/validation-schemas.js';
// Compliance checking
export {
  type ComplianceMetrics,
  calculateOrchestrationOverhead,
  calculateTokenEfficiency,
  checkManifestEntry,
  checkReturnFormat,
  type ManifestIntegrity,
  type OrchestrationOverhead,
  scoreSubagentCompliance,
  type TokenEfficiency,
  type TokenMetrics,
} from './compliance.js';
// Documentation drift detection
export {
  checkCommandsSync,
  checkWrapperSync,
  type DriftIssue,
  type DriftReport,
  detectDrift,
  getIndexCommands,
  getIndexScripts,
  getScriptCommands,
  shouldRunDriftDetection,
} from './docs-sync.js';
// Doctor health checks
export * from './doctor/index.js';
export {
  type ArchiveData,
  type ComprehensiveValidationResult,
  checkIdUniqueness,
  checkTimestampSanity,
  FIELD_LIMITS,
  isMetadataOnlyUpdate,
  isValidStatus,
  normalizeLabels,
  sanitizeFilePath,
  type Task,
  type TaskData,
  type TaskStatus,
  VALID_OPERATIONS,
  type ValidationError,
  type ValidationResult,
  validateAll,
  validateBlockedBy,
  validateCancelReason,
  validateCurrentPhaseConsistency,
  validateDescription,
  validateNoCircularDeps,
  validateNote,
  validatePhaseStatusRequirements,
  validatePhaseTimestamps,
  validateSessionNote,
  validateSingleActivePhase,
  validateStatusTransition,
  validateTask,
  validateTitle,
} from './engine.js';
// Gap analysis
export {
  analyzeCoverage,
  type CoverageEntry,
  extractTopics,
  findReviewDocs,
  formatGapReport,
  type GapEntry,
  type GapReport,
  parseManifest,
  searchCanonicalCoverage,
} from './gap-check.js';
// Manifest validation
export {
  type ComplianceEntry,
  findManifestEntry,
  logRealCompliance,
  type ManifestEntry,
  type ManifestValidationResult,
  type ManifestViolation,
  validateAndLog,
  validateManifestEntry,
} from './manifest.js';
// Protocol validation common
export {
  checkAgentType,
  checkDocumentationSections,
  checkKeyFindingsCount,
  checkLinkedTasksPresent,
  checkManifestFieldPresent,
  checkManifestFieldType,
  checkOutputFileExists,
  checkProvenanceTags,
  checkReturnMessageFormat,
  checkStatusValid,
  type ProtocolValidationResult,
  type ProtocolViolation,
  validateCommonManifestRequirements,
} from './protocol-common.js';
// Verification gates
export {
  type AgentName,
  allEpicChildrenVerified,
  allSiblingsVerified,
  type CircularValidationResult,
  checkAllGatesPassed,
  checkCircularValidation,
  computePassed,
  type FailureLogEntry,
  type GateName,
  getDownstreamGates,
  getGateIndex,
  getGateOrder,
  getGateSummary,
  getMissingGates,
  getVerificationStatus,
  incrementRound,
  initVerification,
  isValidAgentName,
  isValidGateName,
  isVerificationComplete,
  logFailure,
  resetDownstreamGates,
  setVerificationPassed,
  shouldRequireVerification,
  type TaskForVerification,
  updateGate,
  VERIFICATION_GATE_ORDER,
  VERIFICATION_VALID_AGENTS,
  type Verification,
  type VerificationGates,
  type VerificationStatus,
} from './verification.js';
