/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Combine [`read_worktree_include`] + filtering + copying in one call.
 *
 * Walks `src_dir` discovering candidate leaves, filters them through the
 * supplied gitignore-syntax patterns, and copies the matches into
 * `dest_dir` using [`copy_paths_parallel`] semantics. When `patterns` is
 * empty the full subtree is copied (mirroring `worktrunk-core`'s
 * "no filter when the file is absent" rule).
 *
 * # Errors
 *
 * Returns a [`napi::Error`] when matcher construction, walking, or copying
 * fails for any reason.
 */
export declare function applyInclude(patterns: Array<IncludePatternNapi>, srcDir: string, destDir: string, opts: CopyOpts): CopyResult

/** Options for [`copy_paths_parallel`] and [`apply_include`]. */
export interface CopyOpts {
  /** Overwrite existing entries at the destination. */
  force: boolean
  /**
   * When set, every destination must resolve inside this root (path
   * canonicalization is tolerant of non-existent parents — see
   * `worktrunk_core::path::canonicalize_with_parents`).
   */
  rootGuard?: string
  /**
   * Reserved for future use — symlinks are always followed by
   * [`worktrunk_core::copy::copy_leaf`] today.
   */
  includeSymlinks: boolean
}

/**
 * Copy a list of explicit leaf paths from `src_dir` to `dest_dir` in
 * parallel using `worktrunk-core`'s 4-thread reflink-aware pool.
 *
 * `paths` must be repo-root relative — each `src_dir/path` is copied to
 * `dest_dir/path`. Destination parent directories are created on demand.
 *
 * # Errors
 *
 * Returns a [`napi::Error`] if `worktrunk_core::copy::copy_leaf` errors on
 * any leaf. The error chain is preserved via [`napi_err`].
 */
export declare function copyPathsParallel(srcDir: string, destDir: string, paths: Array<string>, opts: CopyOpts): CopyResult

/** Aggregated result of a parallel copy operation. */
export interface CopyResult {
  /** Number of leaves successfully copied. */
  copiedCount: number
  /** Number of leaves skipped because they already existed at the destination. */
  skippedCount: number
  /** Paths that failed to copy (relative to the source) — typically empty. */
  failedPaths: Array<string>
  /**
   * Total bytes copied. Capped at `u32::MAX` to fit napi's `u32` JS-number
   * surface; callers that need >4 GiB should split the copy. This matches
   * the worktree-provisioning use case where 4 GiB+ is exceptional.
   */
  totalBytes: number
}

/** Options for [`destroy_worktree`]. */
export interface DestroyOpts {
  /** Absolute path to the git repository whose worktrees we manage. */
  repoRoot: string
  /** Absolute path to the worktree directory to remove. */
  worktreePath: string
  /** When `true`, pass `--force` to remove locked or dirty worktrees. */
  force: boolean
}

/** Result of [`destroy_worktree`]. */
export interface DestroyResult {
  /** `true` once `git worktree remove` exited zero. */
  removed: boolean
  /**
   * Always `false` — branch deletion is the caller's responsibility.
   *
   * Reserved for future expansion if we ever wire `-b/--branch` deletion
   * into the SDK; today `worktrunk-core` only removes the working copy.
   */
  branchDeleted: boolean
}

/**
 * Remove an existing worktree via `git worktree remove [--force]`.
 *
 * Wraps [`worktrunk_core::git_wt::destroy_worktree`].
 *
 * # Errors
 *
 * Returns a [`napi::Error`] when the underlying `git worktree remove` fails.
 */
export declare function destroyWorktree(opts: DestroyOpts): DestroyResult

/** JS-facing pattern from a `.worktreeinclude` file. */
export interface IncludePatternNapi {
  /** The raw pattern text (gitignore-style), `!`-prefix stripped. */
  pattern: string
  /** Whether this entry began with `!` (re-includes after a prior exclusion). */
  isNegation: boolean
}

/** Options for [`list_worktrees`]. */
export interface ListOpts {
  /** Absolute path to the git repository whose worktrees we list. */
  repoRoot: string
}

/**
 * List all worktrees in `opts.repo_root`.
 *
 * Wraps [`worktrunk_core::git_wt::list_worktrees`].
 *
 * # Errors
 *
 * Returns a [`napi::Error`] when the underlying `git worktree list` fails.
 */
export declare function listWorktrees(opts: ListOpts): Array<WorktreeInfoNapi>

/**
 * Options for [`provision_worktree`].
 *
 * Mirrors the arguments of [`worktrunk_core::git_wt::provision_worktree`]
 * plus an optional `lock_reason` — when present, the worktree is locked
 * immediately after creation via `git worktree lock --reason <reason>`.
 */
export interface ProvisionOpts {
  /** Absolute path to the git repository whose worktrees we manage. */
  repoRoot: string
  /** Absolute target path where the new worktree should live. */
  targetPath: string
  /** Branch name to create + check out (passed as `-b <branch>`). */
  branch: string
  /** Base ref (commit-ish) to root the new worktree at. */
  baseRef: string
  /** When set, the new worktree is locked with this reason string. */
  lockReason?: string
}

/**
 * Provision a new git worktree and (optionally) lock it.
 *
 * Wraps [`worktrunk_core::git_wt::provision_worktree`]. When
 * `opts.lock_reason` is `Some`, the worktree is locked with that reason
 * immediately after creation; lock failures bubble up as a napi error.
 *
 * # Errors
 *
 * Returns a [`napi::Error`] when the underlying `git worktree add` /
 * `git worktree lock` fails. The JS side sees the trimmed `git` stderr in
 * `Error.message`.
 */
export declare function provisionWorktree(opts: ProvisionOpts): WorktreeHandleNapi

/**
 * Read and parse `<repo_root>/.worktreeinclude`.
 *
 * Returns an empty `Vec` when the file does not exist (callers can use
 * this as the "no filter, copy everything" signal).
 *
 * # Errors
 *
 * Returns a [`napi::Error`] when the file exists but cannot be read.
 */
export declare function readWorktreeInclude(repoRoot: string): Array<IncludePatternNapi>

/**
 * JS-facing handle returned from [`provision_worktree`].
 *
 * Mirrors [`worktrunk_core::git_wt::WorktreeHandle`] with `path` rendered as
 * a UTF-8 string for JS consumption.
 */
export interface WorktreeHandleNapi {
  /** Absolute path to the newly created worktree directory. */
  path: string
  /** The branch the worktree checked out. */
  branch: string
  /** The HEAD commit SHA at the moment of creation. */
  head: string
}

/** JS-facing worktree record (one entry from `git worktree list --porcelain`). */
export interface WorktreeInfoNapi {
  /** Absolute path to the worktree directory. */
  path: string
  /** Branch name (`None` for detached HEAD). */
  branch?: string
  /** HEAD commit SHA. */
  head: string
  /** Whether the worktree is locked. */
  isLocked: boolean
  /** Whether the worktree is reported as prunable by git. */
  isPrunable: boolean
}
