-- T13278 (journal spec §1.5 "Retirement", §3.5 Rule 2 D5) — retiring a replica.
--
-- _sync_txn.retire_json: the `retire` body of a `kind = 'retire'` control
-- transaction this replica emitted, `{"replica","successor","lastReplicaSeq"}`
-- as canonical JSON; NULL for every other transaction. The segment builder
-- puts it on the wire as `LedgerTxn.retire`.
--
-- _sync_retired: every replica a `retire` transaction retired, per stream:
-- its successor, the last replicaSeq it may still land, the transaction that
-- carried the retirement and that transaction's stream seq (NULL until it is
-- sequenced: this replica's own retire before its echo). A transaction of a
-- retired replica sequenced after the retire is inherited history: applied as
-- an ordinary op, never recorded as a new conflict. The fold horizon and the
-- remint authority leave retired replicas out.
--
-- Local-only: rebuilt from the stream by every receiver.
--
-- Do not edit this file once applied: its hash is recorded per store.
ALTER TABLE _sync_txn ADD COLUMN retire_json TEXT;
CREATE TABLE IF NOT EXISTS _sync_retired (
  stream           TEXT NOT NULL,
  replica_id       TEXT NOT NULL,
  successor        TEXT NOT NULL,
  last_replica_seq INTEGER NOT NULL,
  txn              TEXT NOT NULL,
  hlc              TEXT NOT NULL,
  seq              INTEGER,
  PRIMARY KEY (stream, replica_id)
) WITHOUT ROWID;
