-- BASELINE MARKER — T1176 Hybrid Path A+ (ADR-054).
-- Schema state for telemetry captured in snapshot.json. No DDL to apply here.
-- On fresh installs, the CREATE statements from the canonical tree
-- (prior migrations in this folder) produce the target schema.
-- On existing installs, reconcileJournal Scenario 3 will see that the
-- schema already matches and insert the journal row without running DDL.
-- Snapshot.json MUST be preserved — it is the anchor for drizzle-kit
-- generate going forward.
