/**
 * Rolling Session Narrative — Per-session conversation summary store.
 *
 * Maintains a compact, rolling prose summary of what has happened in a CLEO
 * session.  Each dialectic turn can contribute a `sessionNarrativeDelta` that
 * is appended and compressed into the rolling `narrative` field.
 *
 * ## Storage
 *
 * Data is persisted to the `session_narrative` table in brain.db.  The table
 * is created on first write via `CREATE TABLE IF NOT EXISTS` so the module
 * works safely before the formal ADR-054 Drizzle migration is applied.
 * The Drizzle migration (`20260423000002_t1089-add-session-narrative-table`)
 * generated by `pnpm db:new -- --db brain --task T1089 --name add-session-narrative-table`
 * is the canonical source for the schema; the inline DDL here is a verbatim copy
 * kept for zero-dep startup resilience.
 *
 * ## Schema
 *
 * ```
 * session_narrative (
 *   session_id     TEXT PRIMARY KEY,
 *   narrative      TEXT NOT NULL,       -- Rolling summary, max 2000 chars
 *   turn_count     INTEGER NOT NULL DEFAULT 0,
 *   last_updated_at INTEGER NOT NULL,   -- Unix epoch milliseconds
 *   pivot_count    INTEGER NOT NULL DEFAULT 0
 * )
 * ```
 *
 * ## Pivot Detection
 *
 * `detectPivot(delta)` uses a simple heuristic: a topic shift is detected when
 * the new delta contains > 50% new keyword tokens relative to the existing
 * narrative.  A future iteration (T1082.followup) can replace this with an
 * embedding cosine similarity check once the vec extension is reliably present.
 *
 * ## PSYCHE Reference
 *
 * Inspired by `upstream psyche-lineage · deriver/deriver.py` (session state
 * derivation) — PSYCHE maintains a rolling representation of what a session
 * "is about" that informs future retrieval and sigil generation.
 *
 * @task T1089
 * @epic T1082
 */

import { getBrainNativeDb } from '../store/memory-sqlite.js';

// ============================================================================
// Constants
// ============================================================================

/** Maximum character length for the rolling narrative field. */
const MAX_NARRATIVE_CHARS = 2000;

/**
 * Keyword-overlap threshold above which a turn is classified as a pivot.
 * When fewer than this fraction of delta keywords appear in the narrative,
 * the topic is considered to have shifted significantly.
 *
 * T1531: replace with cosine similarity < 0.3 once embedding
 * vec extension is reliably loaded.
 */
const PIVOT_KEYWORD_OVERLAP_THRESHOLD = 0.5;

// ============================================================================
// Types
// ============================================================================

/**
 * A session narrative record as returned by `getSessionNarrative`.
 */
export interface SessionNarrativeRecord {
  /** Session identifier. */
  sessionId: string;
  /** Rolling prose summary of the session so far. */
  narrative: string;
  /** Number of dialectic turns that have contributed to this narrative. */
  turnCount: number;
  /** Unix epoch milliseconds of the last update. */
  lastUpdatedAt: number;
  /** Number of detected topic pivots in this session. */
  pivotCount: number;
}

// ============================================================================
// Private: DDL guard
// ============================================================================

/** Whether the `session_narrative` table has been verified / created. */
let _tableEnsured = false;

/**
 * Ensure the `session_narrative` table exists in brain.db.
 *
 * Uses `CREATE TABLE IF NOT EXISTS` so this is idempotent and safe to call
 * multiple times.  After the formal Drizzle migration lands the DDL is
 * redundant but harmless.
 */
function ensureTable(): import('node:sqlite').DatabaseSync {
  const db = getBrainNativeDb();
  if (!db) {
    throw new Error(
      'session-narrative: brain.db native handle not available. ' +
        'Call getBrainDb() at startup to initialise the database.',
    );
  }

  if (!_tableEnsured) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS session_narrative (
        session_id      TEXT PRIMARY KEY,
        narrative       TEXT NOT NULL DEFAULT '',
        turn_count      INTEGER NOT NULL DEFAULT 0,
        last_updated_at INTEGER NOT NULL DEFAULT 0,
        pivot_count     INTEGER NOT NULL DEFAULT 0
      );
    `);
    _tableEnsured = true;
  }

  return db;
}

// ============================================================================
// Public SDK
// ============================================================================

/**
 * Retrieve the current narrative record for a session.
 *
 * Returns `null` when the session has no narrative entry yet.
 *
 * @param sessionId - The session identifier to look up.
 * @returns The narrative record, or `null` if not found.
 *
 * @example
 * ```ts
 * const record = await getSessionNarrative('ses_20260422131135_5149eb');
 * console.log(record?.narrative ?? '(no narrative yet)');
 * ```
 *
 * @task T1089
 */
export async function getSessionNarrative(
  sessionId: string,
): Promise<SessionNarrativeRecord | null> {
  const db = ensureTable();

  const row = db
    .prepare(
      'SELECT session_id, narrative, turn_count, last_updated_at, pivot_count ' +
        'FROM session_narrative WHERE session_id = ?',
    )
    .get(sessionId) as
    | {
        session_id: string;
        narrative: string;
        turn_count: number;
        last_updated_at: number;
        pivot_count: number;
      }
    | undefined;

  if (!row) return null;

  return {
    sessionId: row.session_id,
    narrative: row.narrative,
    turnCount: row.turn_count,
    lastUpdatedAt: row.last_updated_at,
    pivotCount: row.pivot_count,
  };
}

/**
 * Append a narrative delta to a session's rolling summary.
 *
 * The delta is prepended with a space separator if the existing narrative is
 * non-empty.  When the combined result exceeds `MAX_NARRATIVE_CHARS` the oldest
 * content is trimmed from the left (keeping the most recent context).
 *
 * Side effect: increments `turn_count` by one and updates `pivot_count` when
 * `detectPivot(delta)` returns `true` against the existing narrative.
 *
 * @param sessionId   - The session to update.
 * @param delta       - New narrative content from the current turn.
 * @param _projectRoot - Project root (reserved for future embedding-based pivot; unused now).
 *
 * @example
 * ```ts
 * await appendNarrativeDelta(
 *   'ses_20260422131135_5149eb',
 *   'User requested zero-dep implementation; agent proposed using existing buildRetrievalBundle.',
 *   '/mnt/projects/cleocode',
 * );
 * ```
 *
 * @task T1089
 */
export async function appendNarrativeDelta(
  sessionId: string,
  delta: string,
  _projectRoot: string,
): Promise<void> {
  if (!delta.trim()) return;

  const db = ensureTable();
  const now = Date.now();

  // Get existing record
  const existing = await getSessionNarrative(sessionId);

  let newNarrative: string;
  let newPivotCount: number;

  if (!existing) {
    newNarrative = delta.slice(0, MAX_NARRATIVE_CHARS);
    newPivotCount = 0;
  } else {
    // Detect pivot before composing new narrative
    const isPivot = detectPivot(delta, existing.narrative);
    newPivotCount = existing.pivotCount + (isPivot ? 1 : 0);

    // Compose and trim to max length (keep newest content)
    const combined = existing.narrative ? `${existing.narrative} ${delta}` : delta;
    newNarrative =
      combined.length <= MAX_NARRATIVE_CHARS
        ? combined
        : combined.slice(combined.length - MAX_NARRATIVE_CHARS);
  }

  const newTurnCount = (existing?.turnCount ?? 0) + 1;

  db.prepare(`
    INSERT INTO session_narrative (session_id, narrative, turn_count, last_updated_at, pivot_count)
    VALUES (?, ?, ?, ?, ?)
    ON CONFLICT(session_id) DO UPDATE SET
      narrative       = excluded.narrative,
      turn_count      = excluded.turn_count,
      last_updated_at = excluded.last_updated_at,
      pivot_count     = excluded.pivot_count
  `).run(sessionId, newNarrative, newTurnCount, now, newPivotCount);
}

/**
 * Detect whether a new narrative delta represents a significant topic pivot.
 *
 * Uses a keyword-overlap heuristic: if fewer than `PIVOT_KEYWORD_OVERLAP_THRESHOLD`
 * of the delta's content words appear in the existing narrative, the topic is
 * considered to have shifted (pivot = true).
 *
 * Short deltas (< 5 tokens) never trigger a pivot to avoid false positives from
 * acknowledgement messages.
 *
 * T1531: replace with embedding cosine < 0.3 once vec extension
 * is reliably available.
 *
 * @param delta            - Incoming narrative text from the new turn.
 * @param existingNarrative - Current rolling narrative content.
 * @returns `true` when a topic pivot is detected.
 *
 * @example
 * ```ts
 * detectPivot("switching to Rust implementation", "TypeScript type system discussion"); // true
 * detectPivot("continuing the TypeScript work", "TypeScript type system discussion");   // false
 * ```
 *
 * @task T1089
 */
export function detectPivot(delta: string, existingNarrative: string): boolean {
  if (!existingNarrative.trim()) return false;

  // Tokenise: lowercase alpha-only tokens of length >= 4 (ignores stop words)
  const tokenise = (text: string): Set<string> => {
    const tokens = text
      .toLowerCase()
      .split(/\W+/)
      .filter((t) => t.length >= 4);
    return new Set(tokens);
  };

  const deltaTokens = tokenise(delta);
  if (deltaTokens.size < 5) return false; // Too short to judge

  const narrativeTokens = tokenise(existingNarrative);
  let overlap = 0;
  for (const token of deltaTokens) {
    if (narrativeTokens.has(token)) overlap++;
  }

  const overlapRatio = overlap / deltaTokens.size;
  return overlapRatio < PIVOT_KEYWORD_OVERLAP_THRESHOLD;
}
