/**
 * BUILD CONFIGURATION - AUTO-GENERATED FILE
 *
 * This file is generated by dev/generate-build-config.js
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next build
 *
 * Source of truth: package.json
 * Generated at: 2026-03-18T09:06:32.935Z
 *
 * @task T5245
 * @auto-generated
 */

export const BUILD_CONFIG = {
  name: '@cleocode/cleo',
  version: '2026.3.36',
  description: 'CLEO V2 - TypeScript task management CLI for AI coding agents',
  repository: {
    owner: 'kryptobaseddev',
    name: 'cleo',
    fullName: 'kryptobaseddev/cleo',
    url: 'https://github.com/kryptobaseddev/cleo.git',
    issuesUrl: 'https://github.com/kryptobaseddev/cleo/issues',
  },
  buildDate: '2026-03-18T09:06:32.935Z',
  templates: {
    issueTemplatesDir: 'templates/issue-templates',
  },
} as const;

// Type exports for TypeScript consumers
export type BuildConfig = typeof BUILD_CONFIG;
export type RepositoryConfig = BuildConfig['repository'];
