-- T13397 (T12341 §6.4 step 1, journal spec §2.6 "K ops") — uid aliases the
-- applier follows, in both stores.
--
-- A held uid collision (T13394) settles when the loser's origin re-keys its
-- row and publishes the K. A receiver that holds the loser (the winner owns
-- the uid here) cannot move a row it never placed, so it records the K as an
-- alias only, and every later read of the loser's ops follows it:
--
-- tbl, old_uid, old_bfp: the re-keyed row, named by (uid, birth fingerprint);
--   the winner of the collision keeps old_uid with another fingerprint and is
--   never matched.
-- new_uid: where the row lives now.
-- origin: the replica that wrote the K. Before its K, that replica's
--   references to old_uid meant the loser; references written after it, or by
--   anyone else, mean the winner.
-- hlc: the K's HLC (the boundary above).
--
-- Local-only: derived from the K ops this replica applied. The project
-- store's portable tasks_uid_aliases (T12341 §9.3) is written by the
-- re-key path; the global store has none, so the journal keeps its own.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_uid_alias (
  tbl        TEXT NOT NULL,
  old_uid    TEXT NOT NULL,
  old_bfp    TEXT NOT NULL,
  new_uid    TEXT NOT NULL,
  origin     TEXT NOT NULL,
  hlc        TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (tbl, old_uid, old_bfp)
) WITHOUT ROWID;
