/**
 * Drizzle ORM schema for CLEO brain.db (SQLite via node:sqlite + sqlite-proxy).
 *
 * Tables: brain_decisions, brain_patterns, brain_learnings, brain_memory_links, brain_schema_meta
 * Stores cognitive infrastructure: decisions, patterns, and learnings extracted
 * from CLEO task execution. Cross-references tasks in tasks.db via soft FKs.
 *
 * @epic T5149
 * @task T5127
 */
/** Decision types from ADR-009. */
export declare const BRAIN_DECISION_TYPES: readonly ["architecture", "technical", "process", "strategic", "tactical"];
/** Confidence levels for decisions. */
export declare const BRAIN_CONFIDENCE_LEVELS: readonly ["low", "medium", "high"];
/** Outcome types for decision tracking. */
export declare const BRAIN_OUTCOME_TYPES: readonly ["success", "failure", "mixed", "pending"];
/** Pattern types for workflow analysis. */
export declare const BRAIN_PATTERN_TYPES: readonly ["workflow", "blocker", "success", "failure", "optimization"];
/** Impact levels for patterns. */
export declare const BRAIN_IMPACT_LEVELS: readonly ["low", "medium", "high"];
/** Link types for cross-referencing BRAIN entries with tasks. */
export declare const BRAIN_LINK_TYPES: readonly ["produced_by", "applies_to", "informed_by", "contradicts"];
/** Observation types for claude-mem compatible observations. */
export declare const BRAIN_OBSERVATION_TYPES: readonly ["discovery", "change", "feature", "bugfix", "decision", "refactor"];
/** Source types for observations (how the observation was created). */
export declare const BRAIN_OBSERVATION_SOURCE_TYPES: readonly ["agent", "session-debrief", "claude-mem", "manual"];
/** Memory entity types for the links table. */
export declare const BRAIN_MEMORY_TYPES: readonly ["decision", "pattern", "learning", "observation"];
/** Sticky note status values. */
export declare const BRAIN_STICKY_STATUSES: readonly ["active", "converted", "archived"];
/** Sticky note colors. */
export declare const BRAIN_STICKY_COLORS: readonly ["yellow", "blue", "green", "red", "purple"];
/** Sticky note priority levels. */
export declare const BRAIN_STICKY_PRIORITIES: readonly ["low", "medium", "high"];
export declare const brainDecisions: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_decisions";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        type: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string enum";
            data: "process" | "architecture" | "technical" | "strategic" | "tactical";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["architecture", "technical", "process", "strategic", "tactical"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        decision: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        rationale: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        confidence: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string enum";
            data: "high" | "medium" | "low";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["low", "medium", "high"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        outcome: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string enum";
            data: "pending" | "success" | "failure" | "mixed";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["success", "failure", "mixed", "pending"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        alternativesJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        contextEpicId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        contextTaskId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        contextPhase: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        createdAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        updatedAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_decisions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
export declare const brainPatterns: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_patterns";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        type: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string enum";
            data: "success" | "workflow" | "failure" | "blocker" | "optimization";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["workflow", "blocker", "success", "failure", "optimization"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        pattern: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        context: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        frequency: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "number int53";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        successRate: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "number double";
            data: number;
            driverParam: number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        impact: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string enum";
            data: "high" | "medium" | "low";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["low", "medium", "high"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        antiPattern: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        mitigation: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        examplesJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        extractedAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        updatedAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_patterns";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
export declare const brainLearnings: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_learnings";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        insight: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        source: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        confidence: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "number double";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        actionable: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "boolean";
            data: boolean;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        application: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        applicableTypesJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        createdAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        updatedAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_learnings";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
/** General-purpose observations — replaces claude-mem's observations table. */
export declare const brainObservations: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_observations";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        type: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string enum";
            data: "discovery" | "change" | "feature" | "bugfix" | "decision" | "refactor";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["discovery", "change", "feature", "bugfix", "decision", "refactor"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        title: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        subtitle: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        narrative: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        factsJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        conceptsJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        project: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        filesReadJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        filesModifiedJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        sourceSessionId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        sourceType: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string enum";
            data: "manual" | "agent" | "session-debrief" | "claude-mem";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["agent", "session-debrief", "claude-mem", "manual"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        contentHash: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        discoveryTokens: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "number int53";
            data: number;
            driverParam: number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        createdAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        updatedAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_observations";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
/** Ephemeral sticky notes for quick capture before formal classification. */
export declare const brainStickyNotes: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_sticky_notes";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        content: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        createdAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        updatedAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        tagsJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        status: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string enum";
            data: "archived" | "active" | "converted";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["active", "converted", "archived"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        convertedToJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        color: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string enum";
            data: "yellow" | "blue" | "green" | "red" | "purple";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["yellow", "blue", "green", "red", "purple"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        priority: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string enum";
            data: "high" | "medium" | "low";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["low", "medium", "high"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        sourceType: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_sticky_notes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
/** Cross-references between BRAIN entries and tasks in tasks.db. */
export declare const brainMemoryLinks: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_memory_links";
    schema: undefined;
    columns: {
        memoryType: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_memory_links";
            dataType: "string enum";
            data: "pattern" | "decision" | "learning" | "observation";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["decision", "pattern", "learning", "observation"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        memoryId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_memory_links";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        taskId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_memory_links";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        linkType: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_memory_links";
            dataType: "string enum";
            data: "produced_by" | "applies_to" | "informed_by" | "contradicts";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["produced_by", "applies_to", "informed_by", "contradicts"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        createdAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_memory_links";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
export declare const brainSchemaMeta: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_schema_meta";
    schema: undefined;
    columns: {
        key: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_schema_meta";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        value: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_schema_meta";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
/** Node types for PageIndex graph. */
export declare const BRAIN_NODE_TYPES: readonly ["task", "doc", "file", "concept"];
/** Edge types for PageIndex graph. */
export declare const BRAIN_EDGE_TYPES: readonly ["depends_on", "relates_to", "implements", "documents"];
/** Documents/concepts as graph nodes for cross-document linking. */
export declare const brainPageNodes: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_page_nodes";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_nodes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        nodeType: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_nodes";
            dataType: "string enum";
            data: "file" | "task" | "doc" | "concept";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["task", "doc", "file", "concept"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        label: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_nodes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        metadataJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_nodes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        createdAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_nodes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
/** Directed links between graph nodes. */
export declare const brainPageEdges: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "brain_page_edges";
    schema: undefined;
    columns: {
        fromId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_edges";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        toId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_edges";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        edgeType: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_edges";
            dataType: "string enum";
            data: "depends_on" | "implements" | "relates_to" | "documents";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["depends_on", "relates_to", "implements", "documents"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        weight: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_edges";
            dataType: "number double";
            data: number;
            driverParam: number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        createdAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "brain_page_edges";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
export type BrainDecisionRow = typeof brainDecisions.$inferSelect;
export type NewBrainDecisionRow = typeof brainDecisions.$inferInsert;
export type BrainPatternRow = typeof brainPatterns.$inferSelect;
export type NewBrainPatternRow = typeof brainPatterns.$inferInsert;
export type BrainLearningRow = typeof brainLearnings.$inferSelect;
export type NewBrainLearningRow = typeof brainLearnings.$inferInsert;
export type BrainObservationRow = typeof brainObservations.$inferSelect;
export type NewBrainObservationRow = typeof brainObservations.$inferInsert;
export type BrainMemoryLinkRow = typeof brainMemoryLinks.$inferSelect;
export type NewBrainMemoryLinkRow = typeof brainMemoryLinks.$inferInsert;
export type BrainPageNodeRow = typeof brainPageNodes.$inferSelect;
export type NewBrainPageNodeRow = typeof brainPageNodes.$inferInsert;
export type BrainPageEdgeRow = typeof brainPageEdges.$inferSelect;
export type NewBrainPageEdgeRow = typeof brainPageEdges.$inferInsert;
export type BrainStickyNoteRow = typeof brainStickyNotes.$inferSelect;
export type NewBrainStickyNoteRow = typeof brainStickyNotes.$inferInsert;
//# sourceMappingURL=brain-schema.d.ts.map