/**
 * Drizzle ORM schema for CLEO nexus.db (SQLite via node:sqlite + sqlite-proxy).
 *
 * Tables: project_registry, nexus_audit_log, nexus_schema_meta
 * Stores cross-project registry and audit infrastructure for the Nexus domain.
 *
 * @task T5365
 */
/** Central registry of all CLEO projects known to the Nexus. */
export declare const projectRegistry: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "project_registry";
    schema: undefined;
    columns: {
        projectId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        projectHash: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        projectPath: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        name: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        registeredAt: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        lastSeen: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        healthStatus: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        healthLastCheck: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        permissions: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        lastSync: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        taskCount: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "number int53";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        labelsJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "project_registry";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
/** Append-only audit log for all Nexus operations across projects. */
export declare const nexusAuditLog: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "nexus_audit_log";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        timestamp: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        action: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        projectHash: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        projectId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        domain: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        operation: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        sessionId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        requestId: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        source: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        gateway: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        success: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "number int53";
            data: number;
            driverParam: number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        durationMs: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "number int53";
            data: number;
            driverParam: number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        detailsJson: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        errorMessage: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_audit_log";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
/** Key-value store for nexus.db schema versioning and metadata. */
export declare const nexusSchemaMeta: import("drizzle-orm/sqlite-core").SQLiteTableWithColumns<{
    name: "nexus_schema_meta";
    schema: undefined;
    columns: {
        key: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_schema_meta";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
        value: import("drizzle-orm/sqlite-core").SQLiteColumn<{
            name: string;
            tableName: "nexus_schema_meta";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}>;
    };
    dialect: "sqlite";
}>;
export type ProjectRegistryRow = typeof projectRegistry.$inferSelect;
export type NewProjectRegistryRow = typeof projectRegistry.$inferInsert;
export type NexusAuditLogRow = typeof nexusAuditLog.$inferSelect;
export type NewNexusAuditLogRow = typeof nexusAuditLog.$inferInsert;
export type NexusSchemaMetaRow = typeof nexusSchemaMeta.$inferSelect;
export type NewNexusSchemaMetaRow = typeof nexusSchemaMeta.$inferInsert;
//# sourceMappingURL=nexus-schema.d.ts.map