// @ts-nocheck — pre-existing scaffold script with dead code paths
/**
 * Config-file scaffolding: .gitignore, worktree-include, config.json,
 * project-info.json, and related template/version utilities.
 */

import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ScaffoldResult } from '@cleocode/contracts/scaffold-diagnostics';
import { generateProjectHash } from '../nexus/hash.js';
import { getConfigPath, resolveCanonicalCleoDir, resolveProjectByCwd } from '../paths.js';
import { saveJson } from '../store/json.js';

/**
 * Resolve the `.cleo` directory for scaffold steps.
 *
 * During first-time `cleo init`, `project-info.json` and nexus registration do
 * not exist yet, so the projectId-based resolver is intentionally unavailable.
 * Scaffold callers fall back to the local project root in that bootstrap window.
 *
 * @param projectRoot - Absolute path to the project root directory.
 * @returns Absolute path to the project's `.cleo` directory.
 */
export function resolveScaffoldCleoDir(projectRoot: string): string {
  try {
    const projectId = resolveProjectByCwd(projectRoot);
    return resolveCanonicalCleoDir(projectId);
  } catch {
    return join(projectRoot, '.cleo');
  }
}

/**
 * Embedded fallback for .cleo/.gitignore content (deny-by-default).
 *
 * ADR-013 §9: config.json / project-info.json are NOT re-included here.
 */
export const CLEO_GITIGNORE_FALLBACK = `# .cleo/.gitignore — Deny-by-default for CLEO project data
# Ignore everything, then explicitly allow only tracked files.
#
# ADR-013 §9 (2026-04-07, T5158): config.json + project-info.json are
# runtime snapshots regenerated by \`cleo init\`, not tracked in git.
# Recovery for all four runtime files (tasks.db, brain.db, config.json,
# project-info.json) is provided by \`cleo backup add\` snapshots under
# .cleo/backups/. See .cleo/adrs/ADR-013 for the full recovery story.

# Step 1: Ignore everything
*

# Allow list
!.gitignore
!project-context.json
!setup-otel.sh
!DATA-SAFETY-IMPLEMENTATION-SUMMARY.md
!adrs/
!adrs/**
!rcasd/
!rcasd/**
!agent-outputs/
!agent-outputs/**

# Explicit deny safety net
*.db
*.db-shm
*.db-wal
*.db-journal
config.json
project-info.json
log.json
bypass-log.json
qa-log.json
.deps-cache/
.context-alert-state.json
.context-state*.json
context-states/
.git-checkpoint-state
.migration-state.json
migrations.json
sync/
metrics/
.backups/
backups/

# Session journals — T1263 PSYCHE E6 (sensitive session data — task IDs, notes, agent IDs)
# Retain locally for meta-agent training; never commit to project git.
session-journals/
`;

/**
 * Embedded fallback for `.worktreeinclude` (canonical) content.
 *
 * The canonical location (T9983) is `<projectRoot>/.worktreeinclude` —
 * matches Claude Code Desktop + worktrunk-core. The legacy location
 * `<projectRoot>/.cleo/worktree-include` is still read for one deprecation
 * cycle; `cleo doctor --migrate-worktree-include` auto-migrates.
 *
 * @task T9983
 */
export const WORKTREE_INCLUDE_FALLBACK = `# .worktreeinclude — files to copy into agent worktrees on provisioning.
#
# Syntax: gitignore-style globs (parsed by ignore::gitignore via
# @cleocode/worktree-napi). Lines starting with \`!\` are negations.
#
# Local environment overrides (gitignored but required for dev)
.env.local
.env.development.local

# Package-manager configuration (registry auth, resolution rules)
.npmrc
.yarnrc
.pnpmrc
`;

/**
 * Resolve the package root directory (where schemas/ and templates/ live).
 *
 * @returns Absolute path to the @cleocode/core package root
 */
export function getPackageRoot(): string {
  const thisFile = fileURLToPath(import.meta.url);
  // ensure-config.ts lives in packages/core/src/scaffold/
  // going up 2 dirs reaches packages/core/
  return resolve(dirname(thisFile), '..', '..');
}

/**
 * Load the gitignore template from the package's templates/ directory.
 * Falls back to embedded content if file not found.
 *
 * @returns The .cleo/.gitignore template content string
 */
export function getGitignoreContent(): string {
  try {
    const packageRoot = getPackageRoot();
    const templatePath = join(packageRoot, 'templates', 'cleo-gitignore');
    if (existsSync(templatePath)) {
      return readFileSync(templatePath, 'utf-8');
    }
  } catch {
    // fallback
  }
  return CLEO_GITIGNORE_FALLBACK;
}

/**
 * Load the `.worktreeinclude` template from the package's templates/
 * directory.
 *
 * Resolution order (T9983):
 *  1. `templates/worktreeinclude` — canonical (matches the file name we
 *     write at the project root).
 *  2. `templates/worktree-include` — legacy template kept for one
 *     deprecation cycle so partially-updated installations keep working.
 *  3. {@link WORKTREE_INCLUDE_FALLBACK} embedded constant.
 *
 * @returns The `.worktreeinclude` template content string
 *
 * @task T9983
 */
export function getWorktreeIncludeContent(): string {
  try {
    const packageRoot = getPackageRoot();
    const canonicalTemplatePath = join(packageRoot, 'templates', 'worktreeinclude');
    if (existsSync(canonicalTemplatePath)) {
      return readFileSync(canonicalTemplatePath, 'utf-8');
    }
    const legacyTemplatePath = join(packageRoot, 'templates', 'worktree-include');
    if (existsSync(legacyTemplatePath)) {
      return readFileSync(legacyTemplatePath, 'utf-8');
    }
  } catch {
    // fallback
  }
  return WORKTREE_INCLUDE_FALLBACK;
}

/**
 * Read CLEO version from package.json.
 *
 * @returns Semver version string, or "0.0.0" if unavailable
 */
export function getCleoVersion(): string {
  try {
    const pkgPath = join(getPackageRoot(), 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    return pkg.version ?? '0.0.0';
  } catch {
    return '0.0.0';
  }
}

/** Detect whether projectRoot is the CLEO source repository itself. */
function isCleoContributorProject(projectRoot: string): boolean {
  const exists = (p: string) => existsSync(join(projectRoot, p));
  if (!exists('src/dispatch') || !exists('src/core')) return false;
  try {
    const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf-8')) as {
      name?: string;
    };
    return pkg.name === '@cleocode/cleo';
  } catch {
    return false;
  }
}

/**
 * Create default config.json content.
 *
 * @returns A plain object with the default CLEO configuration structure
 */
export function createDefaultConfig(): Record<string, unknown> {
  return {
    version: '2.10.0',
    output: {
      defaultFormat: 'json',
      showColor: true,
      showUnicode: true,
      dateFormat: 'relative',
    },
    backup: {
      maxOperationalBackups: 10,
      maxSafetyBackups: 5,
    },
    hierarchy: {
      maxDepth: 3,
      maxSiblings: 0,
    },
    session: {
      autoStart: false,
      multiSession: false,
    },
    lifecycle: {
      mode: 'strict',
    },
  };
}

/**
 * Create or repair .cleo/.gitignore from template.
 * Idempotent: skips if file already exists with correct content.
 *
 * @param projectRoot - Absolute path to the project root directory
 * @returns Scaffold result indicating whether the gitignore was created, repaired, or skipped
 */
export async function ensureGitignore(projectRoot: string): Promise<ScaffoldResult> {
  const cleoDir = resolveScaffoldCleoDir(projectRoot);
  const gitignorePath = join(cleoDir, '.gitignore');
  const templateContent = getGitignoreContent();

  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, 'utf-8');
    const normalize = (s: string) => s.trim().replace(/\r\n/g, '\n');
    if (normalize(existing) === normalize(templateContent)) {
      return { action: 'skipped', path: gitignorePath, details: 'Already matches template' };
    }
    await writeFile(gitignorePath, templateContent);
    return { action: 'repaired', path: gitignorePath, details: 'Updated to match template' };
  }

  await writeFile(gitignorePath, templateContent);
  return { action: 'created', path: gitignorePath };
}

/**
 * Create or repair `.worktreeinclude` (canonical, at project root) from the
 * shipped template. Idempotent — skips when the existing file already
 * matches the template byte-for-byte (after CR-LF + trim normalisation).
 *
 * Resolution rules (T9983):
 * - If `<projectRoot>/.worktreeinclude` already exists → keep + compare to
 *   the template; repair if drifted.
 * - Else if legacy `<projectRoot>/.cleo/worktree-include` exists → SKIP
 *   (do not overwrite the legacy file in place; `cleo doctor
 *   --migrate-worktree-include` is the explicit migration path).
 * - Else → write the canonical template.
 *
 * @param projectRoot - Absolute path to the project root directory
 * @returns Scaffold result indicating whether `.worktreeinclude` was
 *          created, repaired, or skipped.
 *
 * @task T9983
 */
export async function ensureWorktreeInclude(projectRoot: string): Promise<ScaffoldResult> {
  const canonicalPath = join(projectRoot, '.worktreeinclude');
  const legacyPath = join(resolveScaffoldCleoDir(projectRoot), 'worktree-include');
  const templateContent = getWorktreeIncludeContent();

  if (existsSync(canonicalPath)) {
    const existing = readFileSync(canonicalPath, 'utf-8');
    const normalize = (s: string) => s.trim().replace(/\r\n/g, '\n');
    if (normalize(existing) === normalize(templateContent)) {
      return { action: 'skipped', path: canonicalPath, details: 'Already matches template' };
    }
    await writeFile(canonicalPath, templateContent);
    return { action: 'repaired', path: canonicalPath, details: 'Updated to match template' };
  }

  // T9983: when only the legacy file exists, leave it in place. The reader
  // honours it under a one-cycle deprecation warning. Users opt-in to the
  // migration via `cleo doctor --migrate-worktree-include`.
  if (existsSync(legacyPath)) {
    return {
      action: 'skipped',
      path: legacyPath,
      details:
        'Legacy .cleo/worktree-include present — run `cleo doctor --migrate-worktree-include` to move to .worktreeinclude',
    };
  }

  await writeFile(canonicalPath, templateContent);
  return { action: 'created', path: canonicalPath };
}

/**
 * Create default config.json if missing.
 * Idempotent: skips if file already exists.
 *
 * @param projectRoot - Absolute path to the project root directory
 * @param opts - Optional configuration
 * @param opts.force - When true, overwrite the existing config
 * @returns Scaffold result indicating the action taken
 */
export async function ensureConfig(
  projectRoot: string,
  opts?: { force?: boolean },
): Promise<ScaffoldResult> {
  const configPath = getConfigPath(projectRoot);

  if (existsSync(configPath) && !opts?.force) {
    try {
      const existing = JSON.parse(readFileSync(configPath, 'utf-8')) as Record<string, unknown>;
      if (!existing['contributor'] && isCleoContributorProject(projectRoot)) {
        existing['contributor'] = {
          isContributorProject: true,
          devCli: 'cleo-dev',
          verifiedAt: new Date().toISOString(),
        };
        await writeFile(configPath, JSON.stringify(existing, null, 2));
        return {
          action: 'repaired',
          path: configPath,
          details: 'Added contributor block (ADR-029)',
        };
      }
    } catch {
      /* non-fatal */
    }
    return { action: 'skipped', path: configPath, details: 'Config already exists' };
  }

  const config = createDefaultConfig();
  if (isCleoContributorProject(projectRoot)) {
    (config as Record<string, unknown>)['contributor'] = {
      isContributorProject: true,
      devCli: 'cleo-dev',
      verifiedAt: new Date().toISOString(),
    };
  }
  await saveJson(configPath, config);
  return {
    action: existsSync(configPath) ? 'repaired' : 'created',
    path: configPath,
  };
}

/**
 * Create or refresh project-info.json.
 * Idempotent: skips if file exists (unless force).
 *
 * @param projectRoot - Absolute path to the project root directory
 * @param opts - Optional configuration
 * @param opts.force - When true, regenerate even if the file exists
 * @returns Scaffold result indicating the action taken
 */
export async function ensureProjectInfo(
  projectRoot: string,
  opts?: { force?: boolean },
): Promise<ScaffoldResult> {
  const cleoDir = resolveScaffoldCleoDir(projectRoot);
  const projectInfoPath = join(cleoDir, 'project-info.json');

  if (existsSync(projectInfoPath) && !opts?.force) {
    try {
      const existing = JSON.parse(readFileSync(projectInfoPath, 'utf-8'));
      if (typeof existing.projectId !== 'string' || existing.projectId.length === 0) {
        existing.projectId = randomUUID();
        existing.lastUpdated = new Date().toISOString();
        await writeFile(projectInfoPath, JSON.stringify(existing, null, 2));
        return { action: 'repaired', path: projectInfoPath, details: 'Added projectId' };
      }
    } catch {
      // If parse fails, fall through to regenerate
    }
    return { action: 'skipped', path: projectInfoPath, details: 'Already exists' };
  }

  const projectHash = generateProjectHash(projectRoot);
  const cleoVersion = getCleoVersion();
  const now = new Date().toISOString();

  const { readSchemaVersionFromFile } = await import('../validation/schema-integrity.js');
  const { SQLITE_SCHEMA_VERSION } = await import('../store/sqlite.js');
  const configSchemaVersion = readSchemaVersionFromFile('config.schema.json') ?? cleoVersion;
  const projectContextSchemaVersion =
    readSchemaVersionFromFile('project-context.schema.json') ?? '1.0.0';

  const projectInfo = {
    $schema: './schemas/project-info.schema.json',
    schemaVersion: '1.0.0',
    projectId: randomUUID(),
    projectHash,
    cleoVersion,
    lastUpdated: now,
    schemas: {
      config: configSchemaVersion,
      sqlite: SQLITE_SCHEMA_VERSION,
      projectContext: projectContextSchemaVersion,
    },
    injection: {
      'CLAUDE.md': null,
      'AGENTS.md': null,
      'GEMINI.md': null,
    },
    health: {
      status: 'unknown',
      lastCheck: null,
      issues: [],
    },
    features: {
      multiSession: false,
      verification: false,
      contextAlerts: false,
    },
  };

  await writeFile(projectInfoPath, JSON.stringify(projectInfo, null, 2));
  return { action: 'created', path: projectInfoPath };
}

/**
 * No-op. Kept for API compatibility.
 *
 * @param projectRoot - Absolute path to the project root directory
 * @returns Scaffold result with action "skipped"
 */
export async function ensureContributorMcp(projectRoot: string): Promise<ScaffoldResult> {
  return {
    action: 'skipped',
    path: projectRoot,
    details: 'Removed (Phase 2 production readiness)',
  };
}
