/**
 * Engine Re-exports for Dispatch Domain Handlers
 *
 * Centralizes the dispatch layer's engine imports into a single barrel.
 * All imports use dispatch/engines/ (which delegate to src/core/).
 *
 * @epic T4820
 * @task T4815
 */

// Pipeline manifest functions (moved from memory domain in T5241)
export {
  filterEntries as filterManifestEntries,
  type ManifestEntry as ResearchManifestEntry,
  pipelineManifestAppend,
  pipelineManifestArchive,
  pipelineManifestFind,
  pipelineManifestList,
  pipelineManifestPending,
  pipelineManifestShow,
  pipelineManifestStats,
  readManifestEntries,
} from '../../core/memory/pipeline-manifest-sqlite.js';
export type { Session as SessionRecord } from '../../types/session.js';
// Config engine
export {
  configGet,
  configSet,
} from '../engines/config-engine.js';
// Init engine
export {
  ensureInitialized,
  getVersion,
  initProject,
  isAutoInitEnabled,
} from '../engines/init-engine.js';
// Lifecycle engine
export {
  lifecycleCheck,
  lifecycleGateFail,
  lifecycleGatePass,
  lifecycleGates,
  lifecycleHistory,
  lifecyclePrerequisites,
  lifecycleProgress,
  lifecycleReset,
  lifecycleSkip,
  lifecycleStatus,
} from '../engines/lifecycle-engine.js';
// Memory engine — brain.db cognitive memory (T5241 cutover)
export {
  memoryBrainStats,
  memoryContradictions,
  memoryDecisionFind,
  memoryDecisionStore,
  memoryFetch,
  memoryFind,
  memoryGraphAdd,
  memoryGraphNeighbors,
  memoryGraphRemove,
  memoryGraphShow,
  memoryLearningFind,
  memoryLearningStats,
  memoryLearningStore,
  memoryLink,
  memoryObserve,
  memoryPatternFind,
  memoryPatternStats,
  memoryPatternStore,
  memoryReasonSimilar,
  memoryReasonWhy,
  memorySearchHybrid,
  memoryShow,
  memorySuperseded,
  memoryTimeline,
  memoryUnlink,
} from '../engines/memory-engine.js';
// Orchestrate engine
export {
  orchestrateAnalyze,
  orchestrateBootstrap,
  orchestrateCheck,
  orchestrateContext,
  orchestrateCriticalPath,
  orchestrateHandoff,
  orchestrateNext,
  orchestrateParallelEnd,
  orchestrateParallelStart,
  orchestrateReady,
  orchestrateSkillInject,
  orchestrateSpawn,
  orchestrateSpawnExecute,
  orchestrateStartup,
  orchestrateStatus,
  orchestrateUnblockOpportunities,
  orchestrateValidate,
  orchestrateWaves,
} from '../engines/orchestrate-engine.js';
// Pipeline engine (Phase operations)
export {
  phaseAdvance,
  phaseComplete,
  phaseDelete,
  phaseList,
  phaseRename,
  phaseSet,
  phaseShow,
  phaseStart,
} from '../engines/pipeline-engine.js';
// Release engine
export {
  releaseCancel,
  releaseChangelog,
  releaseCommit,
  releaseGatesRun,
  releaseList,
  releasePrepare,
  releasePush,
  releaseRollback,
  releaseShip,
  releaseShow,
  releaseTag,
} from '../engines/release-engine.js';
// Session engine
export {
  type DecisionRecord,
  sessionArchive,
  sessionBriefing,
  sessionChainShow,
  sessionCleanup,
  // T4959: Rich debrief + chain
  sessionComputeDebrief,
  sessionComputeHandoff,
  sessionContextDrift,
  sessionContextInject,
  sessionDebriefShow,
  sessionDecisionLog,
  sessionEnd,
  // T5119: Lightweight session discovery
  sessionFind,
  sessionGc,
  sessionHandoff,
  sessionHistory,
  sessionList,
  sessionRecordAssumption,
  sessionRecordDecision,
  sessionResume,
  sessionShow,
  sessionStart,
  sessionStats,
  sessionStatus,
  sessionSuspend,
  sessionSwitch,
  taskCurrentGet,
  taskStart,
  taskStop,
  taskWorkHistory,
} from '../engines/session-engine.js';
// System engine
export {
  type ArchiveStatsData,
  type AuditData,
  type BackupData,
  backupRestore,
  type CleanupData,
  type ComplianceData,
  type ContextData,
  type DashboardData,
  type DiagnosticsData,
  type HealthData,
  type HelpData,
  type InjectGenerateData,
  type LabelsData,
  type LogQueryData,
  type MetricsData,
  type MigrateData,
  type RestoreData,
  type RoadmapData,
  type RuntimeData,
  type SafestopData,
  type SequenceData,
  type StatsData,
  type SyncData,
  systemArchiveStats,
  systemAudit,
  systemBackup,
  systemCleanup,
  systemCompliance,
  systemContext,
  systemDash,
  systemDiagnostics,
  systemDoctor,
  systemFix,
  systemHealth,
  systemHelp,
  systemInjectGenerate,
  systemLabels,
  systemLog,
  systemMetrics,
  systemMigrate,
  systemRestore,
  systemRoadmap,
  systemRuntime,
  systemSafestop,
  systemSequence,
  systemSequenceRepair,
  systemStats,
  systemSync,
  systemUncancel,
  type UncancelData,
} from '../engines/system-engine.js';
// Task engine (CRUD + non-CRUD operations)
export {
  type CompactTask,
  type MinimalTaskRecord,
  type TaskRecord,
  taskAnalyze,
  taskArchive,
  taskBatchValidate,
  taskBlockers,
  taskCancel,
  taskComplete,
  taskComplexityEstimate,
  taskCreate,
  taskDelete,
  taskDepends,
  taskDeps,
  taskDepsCycles,
  taskDepsOverview,
  taskExists,
  taskExport,
  taskFind,
  taskHistory,
  taskImport,
  taskLabelList,
  taskLabelShow,
  taskLint,
  taskList,
  taskNext,
  taskPlan,
  taskPromote,
  taskRelates,
  taskRelatesAdd,
  taskRelatesFind,
  taskReopen,
  taskReorder,
  taskReparent,
  taskRestore,
  taskShow,
  taskStats,
  taskTree,
  taskUnarchive,
  taskUpdate,
} from '../engines/task-engine.js';
// Template parser engine
export {
  generateTemplateConfig,
  getTemplateForSubcommand,
  type IssueTemplate,
  parseIssueTemplates,
  type TemplateConfig,
  type TemplateSection,
  validateLabels,
} from '../engines/template-parser.js';
// Validate engine
export {
  validateBatchValidate,
  validateCoherenceCheck,
  validateComplianceRecord,
  validateComplianceSummary,
  validateComplianceViolations,
  validateGateVerify,
  validateManifest as validateManifestOp,
  validateOutput,
  validateProtocol,
  // T5327: Protocol validation operations
  validateProtocolConsensus,
  validateProtocolContribution,
  validateProtocolDecomposition,
  validateProtocolImplementation,
  validateProtocolSpecification,
  validateSchemaOp,
  validateTask as validateTaskOp,
  validateTestCoverage,
  validateTestRun,
  validateTestStatus,
} from '../engines/validate-engine.js';
