#!/usr/bin/env bash
# Orphan disposition — generated by Agent C
# Source: /mnt/projects/cleocode/.cleo/agent-outputs/CLEANUP-2026-05-11/baseline-deps-validate.json
# 124 orphans + 7 extra epic-level test fixtures = 131 total deletions
# All entries classified as TEST_FIXTURE_DELETE — zero REAL_REPARENT, zero UNCERTAIN

set -uo pipefail
DELETED=0; SKIPPED=0
trap 'echo "Deletions done: $DELETED succeeded, $SKIPPED skipped"' EXIT

echo "==== Section 1: Orphan deletions (leaves first) ===="

echo "[DELETE] T-RECONCILE-FOLLOWUP-v2026.5.38-2 — Reconcile T1889 for v2026.5.38 (verification absent)"
cleo delete T-RECONCILE-FOLLOWUP-v2026.5.38-2 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T-RECONCILE-FOLLOWUP-v2026.5.38-3 — Reconcile T9031 for v2026.5.38 (verification absent)"
cleo delete T-RECONCILE-FOLLOWUP-v2026.5.38-3 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T-cap-001 — Capacity test task"
cleo delete T-cap-001 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T000 — Task 0"
cleo delete T000 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T005 — Task 5"
cleo delete T005 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T006 — Task 6"
cleo delete T006 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T007 — Task 7"
cleo delete T007 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T008 — Task 8"
cleo delete T008 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T009 — Task 9"
cleo delete T009 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T010 — Task 10"
cleo delete T010 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T011 — Task 11"
cleo delete T011 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T012 — Task 12"
cleo delete T012 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T013 — Task 13"
cleo delete T013 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T014 — Task 14"
cleo delete T014 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T015 — Task 15"
cleo delete T015 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T016 — Task 16"
cleo delete T016 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T017 — Task 17"
cleo delete T017 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T018 — Task 18"
cleo delete T018 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T019 — Task 19"
cleo delete T019 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T020 — Task 20"
cleo delete T020 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T021 — Task 21"
cleo delete T021 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T022 — Task 22"
cleo delete T022 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T023 — Task 23"
cleo delete T023 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T024 — Task 24"
cleo delete T024 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T025 — Task 25"
cleo delete T025 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T026 — Task 26"
cleo delete T026 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T027 — Task 27"
cleo delete T027 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T028 — Task 28"
cleo delete T028 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T029 — Task 29"
cleo delete T029 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T030 — Task 30"
cleo delete T030 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T031 — Task 31"
cleo delete T031 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T032 — Task 32"
cleo delete T032 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T033 — Task 33"
cleo delete T033 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T034 — Task 34"
cleo delete T034 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T035 — Task 35"
cleo delete T035 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T036 — Task 36"
cleo delete T036 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T037 — Task 37"
cleo delete T037 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T038 — Task 38"
cleo delete T038 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T039 — Task 39"
cleo delete T039 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T040 — Task 40"
cleo delete T040 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T041 — Task 41"
cleo delete T041 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T042 — Task 42"
cleo delete T042 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T043 — Task 43"
cleo delete T043 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T044 — Task 44"
cleo delete T044 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T045 — Task 45"
cleo delete T045 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T046 — Task 46"
cleo delete T046 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T047 — Task 47"
cleo delete T047 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T048 — Task 48"
cleo delete T048 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T049 — Task 49"
cleo delete T049 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T050 — Task 50"
cleo delete T050 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T051 — Task 51"
cleo delete T051 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T052 — Task 52"
cleo delete T052 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T053 — Task 53"
cleo delete T053 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T054 — Task 54"
cleo delete T054 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T055 — Task 55"
cleo delete T055 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T056 — Task 56"
cleo delete T056 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T057 — Task 57"
cleo delete T057 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T058 — Task 58"
cleo delete T058 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T059 — Task 59"
cleo delete T059 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T060 — Task 60"
cleo delete T060 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T061 — Task 61"
cleo delete T061 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T062 — Task 62"
cleo delete T062 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T063 — Task 63"
cleo delete T063 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T064 — Task 64"
cleo delete T064 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T065 — Task 65"
cleo delete T065 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T066 — Task 66"
cleo delete T066 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T067 — Task 67"
cleo delete T067 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T068 — Task 68"
cleo delete T068 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T069 — Task 69"
cleo delete T069 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T070 — Task 70"
cleo delete T070 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T071 — Task 71"
cleo delete T071 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T072 — Task 72"
cleo delete T072 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T073 — Task 73"
cleo delete T073 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T074 — Task 74"
cleo delete T074 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T075 — Task 75"
cleo delete T075 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T076 — Task 76"
cleo delete T076 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T077 — Task 77"
cleo delete T077 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T078 — Task 78"
cleo delete T078 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T079 — Task 79"
cleo delete T079 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T080 — Task 80"
cleo delete T080 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T100 — Task 100"
cleo delete T100 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T101 — P0 bug"
cleo delete T101 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T106 — Target 6"
cleo delete T106 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T110 — Task 10"
cleo delete T110 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T111 — Task 11"
cleo delete T111 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T112 — Task 12"
cleo delete T112 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T113 — Task 13"
cleo delete T113 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T114 — Task 14"
cleo delete T114 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T115 — Task 15"
cleo delete T115 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T116 — Task 16"
cleo delete T116 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T117 — Task 17"
cleo delete T117 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T118 — Task 18"
cleo delete T118 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T119 — Task 19"
cleo delete T119 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T1335 — Task (imported)"
cleo delete T1335 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T1364 — Task (imported-2)"
cleo delete T1364 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T1367 — Test task (imported-2)"
cleo delete T1367 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T1957 — Auth API (imported-3)"
cleo delete T1957 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T1961 — Task (imported-3)"
cleo delete T1961 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T1965 — Task (imported-4)"
cleo delete T1965 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T1969 — Frontend auth (imported)"
cleo delete T1969 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T200 — Research task"
cleo delete T200 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T201 — Work task"
cleo delete T201 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T300 — Spike task alpha"
cleo delete T300 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T301 — Spike task beta"
cleo delete T301 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T302 — Documented"
cleo delete T302 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T400 — Default role task"
cleo delete T400 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T401 — Default scope task"
cleo delete T401 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T402 — Task T402"
cleo delete T402 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T500 — Task T500"
cleo delete T500 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T501 — Partial gates"
cleo delete T501 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T502 — Ready"
cleo delete T502 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T503 — Dep task"
cleo delete T503 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T504 — Blocked task"
cleo delete T504 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T506 — Task with done dep"
cleo delete T506 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T601 — Pending dep"
cleo delete T601 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T602 — Blocked"
cleo delete T602 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T605 — Needs verify"
cleo delete T605 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T606 — Ready to spawn"
cleo delete T606 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T701 — Task T701"
cleo delete T701 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T702 — Third"
cleo delete T702 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T8001 — Verified work shipped in v0"
cleo delete T8001 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T8002 — Unverified work"
cleo delete T8002 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T8003 — Verified work (dry-run case)"
cleo delete T8003 --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE] T932E — T932 integration epic"
cleo delete T932E --force && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "==== Section 1b: Epic-level test fixtures (with --cascade) ===="

echo "[DELETE-CASCADE] E1 — Test Epic (epic-level fixture)"
cleo delete E1 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T603 — Epic (epic-level fixture)"
cleo delete T603 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T932EP — T932 standalone epic with no files (epic-level fixture)"
cleo delete T932EP --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T1972 — Epic: Auth (imported-2) (epic-level fixture)"
cleo delete T1972 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T800 — Task T800 (epic) (epic-level fixture)"
cleo delete T800 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T810 — Task T810 (epic) (epic-level fixture)"
cleo delete T810 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T1958 — JWT tokens (imported) (epic-level fixture)"
cleo delete T1958 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T1962 — JWT tokens (imported-2) (epic-level fixture)"
cleo delete T1962 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[DELETE-CASCADE] T1966 — JWT tokens (imported-3) (epic-level fixture)"
cleo delete T1966 --force --cascade && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "==== Section 1c: Re-issue --cascade for orphan IDs that are also epic-level fixtures ===="
# These commands are idempotent — if the task is already gone they no-op

echo "[CASCADE-CLEANUP] T932E (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T932E --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[CASCADE-CLEANUP] T1957 (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T1957 --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[CASCADE-CLEANUP] T1961 (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T1961 --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[CASCADE-CLEANUP] T1965 (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T1965 --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[CASCADE-CLEANUP] T1969 (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T1969 --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[CASCADE-CLEANUP] T1335 (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T1335 --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[CASCADE-CLEANUP] T1364 (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T1364 --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "[CASCADE-CLEANUP] T1367 (was leaf-deleted above; cascade to catch any orphan children)"
cleo delete T1367 --force --cascade 2>/dev/null || true && DELETED=$((DELETED+1)) || SKIPPED=$((SKIPPED+1))

echo "==== Section 2: Reparents ===="
# (none — every orphan was a test fixture)

echo "Done."
