-- T13318 (journal spec §3.1 "Receive") — a per-origin floor for the
-- seen-transaction ledger.
--
-- A transaction id is `<replica>:<local_seq>`, and every origin's
-- transactions are FIRST delivered in local_seq order (the sealer mints
-- local_seq rising, a segment packs the lowest sealed ones in order, and
-- pullers refuse a replicaSeq gap or replay). So per (stream, origin):
--
-- staged_upto: the highest local_seq staged. A transaction at or below it
--   that has no _sync_seen_txn row was either pruned or arrived out of order;
--   the pull refuses it loudly, never skips it as seen.
-- pruned_upto: seen rows at or below it were dropped (0: none), so a refusal
--   can say which of the two it is.
-- seen_rows, seen_bytes: the origin's _sync_seen_txn rows and their payload
--   bytes, kept with every insert and prune, so `cleo cloud status` sums this
--   table instead of walking the ledger.
--
-- The backfill seeds the floor from rows staged before this table existed.
--
-- Local-only.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_seen_floor (
  stream      TEXT NOT NULL,
  origin      TEXT NOT NULL,
  staged_upto INTEGER NOT NULL,
  pruned_upto INTEGER NOT NULL DEFAULT 0,
  seen_rows   INTEGER NOT NULL DEFAULT 0,
  seen_bytes  INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (stream, origin)
) WITHOUT ROWID;
INSERT OR IGNORE INTO _sync_seen_floor (stream, origin, staged_upto, pruned_upto, seen_rows, seen_bytes)
SELECT stream,
       substr(txn, 1, instr(txn, ':') - 1),
       max(CAST(substr(txn, instr(txn, ':') + 1) AS INTEGER)),
       0,
       count(*),
       sum(octet_length(stream) + octet_length(txn) + 8)
  FROM _sync_seen_txn
 WHERE instr(txn, ':') > 1
 GROUP BY stream, substr(txn, 1, instr(txn, ':') - 1);
