//! Build script for cant-core: generates `src/generated/events.rs` from
//! `packages/caamp/providers/hook-mappings.json` (the canonical SSoT for all
//! event definitions).

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

struct EventEntry {
    name: String,
    category: String,
    source: String,
    can_block: bool,
    description: String,
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let json_path =
        Path::new(&manifest_dir).join("../../packages/caamp/providers/hook-mappings.json");

    println!("cargo:rerun-if-changed={}", json_path.display());

    let (entries, categories, sources) = parse_mappings(&json_path);
    let code = generate_code(&entries, &categories, &sources);

    let out_dir = Path::new(&manifest_dir).join("src/generated");
    fs::create_dir_all(&out_dir).expect("Failed to create src/generated/");
    fs::write(out_dir.join("events.rs"), &code).expect("Failed to write events.rs");
    fs::write(
        out_dir.join("mod.rs"),
        "// @generated — DO NOT EDIT.\n\npub mod events;\n",
    )
    .expect("Failed to write mod.rs");
}

fn parse_mappings(json_path: &Path) -> (Vec<EventEntry>, BTreeSet<String>, BTreeSet<String>) {
    let json_str = fs::read_to_string(json_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", json_path.display(), e));
    let mappings: serde_json::Value =
        serde_json::from_str(&json_str).expect("Failed to parse hook-mappings.json");

    let events = mappings["canonicalEvents"]
        .as_object()
        .expect("canonicalEvents must be an object");

    let mut categories = BTreeSet::new();
    let mut sources = BTreeSet::new();
    let mut entries = Vec::new();

    for (name, meta) in events {
        let category = meta["category"]
            .as_str()
            .unwrap_or_else(|| panic!("Event '{}' missing category", name))
            .to_string();
        let source = meta["source"]
            .as_str()
            .unwrap_or_else(|| panic!("Event '{}' missing source", name))
            .to_string();
        let can_block = meta["canBlock"].as_bool().unwrap_or(false);
        let description = meta["description"].as_str().unwrap_or("").to_string();

        categories.insert(category.clone());
        sources.insert(source.clone());
        entries.push(EventEntry {
            name: name.clone(),
            category,
            source,
            can_block,
            description,
        });
    }

    // Sort: provider events first, then domain events; alphabetical within each group
    entries.sort_by(|a, b| {
        let source_order = |s: &str| -> u8 {
            match s {
                "provider" => 0,
                "domain" => 1,
                _ => 2,
            }
        };
        source_order(&a.source)
            .cmp(&source_order(&b.source))
            .then(a.name.cmp(&b.name))
    });

    (entries, categories, sources)
}

fn generate_code(
    entries: &[EventEntry],
    categories: &BTreeSet<String>,
    sources: &BTreeSet<String>,
) -> String {
    let mut c = String::with_capacity(8192);

    c.push_str(
        "// @generated — DO NOT EDIT. Source: packages/caamp/providers/hook-mappings.json\n",
    );
    c.push_str("// Generated by crates/cant-core/build.rs\n\n");
    c.push_str("use serde::{Deserialize, Serialize};\n\n");

    gen_category_enum(&mut c, categories);
    gen_source_enum(&mut c, sources);
    gen_event_enum(&mut c, entries);
    gen_event_impl(&mut c, entries);
    gen_helpers(&mut c, entries);

    c
}

fn gen_category_enum(c: &mut String, categories: &BTreeSet<String>) {
    c.push_str("/// Event categories derived from hook-mappings.json.\n");
    c.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    c.push_str("pub enum EventCategory {\n");
    for cat in categories {
        c.push_str(&format!(
            "    /// `{}` category.\n    {},\n",
            cat,
            pascal_case(cat)
        ));
    }
    c.push_str("}\n\n");
    c.push_str("impl EventCategory {\n");
    c.push_str("    /// Returns the lowercase string representation.\n");
    c.push_str("    pub const fn as_str(&self) -> &'static str {\n");
    c.push_str("        match self {\n");
    for cat in categories {
        c.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            pascal_case(cat),
            cat
        ));
    }
    c.push_str("        }\n    }\n}\n\n");
}

fn gen_source_enum(c: &mut String, sources: &BTreeSet<String>) {
    c.push_str("/// Event source types derived from hook-mappings.json.\n");
    c.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    c.push_str("pub enum EventSource {\n");
    for src in sources {
        c.push_str(&format!(
            "    /// `{}` source.\n    {},\n",
            src,
            pascal_case(src)
        ));
    }
    c.push_str("}\n\n");
    c.push_str("impl EventSource {\n");
    c.push_str("    /// Returns the lowercase string representation.\n");
    c.push_str("    pub const fn as_str(&self) -> &'static str {\n");
    c.push_str("        match self {\n");
    for src in sources {
        c.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            pascal_case(src),
            src
        ));
    }
    c.push_str("        }\n    }\n}\n\n");
}

fn gen_event_enum(c: &mut String, entries: &[EventEntry]) {
    c.push_str(
        "/// All canonical events (provider + domain) derived from hook-mappings.json.\n///\n",
    );
    c.push_str(&format!(
        "/// Total: {} events ({} provider, {} domain).\n",
        entries.len(),
        entries.iter().filter(|e| e.source == "provider").count(),
        entries.iter().filter(|e| e.source == "domain").count(),
    ));
    c.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    c.push_str("pub enum CanonicalEvent {\n");

    let mut current_source = String::new();
    for entry in entries {
        if entry.source != current_source {
            current_source.clone_from(&entry.source);
            c.push_str(&format!(
                "\n    // {} events\n",
                pascal_case(&current_source)
            ));
        }
        c.push_str(&format!(
            "    /// {} — `{}` category. {}.\n    {},\n",
            entry.name, entry.category, entry.description, entry.name
        ));
    }
    c.push_str("}\n\n");
}

fn gen_event_impl(c: &mut String, entries: &[EventEntry]) {
    c.push_str("impl CanonicalEvent {\n");

    // ALL const
    c.push_str("    /// All canonical events in registry order.\n");
    c.push_str("    pub const ALL: &[Self] = &[\n");
    for e in entries {
        c.push_str(&format!("        Self::{},\n", e.name));
    }
    c.push_str("    ];\n\n");

    // as_str
    gen_const_match(c, "as_str", "&'static str", entries, |e| {
        format!("\"{}\"", e.name)
    });

    // from_str
    c.push_str("    /// Parses a PascalCase event name. O(1) via compiler-optimized match.\n");
    c.push_str("    pub fn from_str(s: &str) -> Option<Self> {\n");
    c.push_str("        match s {\n");
    for e in entries {
        c.push_str(&format!(
            "            \"{}\" => Some(Self::{}),\n",
            e.name, e.name
        ));
    }
    c.push_str("            _ => None,\n        }\n    }\n\n");

    // category
    gen_const_match(c, "category", "EventCategory", entries, |e| {
        format!("EventCategory::{}", pascal_case(&e.category))
    });

    // source
    gen_const_match(c, "source", "EventSource", entries, |e| {
        format!("EventSource::{}", pascal_case(&e.source))
    });

    // can_block
    gen_const_match(c, "can_block", "bool", entries, |e| {
        format!("{}", e.can_block)
    });

    // description
    gen_const_match(c, "description", "&'static str", entries, |e| {
        format!("\"{}\"", e.description.replace('"', "\\\""))
    });

    // Iterator methods
    c.push_str("    /// Returns all events that can block execution.\n");
    c.push_str("    pub fn blocking_events() -> impl Iterator<Item = Self> {\n");
    c.push_str("        Self::ALL.iter().copied().filter(|e| e.can_block())\n    }\n\n");

    c.push_str("    /// Returns all provider-sourced events.\n");
    c.push_str("    pub fn provider_events() -> impl Iterator<Item = Self> {\n");
    c.push_str("        Self::ALL.iter().copied().filter(|e| matches!(e.source(), EventSource::Provider))\n    }\n\n");

    c.push_str("    /// Returns all domain-sourced events.\n");
    c.push_str("    pub fn domain_events() -> impl Iterator<Item = Self> {\n");
    c.push_str("        Self::ALL.iter().copied().filter(|e| matches!(e.source(), EventSource::Domain))\n    }\n");

    c.push_str("}\n\n");
}

fn gen_const_match(
    c: &mut String,
    name: &str,
    ret: &str,
    entries: &[EventEntry],
    value_fn: impl Fn(&EventEntry) -> String,
) {
    let doc = match name {
        "as_str" => "Returns the PascalCase string name.",
        "category" => "Returns the event category.",
        "source" => "Returns the event source (provider or domain).",
        "can_block" => "Whether a hook handler can block the associated action.",
        "description" => "Human-readable description for LSP hover and diagnostics.",
        _ => "",
    };
    c.push_str(&format!("    /// {}\n", doc));
    c.push_str(&format!("    pub const fn {}(&self) -> {} {{\n", name, ret));
    c.push_str("        match self {\n");
    for e in entries {
        c.push_str(&format!(
            "            Self::{} => {},\n",
            e.name,
            value_fn(e)
        ));
    }
    c.push_str("        }\n    }\n\n");
}

fn gen_helpers(c: &mut String, entries: &[EventEntry]) {
    let all_names: Vec<&str> = entries.iter().map(|e| e.name.as_str()).collect();
    c.push_str("/// Comma-separated list of all canonical event names for diagnostic messages.\n");
    c.push_str(&format!(
        "pub const CANONICAL_EVENT_NAMES_CSV: &str = \"{}\";\n\n",
        all_names.join(", ")
    ));

    c.push_str("/// Returns true if the given string is a valid canonical event name.\n///\n");
    c.push_str("/// Backward-compatible wrapper around `CanonicalEvent::from_str`.\n");
    c.push_str("pub fn is_canonical_event(name: &str) -> bool {\n");
    c.push_str("    CanonicalEvent::from_str(name).is_some()\n}\n");
}

/// Converts a lowercase string to PascalCase.
fn pascal_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}
