//! Build script for `signaldock-storage`.
//!
//! Generates a Rust source file (`OUT_DIR/sqlite_pragmas_generated.rs`) that
//! defines the canonical SQLite pragma SQL string from the repo-root SSoT at
//! `specs/sqlite-pragmas.json`. The generated module is `include!`'d by
//! `src/adapters/diesel_store.rs` so the runtime SQL applied to every
//! pooled connection is byte-identical to the SQL produced by the
//! TypeScript side (`packages/core/src/store/sqlite-pragmas.ts`).
//!
//! This is the Rust half of the SSoT pattern documented in T9053 and
//! mirrors how CAAMP consumes `providers/hook-mappings.json`.
//!
//! The build script intentionally avoids any third-party JSON crate so it
//! does not pull additional `[build-dependencies]` into the workspace —
//! the JSON we care about is a tiny well-formed object with a known shape,
//! and we only need to extract the `pragmas` array of `[name, value]`
//! pairs. A focused hand-written parser is enough and keeps build times low.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Locate specs/sqlite-pragmas.json relative to the workspace root.
    // CARGO_MANIFEST_DIR points at crates/signaldock-storage; the SSoT lives
    // four levels up (.../crates/signaldock-storage → workspace root).
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let spec_path = manifest_dir
        .join("..")
        .join("..")
        .join("specs")
        .join("sqlite-pragmas.json");

    println!("cargo:rerun-if-changed={}", spec_path.display());

    let raw = fs::read_to_string(&spec_path).unwrap_or_else(|e| {
        panic!(
            "T9053 SSoT missing or unreadable at {}: {e}\n\
             specs/sqlite-pragmas.json is the canonical source for SQLite \
             pragmas consumed by both packages/core (TS) and \
             signaldock-storage (Rust).",
            spec_path.display()
        )
    });

    let pragmas = parse_pragmas(&raw).unwrap_or_else(|e| {
        panic!(
            "Failed to parse {} as the SSoT pragma spec: {e}",
            spec_path.display()
        )
    });

    // Render the canonical SQL: each entry as `PRAGMA name = value`,
    // joined with `;\n`. Identical to the JS `renderPragmaSql` +
    // `CANONICAL_PRAGMA_SQL` join used in sqlite-pragmas.ts.
    let sql_string = pragmas
        .iter()
        .map(|(name, value)| format!("PRAGMA {name} = {value}"))
        .collect::<Vec<_>>()
        .join(";\n");

    // Produce a runtime form usable by `SimpleConnection::batch_execute`,
    // which expects a single string with `;`-terminated statements.
    let batch_sql = format!("{sql_string};");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path: PathBuf = Path::new(&out_dir).join("sqlite_pragmas_generated.rs");

    let mut generated = String::new();
    generated
        .push_str("// @generated — DO NOT EDIT. Source: specs/sqlite-pragmas.json (T9053 SSoT).\n");
    generated
        .push_str("// Regenerated by crates/signaldock-storage/build.rs on every cargo build.\n\n");
    generated.push_str(
        "/// Canonical pragma SQL — equivalent to the TS `CANONICAL_PRAGMA_SQL` const.\n",
    );
    generated.push_str(&format!(
        "pub const SQLITE_PRAGMA_SQL: &str = {};\n\n",
        rust_string_literal(&sql_string)
    ));
    generated.push_str("/// Same SQL with a trailing `;` so it is ready for `batch_execute`.\n");
    generated.push_str(&format!(
        "pub const SQLITE_PRAGMA_SQL_BATCH: &str = {};\n\n",
        rust_string_literal(&batch_sql)
    ));
    generated.push_str(
        "/// Canonical (name, value) pairs in declared order — mirror of TS `CANONICAL_PRAGMAS`.\n",
    );
    generated.push_str(&format!(
        "pub const SQLITE_PRAGMAS: &[(&str, &str)] = &[\n{}];\n",
        pragmas
            .iter()
            .map(|(n, v)| format!(
                "    ({}, {}),\n",
                rust_string_literal(n),
                rust_string_literal(v)
            ))
            .collect::<String>()
    ));

    fs::write(&out_path, generated).expect("write sqlite_pragmas_generated.rs");
}

/// Convert a Rust string into a safely-quoted Rust string literal,
/// preferring a raw string when no `"` or `#` is present in the source
/// (which is the case for every pragma we ship).
fn rust_string_literal(s: &str) -> String {
    if !s.contains('"') && !s.contains('\\') && !s.contains('\r') {
        // Use a raw literal preserving newlines exactly as-is.
        format!("r#\"{s}\"#")
    } else {
        let mut out = String::with_capacity(s.len() + 2);
        out.push('"');
        for ch in s.chars() {
            match ch {
                '\\' => out.push_str("\\\\"),
                '"' => out.push_str("\\\""),
                '\n' => out.push_str("\\n"),
                '\r' => out.push_str("\\r"),
                '\t' => out.push_str("\\t"),
                c => out.push(c),
            }
        }
        out.push('"');
        out
    }
}

/// Minimal JSON-aware extractor for the `pragmas` array of
/// `["name", "value"]` pairs. Tolerant of whitespace, ignores keys other
/// than `pragmas`. Errors if the array is malformed or the file lacks a
/// `pragmas` field — better to fail the build loudly than ship empty SQL.
fn parse_pragmas(src: &str) -> Result<Vec<(String, String)>, String> {
    let key = "\"pragmas\"";
    let key_idx = src
        .find(key)
        .ok_or_else(|| "missing \"pragmas\" key".to_string())?;
    let after_key = &src[key_idx + key.len()..];
    let colon_rel = after_key
        .find(':')
        .ok_or_else(|| "expected ':' after \"pragmas\"".to_string())?;
    let after_colon = &after_key[colon_rel + 1..];
    let arr_start_rel = after_colon
        .find('[')
        .ok_or_else(|| "expected '[' starting pragmas array".to_string())?;
    let after_open = &after_colon[arr_start_rel + 1..];

    // Find the matching closing bracket by tracking depth and skipping strings.
    let mut depth: i32 = 1;
    let mut in_string = false;
    let mut escape = false;
    let mut end_rel: Option<usize> = None;
    for (i, ch) in after_open.char_indices() {
        if in_string {
            if escape {
                escape = false;
            } else if ch == '\\' {
                escape = true;
            } else if ch == '"' {
                in_string = false;
            }
            continue;
        }
        match ch {
            '"' => in_string = true,
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    end_rel = Some(i);
                    break;
                }
            }
            _ => {}
        }
    }
    let end_rel = end_rel.ok_or_else(|| "unterminated pragmas array".to_string())?;
    let body = &after_open[..end_rel];

    // Body looks like: `["name","value"], ["name","value"], ...`
    // Walk char by char, collecting inner pairs.
    let mut out: Vec<(String, String)> = Vec::new();
    let bytes = body.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        // Skip whitespace and commas between pairs.
        while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b',') {
            i += 1;
        }
        if i >= bytes.len() {
            break;
        }
        if bytes[i] != b'[' {
            return Err(format!(
                "expected '[' starting pragma pair at byte {i} of array body"
            ));
        }
        i += 1;
        let (name, consumed) = read_string(&body[i..])?;
        i += consumed;
        // Skip whitespace + comma.
        while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b',') {
            i += 1;
        }
        let (value, consumed) = read_string(&body[i..])?;
        i += consumed;
        // Skip whitespace + closing ].
        while i < bytes.len() && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= bytes.len() || bytes[i] != b']' {
            return Err(format!("expected ']' closing pragma pair at byte {i}"));
        }
        i += 1;
        out.push((name, value));
    }
    if out.is_empty() {
        return Err("pragmas array is empty".to_string());
    }
    Ok(out)
}

/// Read a JSON string literal starting at `s[0] == '"'`. Returns the
/// decoded value (with `\\`, `\"`, `\n`, `\r`, `\t` escapes processed)
/// and the number of bytes consumed including both quote characters.
fn read_string(s: &str) -> Result<(String, usize), String> {
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() && bytes[i].is_ascii_whitespace() {
        i += 1;
    }
    if i >= bytes.len() || bytes[i] != b'"' {
        return Err(format!("expected '\"' at byte {i}"));
    }
    i += 1;
    let mut out = String::new();
    while i < bytes.len() {
        let b = bytes[i];
        if b == b'"' {
            return Ok((out, i + 1));
        }
        if b == b'\\' {
            i += 1;
            if i >= bytes.len() {
                return Err("dangling escape".to_string());
            }
            match bytes[i] {
                b'"' => out.push('"'),
                b'\\' => out.push('\\'),
                b'/' => out.push('/'),
                b'n' => out.push('\n'),
                b'r' => out.push('\r'),
                b't' => out.push('\t'),
                other => return Err(format!("unsupported escape \\{}", other as char)),
            }
            i += 1;
            continue;
        }
        out.push(b as char);
        i += 1;
    }
    Err("unterminated string".to_string())
}
