/**
 * Auto-stub generator for task verifier scripts (T9218 / ADR-070).
 *
 * Shared between:
 *   - `tasks.add` strict-mode enforcement (creates stub at task creation time)
 *   - `cleo verify backfill` tool (retroactively generates stubs for existing tasks)
 *
 * The generated `.mjs` script is intentionally skeletal — every acceptance
 * criterion starts as a `process.exit(1)` stub with the AC bullet text as
 * the failure message. Replacing those stubs with real checks is the human's
 * (or implementing agent's) job.
 *
 * @task T9218
 * @adr ADR-070
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { AcceptanceItem, Task } from '@cleocode/contracts';

/**
 * Generate the `.mjs` source for a verifier script from a task's acceptance criteria.
 *
 * Each AC bullet becomes one `process.exit(1)` block with the bullet text as
 * the failure message. The generated script is a valid Node.js ESM module.
 *
 * @param task - Task record to generate a verifier for.
 * @returns ESM `.mjs` source string.
 *
 * @example
 * ```ts
 * const source = generateVerifierStub({ id: 'T9218', title: 'My task',
 *   acceptance: ['feature works', 'tests pass'] } as Task);
 * // source contains two process.exit(1) blocks, one per AC bullet
 * ```
 */
export function generateVerifierStub(task: Task): string {
  const id = task.id;
  const title = task.title ?? '(untitled)';
  // AcceptanceItem is string | AcceptanceGate; extract the human-readable text from each.
  const acceptance: string[] = Array.isArray(task.acceptance)
    ? (task.acceptance as AcceptanceItem[]).map((item) => {
        if (typeof item === 'string') return item;
        // AcceptanceGate: use 'description' or 'kind' as the display text
        const gate = item as { description?: string; kind?: string };
        return gate.description ?? gate.kind ?? JSON.stringify(item);
      })
    : [];

  // Build one check block per AC bullet
  const checks = acceptance.length > 0 ? acceptance : ['(no acceptance criteria defined)'];

  const checkBlocks = checks
    .map((ac, i) => {
      const safeMsg = ac.replace(/`/g, "'").replace(/\\/g, '\\\\');
      return `// ---------------------------------------------------------------------------
// Check ${i + 1}: ${safeMsg}
// ---------------------------------------------------------------------------
// TODO: Replace this stub with a real check.
// When the check PASSES, call pass(...) and do NOT call process.exit(1).
// When the check FAILS, call fail(...) which records the failure; the final
// block at the bottom will exit 1.
fail(\`STUB — not yet implemented: ${safeMsg}\`);
// EXAMPLE (file existence):
//   if (existsSync(join(REPO_ROOT, 'path/to/file.ts'))) {
//     pass('${safeMsg}');
//   } else {
//     fail('${safeMsg}');
//   }`;
    })
    .join('\n\n');

  return `#!/usr/bin/env node
/**
 * Verifier for ${id}: ${title}
 *
 * Source task: ${id}
 * Auto-generated by \`cleo verify backfill\` (T9218 / ADR-070).
 *
 * AC:
${checks.map((ac) => ` *   - ${ac}`).join('\n')}
 *
 * INSTRUCTIONS:
 *   Replace each \`fail('STUB — not yet implemented: ...')\` block with a
 *   real programmatic check. When all checks pass, this script must exit 0.
 *   Run: node scripts/verify-${id.toLowerCase()}.mjs
 */

import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

const failures = [];

/**
 * Record a passing check.
 * @param {string} msg
 */
function pass(msg) {
  console.log('PASS:', msg);
}

/**
 * Record a failing check (does NOT exit immediately — all failures are collected).
 * @param {string} msg
 */
function fail(msg) {
  console.error('FAIL:', msg);
  failures.push(msg);
}

${checkBlocks}

// ---------------------------------------------------------------------------
// Final
// ---------------------------------------------------------------------------
if (failures.length === 0) {
  console.log('\\nVERIFIER PASS: ${id} — ${title.replace(/'/g, "\\'")}');
  process.exit(0);
} else {
  console.error(\`\\nVERIFIER FAIL: \${failures.length} check(s) failed\`);
  process.exit(1);
}
`;
}

/**
 * Write a generated verifier stub to `scripts/verify-<lowercase-taskId>.mjs`.
 *
 * Idempotent safety: if the file already exists and `force` is false, the
 * function throws rather than silently overwriting.
 *
 * @param taskId - Task ID (e.g. "T9218") — determines output filename.
 * @param source - ESM source string produced by {@link generateVerifierStub}.
 * @param projectRoot - Absolute path to the project root.
 * @param force - If true, overwrite an existing verifier without error.
 * @returns Absolute path to the written file.
 * @throws Error when the verifier already exists and `force` is false.
 *
 * @example
 * ```ts
 * const src = generateVerifierStub(task);
 * const path = writeVerifierStub('T9218', src, '/mnt/projects/cleocode');
 * // path === '/mnt/projects/cleocode/scripts/verify-t9218.mjs'
 * ```
 */
export function writeVerifierStub(
  taskId: string,
  source: string,
  projectRoot: string,
  force = false,
): string {
  const filename = `verify-${taskId.toLowerCase()}.mjs`;
  const scriptsDir = join(resolve(projectRoot), 'scripts');
  const outPath = join(scriptsDir, filename);

  if (existsSync(outPath) && !force) {
    throw new Error(`verifier already exists: ${outPath}; use --force to overwrite`);
  }

  // Ensure scripts/ directory exists (project may not have it yet)
  if (!existsSync(scriptsDir)) {
    mkdirSync(scriptsDir, { recursive: true });
  }

  writeFileSync(outPath, source, 'utf8');
  return outPath;
}
