-- T12343 O-1 (journal spec §2.8 "Persist before push") — the segment outbox.
--
-- _sync_segment: one row per segment this replica built for a stream, at
-- its replicaSeq (gap-free per stream and replica, 0 first). `sealed` holds
-- the EXACT encrypted bytes and `segment_hash` their sha256: a push always
-- sends these bytes, never re-sealed, so the server's (replica, hash)
-- idempotency makes every resend safe. `state` is 'sealed' until the server
-- acknowledged it ('pushed', with its stream `server_seq`). Written in the
-- same local transaction that marks its transactions segmented.
--
-- _sync_segment_txn: the transactions a segment carries, in order. A
-- segmented transaction stays unsequenced until its echo (§3.5).
--
-- Local-only.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_segment (
  stream       TEXT NOT NULL,
  replica_id   TEXT NOT NULL,
  replica_seq  INTEGER NOT NULL,
  meta_json    TEXT NOT NULL,
  sealed       BLOB NOT NULL,
  segment_hash TEXT NOT NULL,
  state        TEXT NOT NULL DEFAULT 'sealed',
  server_seq   INTEGER,
  created_at   TEXT NOT NULL,
  pushed_at    TEXT,
  PRIMARY KEY (stream, replica_id, replica_seq)
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS _sync_segment_txn (
  stream      TEXT NOT NULL,
  replica_id  TEXT NOT NULL,
  replica_seq INTEGER NOT NULL,
  idx         INTEGER NOT NULL,
  txn         TEXT NOT NULL,
  PRIMARY KEY (stream, txn)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_segment_txn_seg ON _sync_segment_txn (stream, replica_id, replica_seq);
