/**
 * MCP tool definitions and handlers for CLEO sentient operations.
 *
 * Exposes 3 CLEO sentient operations as MCP tools:
 *   1. `cleo_sentient_status`         — query sentient subsystem state
 *   2. `cleo_sentient_propose_list`   — list Tier-2 proposals
 *   3. `cleo_sentient_propose_enable` — enable Tier-2 proposal generation
 *                                       (subject to M7 gate on the CLEO side)
 *
 * External tools (Claude Code, LLM clients) call these tools; the adapter
 * delegates to `@cleocode/core` SDK calls.  No CLI subprocess is used.
 *
 * @task T1485 — MCP adapter SDK migration (T948 prerequisite)
 */

import { getSentientDaemonStatus } from '@cleocode/core/sentient/daemon.js';
import { sentientProposeEnable, sentientProposeList } from '@cleocode/core/sentient/ops.js';
import type { McpTool, McpToolResult } from './types.js';

// ---------------------------------------------------------------------------
// Tool definitions (JSON Schema)
// ---------------------------------------------------------------------------

/** Tool: query sentient subsystem status. */
export const TOOL_SENTIENT_STATUS: McpTool = {
  name: 'cleo_sentient_status',
  description:
    'Query the CLEO sentient subsystem status. Returns daemon state, kill-switch status, Tier-2 enabled flag, and proposal statistics.',
  inputSchema: {
    type: 'object',
    properties: {
      projectRoot: {
        type: 'string',
        description:
          'Absolute path to the CLEO project root. Defaults to the adapter working directory.',
      },
    },
  },
};

/** Tool: list Tier-2 proposals. */
export const TOOL_PROPOSE_LIST: McpTool = {
  name: 'cleo_sentient_propose_list',
  description:
    'List Tier-2 (autonomous) proposals generated by the CLEO sentient subsystem. Returns proposals with status=proposed, sorted by weight descending.',
  inputSchema: {
    type: 'object',
    properties: {
      projectRoot: {
        type: 'string',
        description: 'Absolute path to the CLEO project root.',
      },
      limit: {
        type: 'string',
        description: 'Maximum number of proposals to return (default: 20).',
      },
    },
  },
};

/** Tool: enable Tier-2 proposal generation. */
export const TOOL_PROPOSE_ENABLE: McpTool = {
  name: 'cleo_sentient_propose_enable',
  description:
    'Enable Tier-2 autonomous proposal generation. Subject to M7 gate on the CLEO side: ' +
    '`cleo memory doctor --assert-clean` must pass before this succeeds. ' +
    'Returns success or E_M7_GATE_FAILED with guidance on cleaning the brain corpus.',
  inputSchema: {
    type: 'object',
    properties: {
      projectRoot: {
        type: 'string',
        description: 'Absolute path to the CLEO project root.',
      },
    },
  },
};

/** All exported MCP tools. */
export const ALL_TOOLS: McpTool[] = [TOOL_SENTIENT_STATUS, TOOL_PROPOSE_LIST, TOOL_PROPOSE_ENABLE];

// ---------------------------------------------------------------------------
// Tool handlers
// ---------------------------------------------------------------------------

/**
 * Dispatch an MCP tool call to the appropriate Core SDK function.
 *
 * @param toolName  - The `name` field from the MCP tool call.
 * @param toolInput - The parsed input parameters.
 * @param opts      - Optional execution options (cwd fallback when projectRoot not in input).
 * @returns MCP tool result with text content.
 */
export async function handleToolCall(
  toolName: string,
  toolInput: Record<string, string>,
  opts?: { cwd?: string },
): Promise<McpToolResult> {
  const projectRoot = toolInput['projectRoot'] ?? opts?.cwd ?? process.cwd();

  switch (toolName) {
    case 'cleo_sentient_status': {
      try {
        const status = await getSentientDaemonStatus(projectRoot);
        return toMcpResult(JSON.stringify({ success: true, data: status }), false);
      } catch (err) {
        return toMcpResult(
          JSON.stringify({ success: false, error: { message: String(err) } }),
          true,
        );
      }
    }

    case 'cleo_sentient_propose_list': {
      try {
        const rawLimit = toolInput['limit'];
        const limit = rawLimit ? Number.parseInt(rawLimit, 10) : 20;
        const result = await sentientProposeList(projectRoot, { limit });
        return toMcpResult(JSON.stringify({ success: true, data: result }), false);
      } catch (err) {
        return toMcpResult(
          JSON.stringify({ success: false, error: { message: String(err) } }),
          true,
        );
      }
    }

    case 'cleo_sentient_propose_enable': {
      try {
        const result = await sentientProposeEnable(projectRoot, {});
        return toMcpResult(JSON.stringify({ success: true, data: result }), false);
      } catch (err) {
        const code = (err as NodeJS.ErrnoException).code;
        const isM7Failure = code === 'E_M7_GATE_FAILED';
        return toMcpResult(
          JSON.stringify({
            success: false,
            error: {
              code: code ?? 'E_SENTIENT_PROPOSE_ENABLE',
              message: err instanceof Error ? err.message : String(err),
            },
          }),
          isM7Failure,
        );
      }
    }

    default:
      return {
        content: [{ type: 'text', text: `Unknown tool: ${toolName}` }],
        isError: true,
      };
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Wrap CLI output into an MCP content result.
 *
 * @param text    - Text to surface to the MCP client.
 * @param isError - Whether the result should be flagged as an error.
 */
function toMcpResult(text: string, isError: boolean): McpToolResult {
  return {
    content: [{ type: 'text', text: text || '(no output)' }],
    isError: isError || undefined,
  };
}
