/**
 * Unified CQRS Dispatch Layer -- Operation Registry
 *
 * Single source of truth for all 198 operations mapped to 10 canonical domains.
 * Canonical domains only -- no legacy alias support.
 *
 * @epic T4820
 * @task T4814
 */

import { Gateway, Tier, CanonicalDomain, type ParamDef } from './types.js';

/** Definition of a single dispatchable operation. */
export interface OperationDef {
  /** The CQRS gateway ('query' or 'mutate'). */
  gateway: Gateway;
  /** The canonical domain this operation belongs to. */
  domain: CanonicalDomain;
  /** The specific operation name (e.g. 'show', 'skill.list'). */
  operation: string;
  /** Brief description of what the operation does. */
  description: string;
  /** Agent progressive-disclosure tier (0=basic, 1=memory/check, 2=full). */
  tier: Tier;
  /** Whether the operation is safe to retry. */
  idempotent: boolean;
  /** Whether this operation requires an active session. */
  sessionRequired: boolean;
  /** List of parameter keys that MUST be present in the request. */
  requiredParams: string[];
  /**
   * Fully-described parameter list. Replaces `requiredParams` when populated.
   * Empty array = "no declared params" (not "no params accepted").
   * Optional during T4897 migration — defaults to [] when absent.
   * @see T4897 for progressive migration
   */
  params?: ParamDef[];
  /**
   * Backward-compatible operation aliases (e.g., 'config.get' for 'config.show').
   * These are included in derived gateway matrices so validation passes for both names.
   * Runtime translation happens in resolveOperationAlias() in the MCP adapter.
   */
  aliases?: string[];
}

/**
 * Resolution output for a dispatch request.
 */
export interface Resolution {
  /** The canonical domain. */
  domain: CanonicalDomain;
  /** The operation name. */
  operation: string;
  /** The definition of the matched operation. */
  def: OperationDef;
}

/**
 * The single source of truth for all operations in CLEO.
 */
export const OPERATIONS: OperationDef[] = [
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'show',
    description: 'tasks.show (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'list',
    description: 'tasks.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'find',
    description: 'tasks.find (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'exists',
    description: 'tasks.exists (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'tree',
    description: 'tasks.tree (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'blockers',
    description: 'tasks.blockers (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'depends',
    description: 'tasks.depends (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'analyze',
    description: 'tasks.analyze (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'next',
    description: 'tasks.next (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'plan',
    description: 'Composite planning view with in-progress epics, ready tasks, blocked tasks, and open bugs (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'relates',
    description: 'tasks.relates (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'complexity.estimate',
    description: 'tasks.complexity.estimate (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'current',
    description: 'tasks.current (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // Label operations (dispatch migration)
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'label.list',
    description: 'List all labels with task counts',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'label.show',
    description: 'Show tasks with a specific label',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['label'],
    params: [
      { name: 'label', type: 'string', required: true, description: 'Label name to filter by' },
    ],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'status',
    description: 'session.status (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'list',
    description: 'session.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'show',
    description: 'session.show (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'history',
    description: 'session.history (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'decision.log',
    description: 'session.decision.log (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'context.drift',
    description: 'session.context.drift (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'handoff.show',
    description: 'session.handoff.show - Show handoff data from the most recent ended session (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'briefing.show',
    description: 'session.briefing.show - Composite session-start context (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // T4959: Rich debrief + chain operations
  {
    gateway: 'query',
    domain: 'session',
    operation: 'debrief.show',
    description: 'session.debrief.show - Read a session\'s rich debrief data (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['sessionId'],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'chain.show',
    description: 'session.chain.show - Show session chain linked via previous/next (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['sessionId'],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'find',
    description: 'session.find (query) — lightweight session discovery',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'status',
    description: 'orchestrate.status (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'next',
    description: 'orchestrate.next (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'ready',
    description: 'orchestrate.ready (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'analyze',
    description: 'orchestrate.analyze (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'context',
    description: 'orchestrate.context (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'waves',
    description: 'orchestrate.waves (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'bootstrap',
    description: 'orchestrate.bootstrap (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'unblock.opportunities',
    description: 'orchestrate.unblock.opportunities (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'critical.path',
    description: 'orchestrate.critical.path (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'show',
    description: 'memory.show (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'list',
    description: 'memory.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'find',
    description: 'memory.find (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'pending',
    description: 'memory.pending (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'stats',
    description: 'memory.stats (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'manifest.read',
    description: 'memory.manifest.read (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'contradictions',
    description: 'memory.contradictions (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'superseded',
    description: 'memory.superseded (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // BRAIN memory query operations (T4770)
  {
    gateway: 'query' as const,
    domain: 'memory',
    operation: 'pattern.search',
    description: 'memory.pattern.search (query) — search BRAIN pattern memory by type, impact, or keyword',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'memory',
    operation: 'pattern.stats',
    description: 'memory.pattern.stats (query) — pattern memory statistics (counts by type and impact)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'memory',
    operation: 'learning.search',
    description: 'memory.learning.search (query) — search BRAIN learning memory by confidence, actionability, or keyword',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'memory',
    operation: 'learning.stats',
    description: 'memory.learning.stats (query) — learning memory statistics (counts by confidence band)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // BRAIN 3-layer retrieval query operations (T5149)
  {
    gateway: 'query' as const,
    domain: 'memory',
    operation: 'brain.search',
    description: 'memory.brain.search (query) — 3-layer retrieval step 1: search index',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'memory',
    operation: 'brain.timeline',
    description: 'memory.brain.timeline (query) — 3-layer retrieval step 2: context around anchor',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'memory',
    operation: 'brain.fetch',
    description: 'memory.brain.fetch (query) — 3-layer retrieval step 3: full details for filtered IDs',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.validate',
    description: 'pipeline.stage.validate (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.status',
    description: 'pipeline.stage.status (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.history',
    description: 'pipeline.stage.history (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.gates',
    description: 'pipeline.stage.gates (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.prerequisites',
    description: 'pipeline.stage.prerequisites (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'schema',
    description: 'check.schema (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'protocol',
    description: 'check.protocol (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'task',
    description: 'check.task (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'manifest',
    description: 'check.manifest (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'output',
    description: 'check.output (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'compliance.summary',
    description: 'check.compliance.summary (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'compliance.violations',
    description: 'check.compliance.violations (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'test.status',
    description: 'check.test.status (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'test.coverage',
    description: 'check.test.coverage (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'coherence.check',
    description: 'check.coherence.check (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'version',
    description: 'admin.version (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'health',
    description: 'admin.health (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'config.show',
    description: 'admin.config.show (query) — show config value',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'config.get',
    description: 'admin.config.get (query) — alias for config.show (backward compat)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'stats',
    description: 'admin.stats (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'context',
    description: 'admin.context (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'runtime',
    description: 'admin.runtime (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'job.status',
    description: 'admin.job.status (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'job.list',
    description: 'admin.job.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'dash',
    description: 'admin.dash (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'log',
    description: 'admin.log (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'sequence',
    description: 'admin.sequence (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'help',
    description: 'Get operations list and guidance filtered to specified disclosure tier',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      {
        name: 'tier',
        type: 'number',
        required: false,
        description: 'Progressive disclosure tier: 0=basic (default), 1=+memory/check, 2=all operations',
        cli: { flag: 'tier', short: '-t' },
      },
    ],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'issue.diagnostics',
    description: 'tools.issue.diagnostics (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'issue.templates',
    description: 'List available issue templates',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'issue.validate.labels',
    description: 'Validate issue labels against configured label set',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['labels'],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.list',
    description: 'tools.skill.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.show',
    description: 'tools.skill.show (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.find',
    description: 'tools.skill.find (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.dispatch',
    description: 'tools.skill.dispatch (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.verify',
    description: 'tools.skill.verify (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.dependencies',
    description: 'tools.skill.dependencies (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.catalog.protocols',
    description: 'List CAAMP protocol definitions',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.catalog.profiles',
    description: 'List CAAMP dispatch profiles',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.catalog.resources',
    description: 'List CAAMP shared resources',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.catalog.info',
    description: 'Get CAAMP catalog metadata',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.list',
    description: 'tools.provider.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.detect',
    description: 'tools.provider.detect (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.inject.status',
    description: 'tools.provider.inject.status (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'add',
    description: 'tasks.add (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'update',
    description: 'tasks.update (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'complete',
    description: 'tasks.complete (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'delete',
    description: 'tasks.delete (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'archive',
    description: 'tasks.archive (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'restore',
    description: 'tasks.restore (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reparent',
    description: 'tasks.reparent (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'promote',
    description: 'tasks.promote (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reorder',
    description: 'tasks.reorder (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reopen',
    description: 'tasks.reopen (mutate) — alias for tasks.restore',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'relates.add',
    description: 'tasks.relates.add (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'start',
    description: 'tasks.start (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'stop',
    description: 'tasks.stop (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'start',
    description: 'session.start (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'end',
    description: 'session.end (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'resume',
    description: 'session.resume (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'suspend',
    description: 'session.suspend (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'gc',
    description: 'session.gc (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'record.decision',
    description: 'session.record.decision (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'record.assumption',
    description: 'session.record.assumption (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'start',
    description: 'orchestrate.start (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'spawn',
    description: 'orchestrate.spawn (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'validate',
    description: 'orchestrate.validate (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'parallel.start',
    description: 'orchestrate.parallel.start (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'parallel.end',
    description: 'orchestrate.parallel.end (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'inject',
    description: 'memory.inject (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'link',
    description: 'memory.link (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'manifest.append',
    description: 'memory.manifest.append (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'manifest.archive',
    description: 'memory.manifest.archive (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // BRAIN memory mutate operations (T4770)
  {
    gateway: 'mutate' as const,
    domain: 'memory',
    operation: 'pattern.store',
    description: 'memory.pattern.store (mutate) — store a reusable workflow or anti-pattern in BRAIN pattern memory',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['pattern', 'context'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'memory',
    operation: 'learning.store',
    description: 'memory.learning.store (mutate) — store an insight or lesson learned in BRAIN learning memory',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['insight', 'source'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'memory',
    operation: 'brain.observe',
    description: 'memory.brain.observe (mutate) — save observation to brain.db',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['text'],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.record',
    description: 'pipeline.stage.record (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.skip',
    description: 'pipeline.stage.skip (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.reset',
    description: 'pipeline.stage.reset (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.gate.pass',
    description: 'pipeline.stage.gate.pass (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.gate.fail',
    description: 'pipeline.stage.gate.fail (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'check',
    operation: 'compliance.record',
    description: 'check.compliance.record (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'check',
    operation: 'test.run',
    description: 'check.test.run (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.prepare',
    description: 'pipeline.release.prepare (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.changelog',
    description: 'pipeline.release.changelog (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.commit',
    description: 'pipeline.release.commit (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.tag',
    description: 'pipeline.release.tag (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.push',
    description: 'pipeline.release.push (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.gates.run',
    description: 'pipeline.release.gates.run (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.rollback',
    description: 'pipeline.release.rollback (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'init',
    description: 'admin.init (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'config.set',
    description: 'admin.config.set (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'backup',
    description: 'admin.backup (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'restore',
    description: 'admin.restore (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'migrate',
    description: 'admin.migrate (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'sync',
    description: 'admin.sync (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'cleanup',
    description: 'admin.cleanup (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'job.cancel',
    description: 'admin.job.cancel (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'safestop',
    description: 'admin.safestop (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'inject.generate',
    description: 'admin.inject.generate (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'sequence',
    description: 'admin.sequence (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'issue.add.bug',
    description: 'tools.issue.add.bug (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'issue.add.feature',
    description: 'tools.issue.add.feature (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'issue.add.help',
    description: 'tools.issue.add.help (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // Backward compat aliases for issue.create.* -> issue.add.*
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'issue.create.bug',
    description: 'tools.issue.create.bug (mutate) — alias for issue.add.bug (backward compat)',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'issue.create.feature',
    description: 'tools.issue.create.feature (mutate) — alias for issue.add.feature (backward compat)',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'issue.create.help',
    description: 'tools.issue.create.help (mutate) — alias for issue.add.help (backward compat)',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'issue.generate.config',
    description: 'Generate issue template configuration file',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.install',
    description: 'tools.skill.install (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.uninstall',
    description: 'tools.skill.uninstall (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.enable',
    description: 'tools.skill.enable (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.disable',
    description: 'tools.skill.disable (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.configure',
    description: 'tools.skill.configure (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.refresh',
    description: 'tools.skill.refresh (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'provider.inject',
    description: 'tools.provider.inject (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // T4916: Global install refresh + session behavioral grading
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'install.global',
    description: 'Refresh global CLEO setup: provider files, MCP configs, ~/.agents/AGENTS.md',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'grade',
    description: 'Grade agent behavioral session using 5-dimension rubric (requires --grade session)',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['sessionId'],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'grade.list',
    description: 'List past session grade results from .cleo/metrics/GRADES.jsonl',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },

  // Archive stats (dispatch migration)
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'archive.stats',
    description: 'Archive statistics and analytics',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'report', type: 'string', required: false, description: 'Report type (summary, by-phase, by-label, by-priority, cycle-times, trends)' },
      { name: 'since', type: 'string', required: false, description: 'Filter by archived since date (YYYY-MM-DD)' },
      { name: 'until', type: 'string', required: false, description: 'Filter by archived until date (YYYY-MM-DD)' },
    ],
  },

  // ADR operations (ADR-017 §2, Tier 2 — admin domain)
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'adr.list',
    description: 'admin.adr.list (query) — list ADRs from .cleo/adrs/ with optional status filter',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'adr.show',
    description: 'admin.adr.show (query) — retrieve single ADR by ID with frontmatter',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['adrId'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'adr.sync',
    description: 'admin.adr.sync (mutate) — sync .cleo/adrs/ markdown files into architecture_decisions DB table',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'adr.validate',
    description: 'admin.adr.validate (mutate) — validate ADR frontmatter against adr-frontmatter.schema.json',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'adr.find',
    description: 'admin.adr.find (query) — fuzzy search ADRs by title, summary, keywords, and topics',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'doctor',
    description: 'admin.doctor (query) — comprehensive health check and diagnostics report',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'fix',
    description: 'admin.fix (mutate) — auto-fix failed doctor checks',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },

  // ---------------------------------------------------------------------------
  // sharing — multi-contributor operations
  // ---------------------------------------------------------------------------
  {
    gateway: 'query' as const,
    domain: 'sharing',
    operation: 'status',
    description: 'sharing.status (query) — sharing status',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'sharing',
    operation: 'remotes',
    description: 'sharing.remotes (query) — list configured remotes',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'sharing',
    operation: 'sync.status',
    description: 'sharing.sync.status (query) — sync status',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sharing',
    operation: 'snapshot.export',
    description: 'sharing.snapshot.export (mutate) — export project snapshot',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sharing',
    operation: 'snapshot.import',
    description: 'sharing.snapshot.import (mutate) — import project snapshot',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sharing',
    operation: 'sync.gitignore',
    description: 'sharing.sync.gitignore (mutate) — sync gitignore',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sharing',
    operation: 'remote.add',
    description: 'sharing.remote.add (mutate) — add remote',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sharing',
    operation: 'remote.remove',
    description: 'sharing.remote.remove (mutate) — remove remote',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sharing',
    operation: 'push',
    description: 'sharing.push (mutate) — push to remote',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sharing',
    operation: 'pull',
    description: 'sharing.pull (mutate) — pull from remote',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },

  // ---------------------------------------------------------------------------
  // nexus — Cross-project coordination (BRAIN Network)
  // ---------------------------------------------------------------------------

  // Query operations
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'status',
    description: 'nexus.status (query) — overall NEXUS health status',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'list',
    description: 'nexus.list (query) — list all registered NEXUS projects',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'show',
    description: 'nexus.show (query) — show a specific project by name or hash',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['name'],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'query',
    description: 'nexus.query (query) — resolve a cross-project project:taskId query',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'deps',
    description: 'nexus.deps (query) — cross-project dependency analysis',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'graph',
    description: 'nexus.graph (query) — global dependency graph across all projects',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },

  // Mutate operations
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'init',
    description: 'nexus.init (mutate) — initialize NEXUS (creates registry and directories)',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'register',
    description: 'nexus.register (mutate) — register a project in NEXUS',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['path'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'unregister',
    description: 'nexus.unregister (mutate) — remove a project from NEXUS',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['name'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'sync',
    description: 'nexus.sync (mutate) — sync project metadata (task count, labels)',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['name'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'sync.all',
    description: 'nexus.sync.all (mutate) — sync all registered projects',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'permission.set',
    description: 'nexus.permission.set (mutate) — update project permissions',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['name', 'level'],
  },
];

// ---------------------------------------------------------------------------
// Legacy Domain Aliases
// ---------------------------------------------------------------------------

/**
 * Legacy domain alias mapping.
 *
 * Maps legacy MCP domain names to their canonical domain + operation prefix.
 * Used to generate backward-compatible gateway operation matrices and to
 * resolve domain aliases at runtime in the MCP adapter.
 *
 * When a legacy domain has a prefix, the canonical operation name is expected
 * to start with that prefix (e.g., `skill.list` in canonical `tools` domain
 * maps to `list` in legacy `skills` domain).
 */
export const LEGACY_DOMAIN_ALIASES: Record<string, { canonical: CanonicalDomain; prefix: string }> = {
  research:  { canonical: 'memory',   prefix: '' },
  validate:  { canonical: 'check',    prefix: '' },
  lifecycle: { canonical: 'pipeline', prefix: 'stage.' },
  release:   { canonical: 'pipeline', prefix: 'release.' },
  system:    { canonical: 'admin',    prefix: '' },
  skills:    { canonical: 'tools',    prefix: 'skill.' },
  providers: { canonical: 'tools',    prefix: 'provider.' },
  issues:    { canonical: 'tools',    prefix: 'issue.' },
};

// ---------------------------------------------------------------------------
// Gateway Matrix Derivation
// ---------------------------------------------------------------------------

/**
 * Derive a gateway operation matrix from the registry.
 *
 * Returns `Record<string, string[]>` containing:
 * - All 10 canonical domains with their operations (including aliases)
 * - All legacy alias domains with reverse-mapped operation names
 *
 * This is the SINGLE derivation point — gateways use this instead of
 * maintaining independent operation lists.
 */
export function deriveGatewayMatrix(gateway: Gateway): Record<string, string[]> {
  const matrix: Record<string, string[]> = {};

  // Step 1: Populate canonical domains from the OPERATIONS array
  for (const op of OPERATIONS) {
    if (op.gateway !== gateway) continue;
    if (!matrix[op.domain]) matrix[op.domain] = [];
    matrix[op.domain].push(op.operation);
    // Include aliases in the canonical domain entry
    if (op.aliases) {
      for (const alias of op.aliases) {
        matrix[op.domain].push(alias);
      }
    }
  }

  // Step 2: Populate legacy alias domains by reverse-mapping
  for (const [alias, { canonical, prefix }] of Object.entries(LEGACY_DOMAIN_ALIASES)) {
    const canonicalOps = matrix[canonical];
    if (!canonicalOps) continue;

    const legacyOps: string[] = [];
    for (const op of canonicalOps) {
      if (prefix) {
        // Only include operations that start with the prefix
        if (op.startsWith(prefix)) {
          legacyOps.push(op.slice(prefix.length));
        }
      } else {
        // No prefix — all operations map directly
        legacyOps.push(op);
      }
    }
    if (legacyOps.length > 0) {
      matrix[alias] = legacyOps;
    }
  }

  return matrix;
}

/**
 * Get all accepted domain names for a gateway (canonical + legacy aliases).
 */
export function getGatewayDomains(gateway: Gateway): string[] {
  return Object.keys(deriveGatewayMatrix(gateway));
}

// ---------------------------------------------------------------------------
// Lookup & Validation
// ---------------------------------------------------------------------------

/**
 * Resolves a domain + operation to its registered definition.
 */
export function resolve(gateway: Gateway, domain: string, operation: string): Resolution | undefined {
  const def = OPERATIONS.find(
    o => o.gateway === gateway && o.domain === domain && o.operation === operation,
  );

  if (!def) return undefined;

  return { domain: def.domain, operation: def.operation, def };
}

/**
 * Validates that all required parameters are present in the request.
 * Returns an array of missing parameter keys.
 */
export function validateRequiredParams(def: OperationDef, params?: Record<string, unknown>): string[] {
  if (!def.requiredParams || def.requiredParams.length === 0) return [];
  const provided = params || {};
  return def.requiredParams.filter(key => provided[key] === undefined || provided[key] === null || provided[key] === '');
}

/** Get all operations for a specific canonical domain. */
export function getByDomain(domain: CanonicalDomain): OperationDef[] {
  return OPERATIONS.filter(o => o.domain === domain);
}

/** Get all operations for a specific gateway. */
export function getByGateway(gateway: Gateway): OperationDef[] {
  return OPERATIONS.filter(o => o.gateway === gateway);
}

/** Get all operations available at or below a specific tier. */
export function getByTier(tier: Tier): OperationDef[] {
  return OPERATIONS.filter(o => o.tier <= tier);
}

/** Get a list of canonical domains that actually have operations registered. */
export function getActiveDomains(): CanonicalDomain[] {
  const active = new Set(OPERATIONS.map(o => o.domain));
  return Array.from(active);
}

/**
 * Returns summary counts of operations for module validation.
 */
export function getCounts(): { query: number; mutate: number; total: number } {
  return {
    query: OPERATIONS.filter(o => o.gateway === 'query').length,
    mutate: OPERATIONS.filter(o => o.gateway === 'mutate').length,
    total: OPERATIONS.length,
  };
}

// Module load validation (dynamic, no hardcoded operation totals)
const counts = getCounts();
if (counts.total !== OPERATIONS.length) {
  console.warn(`[Registry] Operation count mismatch: total=${counts.total}, registry=${OPERATIONS.length}`);
}
