/**
 * Unified CQRS Dispatch Layer -- Operation Registry
 *
 * Single source of truth for all 140 operations mapped to 9 canonical domains.
 * Provides aliases (legacy domain support), declarative required-param checks,
 * idempotency flags, and filtering.
 *
 * @epic T4820
 * @task T4814
 */

import { Gateway, Tier, CanonicalDomain } from './types.js';

/**
 * Mappings from legacy CLI domain names to new canonical V2 names.
 */
export const LEGACY_TO_CANONICAL: Record<string, CanonicalDomain> = {
  research: 'pipeline',
  validate: 'check',
  lifecycle: 'pipeline',
  release: 'pipeline',
  skills: 'tools',
  providers: 'tools',
  issues: 'tasks',
  system: 'admin',
};

/** Definition of a single dispatchable operation. */
export interface OperationDef {
  /** The CQRS gateway ('query' or 'mutate'). */
  gateway: Gateway;
  /** The true canonical domain this operation belongs to. */
  domain: CanonicalDomain;
  /** Optional legacy domain alias for backwards compatibility. */
  legacyDomain?: string;
  /** The specific operation name (e.g. 'show', 'add'). */
  operation: string;
  /** Brief description of what the operation does. */
  description: string;
  /** Agent progressive-disclosure tier (0=basic, 1=memory/check, 2=full). */
  tier: Tier;
  /** Whether the operation is safe to retry. */
  idempotent: boolean;
  /** Whether this operation requires an active session. */
  sessionRequired: boolean;
  /** List of parameter keys that MUST be present in the request. */
  requiredParams: string[];
}

/**
 * Resolution output for a dispatch request.
 */
export interface AliasResolution {
  /** The true canonical domain. */
  domain: CanonicalDomain;
  /** The true operation name. */
  operation: string;
  /** The definition of the matched operation. */
  def: OperationDef;
  /** Details about whether this request was made via a legacy alias. */
  alias: {
    aliased: boolean;
    deprecation?: string;
  };
}

/**
 * The single source of truth for all operations in CLEO.
 */
export const OPERATIONS: OperationDef[] = [
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'show',
    description: 'Legacy query operation tasks.show',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'list',
    description: 'Legacy query operation tasks.list',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'find',
    description: 'Legacy query operation tasks.find',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'exists',
    description: 'Legacy query operation tasks.exists',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'tree',
    description: 'Legacy query operation tasks.tree',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'blockers',
    description: 'Legacy query operation tasks.blockers',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'depends',
    description: 'Legacy query operation tasks.depends',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'analyze',
    description: 'Legacy query operation tasks.analyze',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'next',
    description: 'Legacy query operation tasks.next',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'relates',
    description: 'Legacy query operation tasks.relates',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'complexity.estimate',
    description: 'Legacy query operation tasks.complexity.estimate',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'current',
    description: 'Legacy query operation tasks.current',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'status',
    description: 'Legacy query operation session.status',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'list',
    description: 'Legacy query operation session.list',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'show',
    description: 'Legacy query operation session.show',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'history',
    description: 'Legacy query operation session.history',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'decision.log',
    description: 'Legacy query operation session.decision.log',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'context.drift',
    description: 'Legacy query operation session.context.drift',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'status',
    description: 'Legacy query operation orchestrate.status',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'next',
    description: 'Legacy query operation orchestrate.next',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'ready',
    description: 'Legacy query operation orchestrate.ready',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'analyze',
    description: 'Legacy query operation orchestrate.analyze',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'context',
    description: 'Legacy query operation orchestrate.context',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'waves',
    description: 'Legacy query operation orchestrate.waves',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'skill.list',
    description: 'Legacy query operation orchestrate.skill.list',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'bootstrap',
    description: 'Legacy query operation orchestrate.bootstrap',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'unblock.opportunities',
    description: 'Legacy query operation orchestrate.unblock.opportunities',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'critical.path',
    description: 'Legacy query operation orchestrate.critical.path',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'show',
    description: 'Legacy query operation research.show',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'list',
    description: 'Legacy query operation research.list',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'find',
    description: 'Legacy query operation research.find',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'pending',
    description: 'Legacy query operation research.pending',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'stats',
    description: 'Legacy query operation research.stats',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'manifest.read',
    description: 'Legacy query operation research.manifest.read',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'contradictions',
    description: 'Legacy query operation research.contradictions',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'superseded',
    description: 'Legacy query operation research.superseded',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'validate',
    description: 'Legacy query operation lifecycle.validate',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'status',
    description: 'Legacy query operation lifecycle.status',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'history',
    description: 'Legacy query operation lifecycle.history',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'gates',
    description: 'Legacy query operation lifecycle.gates',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'prerequisites',
    description: 'Legacy query operation lifecycle.prerequisites',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'schema',
    description: 'Legacy query operation validate.schema',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'protocol',
    description: 'Legacy query operation validate.protocol',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'task',
    description: 'Legacy query operation validate.task',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'manifest',
    description: 'Legacy query operation validate.manifest',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'output',
    description: 'Legacy query operation validate.output',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'compliance.summary',
    description: 'Legacy query operation validate.compliance.summary',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'compliance.violations',
    description: 'Legacy query operation validate.compliance.violations',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'test.status',
    description: 'Legacy query operation validate.test.status',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'test.coverage',
    description: 'Legacy query operation validate.test.coverage',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'coherence.check',
    description: 'Legacy query operation validate.coherence.check',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'version',
    description: 'Legacy query operation system.version',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'health',
    description: 'Legacy query operation system.health',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'config.get',
    description: 'Legacy query operation system.config.get',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'stats',
    description: 'Legacy query operation system.stats',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'context',
    description: 'Legacy query operation system.context',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'job.status',
    description: 'Legacy query operation system.job.status',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'job.list',
    description: 'Legacy query operation system.job.list',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'dash',
    description: 'Legacy query operation system.dash',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'roadmap',
    description: 'Legacy query operation system.roadmap',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'labels',
    description: 'Legacy query operation system.labels',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'compliance',
    description: 'Legacy query operation system.compliance',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'log',
    description: 'Legacy query operation system.log',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'archive.stats',
    description: 'Legacy query operation system.archive.stats',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'sequence',
    description: 'Legacy query operation system.sequence',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    legacyDomain: 'issues',
    operation: 'diagnostics',
    description: 'Legacy query operation issues.diagnostics',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'list',
    description: 'Legacy query operation skills.list',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'show',
    description: 'Legacy query operation skills.show',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'find',
    description: 'Legacy query operation skills.find',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'dispatch',
    description: 'Legacy query operation skills.dispatch',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'verify',
    description: 'Legacy query operation skills.verify',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'dependencies',
    description: 'Legacy query operation skills.dependencies',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'providers',
    operation: 'list',
    description: 'Legacy query operation providers.list',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'providers',
    operation: 'detect',
    description: 'Legacy query operation providers.detect',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    legacyDomain: 'providers',
    operation: 'inject.status',
    description: 'Legacy query operation providers.inject.status',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'add',
    description: 'Legacy mutate operation tasks.add',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'update',
    description: 'Legacy mutate operation tasks.update',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'complete',
    description: 'Legacy mutate operation tasks.complete',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'delete',
    description: 'Legacy mutate operation tasks.delete',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'archive',
    description: 'Legacy mutate operation tasks.archive',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'restore',
    description: 'Legacy mutate operation tasks.restore',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reparent',
    description: 'Legacy mutate operation tasks.reparent',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'promote',
    description: 'Legacy mutate operation tasks.promote',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reorder',
    description: 'Legacy mutate operation tasks.reorder',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reopen',
    description: 'Legacy mutate operation tasks.reopen',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'relates.add',
    description: 'Legacy mutate operation tasks.relates.add',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'uncancel',
    description: 'Legacy mutate operation tasks.uncancel',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'start',
    description: 'Legacy mutate operation tasks.start',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'stop',
    description: 'Legacy mutate operation tasks.stop',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'start',
    description: 'Legacy mutate operation session.start',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'end',
    description: 'Legacy mutate operation session.end',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'resume',
    description: 'Legacy mutate operation session.resume',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'suspend',
    description: 'Legacy mutate operation session.suspend',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'gc',
    description: 'Legacy mutate operation session.gc',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'record.decision',
    description: 'Legacy mutate operation session.record.decision',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'record.assumption',
    description: 'Legacy mutate operation session.record.assumption',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'start',
    description: 'Legacy mutate operation orchestrate.start',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'spawn',
    description: 'Legacy mutate operation orchestrate.spawn',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'validate',
    description: 'Legacy mutate operation orchestrate.validate',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'parallel.start',
    description: 'Legacy mutate operation orchestrate.parallel.start',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'parallel.end',
    description: 'Legacy mutate operation orchestrate.parallel.end',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'inject',
    description: 'Legacy mutate operation research.inject',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'link',
    description: 'Legacy mutate operation research.link',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'manifest.append',
    description: 'Legacy mutate operation research.manifest.append',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'research',
    operation: 'manifest.archive',
    description: 'Legacy mutate operation research.manifest.archive',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'record',
    description: 'Legacy mutate operation lifecycle.record',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'skip',
    description: 'Legacy mutate operation lifecycle.skip',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'reset',
    description: 'Legacy mutate operation lifecycle.reset',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'gate.pass',
    description: 'Legacy mutate operation lifecycle.gate.pass',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'lifecycle',
    operation: 'gate.fail',
    description: 'Legacy mutate operation lifecycle.gate.fail',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'compliance.record',
    description: 'Legacy mutate operation validate.compliance.record',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'check',
    legacyDomain: 'validate',
    operation: 'test.run',
    description: 'Legacy mutate operation validate.test.run',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'release',
    operation: 'prepare',
    description: 'Legacy mutate operation release.prepare',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'release',
    operation: 'changelog',
    description: 'Legacy mutate operation release.changelog',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'release',
    operation: 'commit',
    description: 'Legacy mutate operation release.commit',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'release',
    operation: 'tag',
    description: 'Legacy mutate operation release.tag',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'release',
    operation: 'push',
    description: 'Legacy mutate operation release.push',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'release',
    operation: 'gates.run',
    description: 'Legacy mutate operation release.gates.run',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    legacyDomain: 'release',
    operation: 'rollback',
    description: 'Legacy mutate operation release.rollback',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'init',
    description: 'Legacy mutate operation system.init',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'config.set',
    description: 'Legacy mutate operation system.config.set',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'backup',
    description: 'Legacy mutate operation system.backup',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'restore',
    description: 'Legacy mutate operation system.restore',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'migrate',
    description: 'Legacy mutate operation system.migrate',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'sync',
    description: 'Legacy mutate operation system.sync',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'cleanup',
    description: 'Legacy mutate operation system.cleanup',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'job.cancel',
    description: 'Legacy mutate operation system.job.cancel',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'safestop',
    description: 'Legacy mutate operation system.safestop',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'uncancel',
    description: 'Legacy mutate operation system.uncancel',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    legacyDomain: 'system',
    operation: 'inject.generate',
    description: 'Legacy mutate operation system.inject.generate',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    legacyDomain: 'issues',
    operation: 'create.bug',
    description: 'Legacy mutate operation issues.create.bug',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    legacyDomain: 'issues',
    operation: 'create.feature',
    description: 'Legacy mutate operation issues.create.feature',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    legacyDomain: 'issues',
    operation: 'create.help',
    description: 'Legacy mutate operation issues.create.help',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'install',
    description: 'Legacy mutate operation skills.install',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'uninstall',
    description: 'Legacy mutate operation skills.uninstall',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'enable',
    description: 'Legacy mutate operation skills.enable',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'disable',
    description: 'Legacy mutate operation skills.disable',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'configure',
    description: 'Legacy mutate operation skills.configure',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    legacyDomain: 'skills',
    operation: 'refresh',
    description: 'Legacy mutate operation skills.refresh',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    legacyDomain: 'providers',
    operation: 'inject',
    description: 'Legacy mutate operation providers.inject',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
];

// --- Registration & Validation Logic ---

/**
 * Resolves a requested domain (canonical or alias) and operation
 * to its true definition.
 */
export function resolve(gateway: Gateway, requestedDomain: string, requestedOperation: string): AliasResolution | undefined {
  const canonicalDomain = resolveAlias(requestedDomain);
  
  const def = OPERATIONS.find(
    o => o.gateway === gateway && o.domain === canonicalDomain && o.operation === requestedOperation
  );

  if (!def) return undefined;

  const aliased = requestedDomain !== canonicalDomain;

  return {
    domain: canonicalDomain,
    operation: requestedOperation,
    def,
    alias: {
      aliased,
      deprecation: aliased ? `Domain '${requestedDomain}' is deprecated. Please use the canonical domain '${canonicalDomain}' instead.` : undefined,
    }
  };
}

/**
 * Normalizes any domain alias to its canonical equivalent.
 */
export function resolveAlias(requestedDomain: string): CanonicalDomain {
  if (requestedDomain in LEGACY_TO_CANONICAL) {
    return LEGACY_TO_CANONICAL[requestedDomain];
  }
  return requestedDomain as CanonicalDomain;
}

/**
 * Validates that all required parameters are present in the request.
 * Returns an array of missing parameter keys.
 */
export function validateRequiredParams(def: OperationDef, params?: Record<string, unknown>): string[] {
  if (!def.requiredParams || def.requiredParams.length === 0) return [];
  const provided = params || {};
  return def.requiredParams.filter(key => provided[key] === undefined || provided[key] === null || provided[key] === '');
}

/** Get all operations for a specific canonical domain. */
export function getByDomain(domain: CanonicalDomain): OperationDef[] {
  return OPERATIONS.filter(o => o.domain === domain);
}

/** Get all operations for a specific gateway. */
export function getByGateway(gateway: Gateway): OperationDef[] {
  return OPERATIONS.filter(o => o.gateway === gateway);
}

/** Get all operations available at or below a specific tier. */
export function getByTier(tier: Tier): OperationDef[] {
  return OPERATIONS.filter(o => o.tier <= tier);
}

/** Get a list of canonical domains that actually have operations registered. */
export function getActiveDomains(): CanonicalDomain[] {
  const active = new Set(OPERATIONS.map(o => o.domain));
  return Array.from(active);
}

/** Check if a given string is a recognized legacy domain alias. */
export function isLegacyDomain(domain: string): boolean {
  return domain in LEGACY_TO_CANONICAL;
}

/**
 * Returns summary counts of operations for module validation.
 */
export function getCounts(): { query: number; mutate: number; total: number } {
  return {
    query: OPERATIONS.filter(o => o.gateway === 'query').length,
    mutate: OPERATIONS.filter(o => o.gateway === 'mutate').length,
    total: OPERATIONS.length,
  };
}

// Module load validation
const counts = getCounts();
if (counts.query !== 75 || counts.mutate !== 65) {
  console.warn(`[Registry] Expected 75 query & 65 mutate ops, got ${counts.query} query & ${counts.mutate} mutate.`);
}
