/**
 * Unified CQRS Dispatch Layer -- Operation Registry
 *
 * Single source of truth for all operations mapped to 10 canonical domains.
 * Canonical domains only -- no legacy alias support.
 *
 * @epic T4820
 * @task T4814, T5241, T5615
 */

import { Gateway, Tier, CanonicalDomain, type ParamDef } from './types.js';

/** Definition of a single dispatchable operation. */
export interface OperationDef {
  /** The CQRS gateway ('query' or 'mutate'). */
  gateway: Gateway;
  /** The canonical domain this operation belongs to. */
  domain: CanonicalDomain;
  /** The specific operation name (e.g. 'show', 'skill.list'). */
  operation: string;
  /** Brief description of what the operation does. */
  description: string;
  /** Agent progressive-disclosure tier (0=basic, 1=memory/check, 2=full). */
  tier: Tier;
  /** Whether the operation is safe to retry. */
  idempotent: boolean;
  /** Whether this operation requires an active session. */
  sessionRequired: boolean;
  /** List of parameter keys that MUST be present in the request. */
  requiredParams: string[];
  /**
   * Fully-described parameter list. Replaces `requiredParams` when populated.
   * Empty array = "no declared params" (not "no params accepted").
   * Optional during T4897 migration — defaults to [] when absent.
   * @see T4897 for progressive migration
   */
  params?: ParamDef[];
}

/**
 * Resolution output for a dispatch request.
 */
export interface Resolution {
  /** The canonical domain. */
  domain: CanonicalDomain;
  /** The operation name. */
  operation: string;
  /** The definition of the matched operation. */
  def: OperationDef;
}

/**
 * The single source of truth for all operations in CLEO.
 */
export const OPERATIONS: OperationDef[] = [
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'show',
    description: 'tasks.show (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'list',
    description: 'tasks.list (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'parent', type: 'string', required: false, description: 'Filter by parent task ID' },
      { name: 'status', type: 'string', required: false, description: 'Filter by task status' },
      { name: 'priority', type: 'string', required: false, description: 'Filter by task priority' },
      { name: 'type', type: 'string', required: false, description: 'Filter by task type' },
      { name: 'phase', type: 'string', required: false, description: 'Filter by task phase' },
      { name: 'label', type: 'string', required: false, description: 'Filter by task label' },
      { name: 'children', type: 'boolean', required: false, description: 'Limit parent queries to direct children' },
      { name: 'limit', type: 'number', required: false, description: 'Maximum number of tasks to return' },
      { name: 'offset', type: 'number', required: false, description: 'Number of filtered tasks to skip' },
      { name: 'compact', type: 'boolean', required: false, description: 'Deprecated: request compact task rows for compatibility' },
    ],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'find',
    description: 'tasks.find (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'tree',
    description: 'tasks.tree (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'blockers',
    description: 'tasks.blockers (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'depends',
    description: 'tasks.depends (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'analyze',
    description: 'tasks.analyze (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'next',
    description: 'tasks.next (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'plan',
    description: 'Composite planning view with in-progress epics, ready tasks, blocked tasks, and open bugs (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'relates',
    description: 'tasks.relates (query) — absorbs relates.find via mode param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'complexity.estimate',
    description: 'tasks.complexity.estimate (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'tasks' as const,
    operation: 'history',
    description: 'Show task work history (time tracked per task)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'current',
    description: 'tasks.current (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // Label operations (dispatch migration)
  {
    gateway: 'query',
    domain: 'tasks',
    operation: 'label.list',
    description: 'List all labels with task counts',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'status',
    description: 'session.status (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'list',
    description: 'session.list (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'status', type: 'string', required: false, description: 'Filter by session status' },
      { name: 'active', type: 'boolean', required: false, description: 'Legacy active-session filter' },
      { name: 'limit', type: 'number', required: false, description: 'Maximum sessions to return' },
      { name: 'offset', type: 'number', required: false, description: 'Skip this many sessions before returning results' },
    ],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'show',
    description: 'session.show (query) — absorbs debrief.show via include param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'decision.log',
    description: 'session.decision.log (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'context.drift',
    description: 'session.context.drift (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'handoff.show',
    description: 'session.handoff.show - Show handoff data from the most recent ended session (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'session',
    operation: 'briefing.show',
    description: 'session.briefing.show - Composite session-start context (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // T4959: Rich debrief removed — merged into session.show via include param (T5615)
  {
    gateway: 'query',
    domain: 'session',
    operation: 'find',
    description: 'session.find (query) — lightweight session discovery',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'status',
    description: 'orchestrate.status (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'next',
    description: 'orchestrate.next (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'ready',
    description: 'orchestrate.ready (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'analyze',
    description: 'orchestrate.analyze (query) — absorbs critical.path via mode param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'context',
    description: 'orchestrate.context (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'waves',
    description: 'orchestrate.waves (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'bootstrap',
    description: 'orchestrate.bootstrap (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'unblock.opportunities',
    description: 'orchestrate.unblock.opportunities (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // orchestrate.critical.path removed — merged into analyze via mode param (T5615)
  // ---------------------------------------------------------------------------
  // memory — brain.db cognitive memory (T5241 cutover)
  // ---------------------------------------------------------------------------
  // memory.show removed — use memory.fetch with single-element ids array (T5615)
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'find',
    description: 'memory.find (query) — cross-table brain.db FTS5 search',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'timeline',
    description: 'memory.timeline (query) — chronological context around anchor',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['anchor'],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'fetch',
    description: 'memory.fetch (query) — batch fetch brain entries by IDs',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['ids'],
  },
  // memory.stats, memory.contradictions, memory.superseded removed — dashboard-only (T5615)
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'decision.find',
    description: 'memory.decision.find (query) — search decisions in brain.db',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'pattern.find',
    description: 'memory.pattern.find (query) — search BRAIN pattern memory by type, impact, or keyword',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // memory.pattern.stats removed — dashboard-only (T5615)
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'learning.find',
    description: 'memory.learning.find (query) — search BRAIN learning memory by confidence, actionability, or keyword',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // memory.learning.stats removed — dashboard-only (T5615)
  // memory — PageIndex graph queries (T5385)
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'graph.show',
    description: 'memory.graph.show (query) — get a PageIndex graph node and its edges',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['nodeId'],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'graph.neighbors',
    description: 'memory.graph.neighbors (query) — get neighbor nodes from the PageIndex graph',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['nodeId'],
  },
  // memory — Reasoning & hybrid search (T5388-T5393)
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'reason.why',
    description: 'memory.reason.why (query) — causal trace through task dependency chains',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['taskId'],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'reason.similar',
    description: 'memory.reason.similar (query) — find semantically similar brain entries',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['entryId'],
  },
  {
    gateway: 'query',
    domain: 'memory',
    operation: 'search.hybrid',
    description: 'memory.search.hybrid (query) — hybrid search across FTS5, vector, and graph',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.validate',
    description: 'pipeline.stage.validate (query) — absorbs stage.prerequisites in response',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.status',
    description: 'pipeline.stage.status (query) — absorbs stage.gates via include param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'stage.history',
    description: 'pipeline.stage.history (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // stage.gates removed — merged into stage.status via include param (T5615)
  // stage.prerequisites removed — always returned in stage.validate response (T5615)
  // T5326: Phase management operations
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'phase.show',
    description: 'Show phase details by slug or current phase (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'phaseId', type: 'string', required: false, description: 'Phase slug (omit for current phase)' },
    ],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'phase.list',
    description: 'List all phases with status and task counts (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // pipeline manifest query operations (T5241 — moved from memory)
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'manifest.show',
    description: 'pipeline.manifest.show (query) — get manifest entry by ID',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['entryId'],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'manifest.list',
    description: 'pipeline.manifest.list (query) — list manifest entries with filters',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'manifest.find',
    description: 'pipeline.manifest.find (query) — search manifest entries by text',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  // manifest.pending removed — merged into manifest.list via filter param (T5615)
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'manifest.stats',
    description: 'pipeline.manifest.stats (query) — manifest statistics',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // T5405: WarpChain pipeline operations
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'chain.show',
    description: 'pipeline.chain.show (query) — get chain definition by ID',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['chainId'],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'chain.list',
    description: 'pipeline.chain.list (query) — list all chain definitions',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'schema',
    description: 'check.schema (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'protocol',
    description: 'check.protocol (query) — absorbs all protocol.* ops via protocolType param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'task',
    description: 'check.task (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'manifest',
    description: 'check.manifest (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'output',
    description: 'check.output (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'compliance.summary',
    description: 'check.compliance.summary (query) — absorbs compliance.violations via detail param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // compliance.violations removed — merged into compliance.summary via detail param (T5615)
  // test.status removed — merged into test op (T5615)
  {
    gateway: 'query',
    domain: 'check',
    operation: 'test',
    description: 'check.test (query) — combined test status and coverage via format param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'coherence',
    description: 'check.coherence (query) — renamed from coherence.check (T5615)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },

  // Protocol validation operations (T5327) — protocol.consensus/contribution/decomposition/implementation/specification
  // removed — folded into check.protocol via protocolType param (T5615)

  // gate.verify split into gate.status (query) + gate.set (mutate) (T5615)
  {
    gateway: 'query',
    domain: 'check',
    operation: 'gate.status',
    description: 'check.gate.status (query) — read-only gate state; split from gate.verify (T5615)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['taskId'],
  },
  // check.archive.stats incoming from admin (T5615)
  {
    gateway: 'query',
    domain: 'check',
    operation: 'archive.stats',
    description: 'check.archive.stats (query) — archive analytics; moved from admin (T5615)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // check.grade and check.grade.list incoming from admin (T5615)
  {
    gateway: 'query',
    domain: 'check',
    operation: 'grade',
    description: 'check.grade (query) — grade agent behavioral session; moved from admin (T5615)',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['sessionId'],
  },
  {
    gateway: 'query',
    domain: 'check',
    operation: 'grade.list',
    description: 'check.grade.list (query) — list past session grade results; moved from admin (T5615)',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'sessionId', type: 'string', required: false, description: 'Filter grades by session ID' },
      { name: 'limit', type: 'number', required: false, description: 'Maximum grade entries to return' },
      { name: 'offset', type: 'number', required: false, description: 'Skip this many grade entries before returning results' },
    ],
  },
  // T5405: WarpChain validation query
  {
    gateway: 'query',
    domain: 'check',
    operation: 'chain.validate',
    description: 'check.chain.validate (query) — validate a WarpChain definition',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['chain'],
  },

  {
    gateway: 'query',
    domain: 'admin',
    operation: 'version',
    description: 'admin.version (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'health',
    description: 'admin.health (query) — absorbs doctor via mode param',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'config.show',
    description: 'admin.config.show (query) — show config value',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'stats',
    description: 'admin.stats (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'context',
    description: 'admin.context (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'runtime',
    description: 'admin.runtime (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.job.status + admin.job.list merged into admin.job via action param (T5615)
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'job',
    description: 'admin.job (query) — absorbs job.status and job.list via action param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'action', type: 'string', required: false, description: 'Action: status (default) or list' },
      { name: 'status', type: 'string', required: false, description: 'Filter jobs by status (for list action)' },
      { name: 'limit', type: 'number', required: false, description: 'Maximum jobs to return (for list action)' },
      { name: 'offset', type: 'number', required: false, description: 'Skip this many jobs before returning results' },
    ],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'dash',
    description: 'admin.dash (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'log',
    description: 'admin.log (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'sequence',
    description: 'admin.sequence (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'help',
    description: 'Get operations list and guidance filtered to specified disclosure tier',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      {
        name: 'tier',
        type: 'number',
        required: false,
        description: 'Progressive disclosure tier: 0=basic (default), 1=+memory/check, 2=all operations',
        cli: { flag: 'tier', short: '-t' },
      },
      {
        name: 'verbose',
        type: 'boolean',
        required: false,
        description: 'Return full operation objects instead of compact domain-grouped format',
        cli: { flag: 'verbose' },
      },
    ],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'issue.diagnostics',
    description: 'tools.issue.diagnostics (query) — CLEO install integrity check',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // tools.issue.templates and tools.issue.validate.labels moved to ct-github-issues plugin (T5615)
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.list',
    description: 'tools.skill.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.show',
    description: 'tools.skill.show (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.find',
    description: 'tools.skill.find (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.dispatch',
    description: 'tools.skill.dispatch (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.verify',
    description: 'tools.skill.verify (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.dependencies',
    description: 'tools.skill.dependencies (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.spawn.providers',
    description: 'List spawn-capable providers by capability (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // skill.catalog.protocols/profiles/resources/info merged into skill.catalog via type param (T5615)
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.catalog',
    description: 'tools.skill.catalog (query) — CAAMP catalog; absorbs catalog.protocols/profiles/resources/info via type param',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'type', type: 'string', required: false, description: 'Catalog type: protocols, profiles, resources, or info (default)' },
    ],
  },
  // skill.precedence.show/resolve merged into skill.precedence via action param (T5615)
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'skill.precedence',
    description: 'tools.skill.precedence (query) — absorbs precedence.show and precedence.resolve via action param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'action', type: 'string', required: false, description: 'Action: show (default) or resolve' },
      { name: 'providerId', type: 'string', required: false, description: 'Provider ID for resolve action' },
    ],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.list',
    description: 'tools.provider.list (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.detect',
    description: 'tools.provider.detect (query)',
    tier: 0,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.inject.status',
    description: 'tools.provider.inject.status (query)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.supports',
    description: 'tools.provider.supports (query) - check if provider supports capability',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['providerId', 'capability'],
    params: [
      { name: 'providerId', type: 'string', required: true, description: 'Provider ID (e.g., claude-code)' },
      { name: 'capability', type: 'string', required: true, description: 'Capability path in dot notation (e.g., spawn.supportsSubagents)' },
    ],
  },
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'provider.hooks',
    description: 'tools.provider.hooks (query) - list providers by hook event support',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['event'],
    params: [
      { name: 'event', type: 'string', required: true, description: 'Hook event to query (e.g., onSessionStart, onToolComplete)' },
    ],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'add',
    description: 'tasks.add (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'update',
    description: 'tasks.update (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'complete',
    description: 'tasks.complete (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'cancel',
    description: 'tasks.cancel (mutate) — cancel task (soft terminal state; reversible via tasks.restore)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['taskId'],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'delete',
    description: 'tasks.delete (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'archive',
    description: 'tasks.archive (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'restore',
    description: 'tasks.restore (mutate) — absorbs reopen and unarchive via from param',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reparent',
    description: 'tasks.reparent (mutate) — absorbs promote via newParentId:null',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'reorder',
    description: 'tasks.reorder (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'relates.add',
    description: 'tasks.relates.add (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'start',
    description: 'tasks.start (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tasks',
    operation: 'stop',
    description: 'tasks.stop (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'start',
    description: 'session.start (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'end',
    description: 'session.end (mutate)',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'resume',
    description: 'session.resume (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'suspend',
    description: 'session.suspend (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'gc',
    description: 'session.gc (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'record.decision',
    description: 'session.record.decision (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'session',
    operation: 'record.assumption',
    description: 'session.record.assumption (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // session.context.inject moved to admin.context.inject (T5615)
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'start',
    description: 'orchestrate.start (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'spawn',
    description: 'orchestrate.spawn (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'handoff',
    description: 'orchestrate.handoff (mutate) — composite handoff (context.inject -> session.end -> spawn)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['taskId', 'protocolType'],
    params: [
      { name: 'taskId', type: 'string', required: true, description: 'Successor task ID for spawn context' },
      { name: 'protocolType', type: 'string', required: true, description: 'Protocol name for handoff context injection' },
      { name: 'note', type: 'string', required: false, description: 'Optional handoff note persisted through session.end' },
      { name: 'nextAction', type: 'string', required: false, description: 'Optional next action metadata for the handoff payload' },
      { name: 'variant', type: 'string', required: false, description: 'Optional context injection variant' },
      { name: 'tier', type: 'number', required: false, description: 'Progressive disclosure tier (0-2)' },
      { name: 'idempotencyKey', type: 'string', required: false, description: 'Caller-provided retry correlation key (reported in metadata)' },
    ],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'spawn.execute',
    description: 'orchestrate.spawn.execute (mutate) — execute spawn for a task using adapter registry',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['taskId'],
    params: [
      { name: 'taskId', type: 'string', required: true, description: 'Task ID to spawn' },
      { name: 'adapterId', type: 'string', required: false, description: 'Adapter ID (auto-select if omitted)' },
      { name: 'protocolType', type: 'string', required: false, description: 'Protocol type override' },
      { name: 'tier', type: 'number', required: false, description: 'Progressive disclosure tier (0-2)' },
    ],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'validate',
    description: 'orchestrate.validate (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // parallel.start and parallel.end merged into orchestrate.parallel via action param (T5615)
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'parallel',
    description: 'orchestrate.parallel (mutate) — absorbs parallel.start and parallel.end via action param',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['action'],
    params: [
      { name: 'action', type: 'string', required: true, description: 'Action: start or end' },
    ],
  },
  // memory mutate — brain.db cognitive memory (T5241 cutover)
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'observe',
    description: 'memory.observe (mutate) — save observation to brain.db',
    tier: 0,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['text'],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'decision.store',
    description: 'memory.decision.store (mutate) — store decision to brain.db',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['decision', 'rationale'],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'pattern.store',
    description: 'memory.pattern.store (mutate) — store a reusable workflow or anti-pattern in BRAIN pattern memory',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['pattern', 'context'],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'learning.store',
    description: 'memory.learning.store (mutate) — store an insight or lesson learned in BRAIN learning memory',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['insight', 'source'],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'link',
    description: 'memory.link (mutate) — link brain entry to task',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['taskId', 'entryId'],
  },
  // memory.unlink removed — rarely needed; direct repair if needed (T5615)
  // memory — PageIndex graph mutations (T5385)
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'graph.add',
    description: 'memory.graph.add (mutate) — add a node or edge to the PageIndex graph',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'memory',
    operation: 'graph.remove',
    description: 'memory.graph.remove (mutate) — remove a node or edge from the PageIndex graph',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.record',
    description: 'pipeline.stage.record (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.skip',
    description: 'pipeline.stage.skip (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.reset',
    description: 'pipeline.stage.reset (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.gate.pass',
    description: 'pipeline.stage.gate.pass (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'stage.gate.fail',
    description: 'pipeline.stage.gate.fail (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // pipeline manifest mutate operations (T5241 — moved from memory)
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'manifest.append',
    description: 'pipeline.manifest.append (mutate) — append entry to MANIFEST.jsonl',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['entry'],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'manifest.archive',
    description: 'pipeline.manifest.archive (mutate) — archive old manifest entries',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['beforeDate'],
  },
  // T5326: Phase mutation operations
  {
    gateway: 'mutate' as const,
    domain: 'pipeline' as const,
    operation: 'phase.set',
    description: 'Set the active phase',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['phaseId'],
    params: [
      { name: 'phaseId', type: 'string', required: true, description: 'Phase slug to set as current' },
      { name: 'rollback', type: 'boolean', required: false, description: 'Allow backward phase movement' },
      { name: 'force', type: 'boolean', required: false, description: 'Skip confirmation prompt' },
      { name: 'dryRun', type: 'boolean', required: false, description: 'Preview changes without modifying files' },
    ],
  },
  // phase.start and phase.complete removed — merged into phase.set via action param (T5615)
  {
    gateway: 'mutate' as const,
    domain: 'pipeline' as const,
    operation: 'phase.advance',
    description: 'Complete current phase and start next',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'force', type: 'boolean', required: false, description: 'Skip validation and interactive prompt' },
    ],
  },
  {
    gateway: 'mutate' as const,
    domain: 'pipeline' as const,
    operation: 'phase.rename',
    description: 'Rename a phase and update all task references',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['oldName', 'newName'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'pipeline' as const,
    operation: 'phase.delete',
    description: 'Delete a phase with task reassignment protection',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['phaseId'],
    params: [
      { name: 'phaseId', type: 'string', required: true, description: 'Phase slug to delete' },
      { name: 'reassignTo', type: 'string', required: false, description: 'Reassign tasks to another phase' },
      { name: 'force', type: 'boolean', required: false, description: 'Required safety flag' },
    ],
  },
  // T5405: WarpChain pipeline mutate operations
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'chain.add',
    description: 'pipeline.chain.add (mutate) — store a validated chain definition',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['chain'],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'chain.instantiate',
    description: 'pipeline.chain.instantiate (mutate) — create chain instance for epic',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['chainId', 'epicId'],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'chain.advance',
    description: 'pipeline.chain.advance (mutate) — advance instance to next stage',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['instanceId', 'nextStage'],
  },
  {
    gateway: 'mutate',
    domain: 'check',
    operation: 'compliance.record',
    description: 'check.compliance.record (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'check',
    operation: 'test.run',
    description: 'check.test.run (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'check',
    operation: 'gate.set',
    description: 'check.gate.set (mutate) — write path of former gate.verify; set/reset gates (T5615)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'release.list',
    description: 'List all releases from release_manifests table',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'release.show',
    description: 'Show details for a specific release version',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['version'],
  },
  {
    gateway: 'query',
    domain: 'pipeline',
    operation: 'release.channel.show',
    description: 'Show the current release channel based on git branch (latest/beta/alpha)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // release.prepare/changelog/commit/tag/push/gates.run removed — merged into release.ship via step param (T5615)
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.cancel',
    description: 'pipeline.release.cancel (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['version'],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.rollback',
    description: 'pipeline.release.rollback (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'pipeline',
    operation: 'release.ship',
    description: 'Ship a release: validate gates → write CHANGELOG → git commit/tag/push → record provenance; absorbs prepare/changelog/commit/tag/push/gates.run via step param',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['version', 'epicId'],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'init',
    description: 'admin.init (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'config.set',
    description: 'admin.config.set (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'backup',
    description: 'admin.backup (mutate) — absorbs restore and backup.restore via action param',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.restore and admin.backup.restore removed — merged into admin.backup via action param (T5615)
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'migrate',
    description: 'admin.migrate (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.sync/sync.status/sync.clear moved to tools.todowrite.* (T5615)
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'cleanup',
    description: 'admin.cleanup (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'job.cancel',
    description: 'admin.job.cancel (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'safestop',
    description: 'admin.safestop (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'inject.generate',
    description: 'admin.inject.generate (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.sequence (mutate) removed — duplicate name; expose via config.set if needed (T5615)
  // tools.issue.add.bug/feature/help moved to ct-github-issues plugin (T5615)
  // tools.issue.generate.config removed — stub with no runtime need (T5615)
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.install',
    description: 'tools.skill.install (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.uninstall',
    description: 'tools.skill.uninstall (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // skill.enable/disable removed — aliases for install/uninstall (T5615)
  // skill.configure removed — stub with no real behavior (T5615)
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'skill.refresh',
    description: 'tools.skill.refresh (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'provider.inject',
    description: 'tools.provider.inject (mutate)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // TodoWrite ops moved from admin domain (T5615)
  {
    gateway: 'query',
    domain: 'tools',
    operation: 'todowrite.status',
    description: 'tools.todowrite.status (query) — TodoWrite sync status; moved from admin.sync.status (T5615)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'todowrite.sync',
    description: 'tools.todowrite.sync (mutate) — TodoWrite sync; moved from admin.sync (T5615)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate',
    domain: 'tools',
    operation: 'todowrite.clear',
    description: 'tools.todowrite.clear (mutate) — clear TodoWrite sync state; moved from admin.sync.clear (T5615)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'dryRun', type: 'boolean', required: false, description: 'Preview what would be cleared' },
    ],
  },
  // T4916: Global install refresh
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'install.global',
    description: 'Refresh global CLEO setup: provider files, MCP configs, ~/.agents/AGENTS.md',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.grade/grade.list/archive.stats moved to check domain (T5615)
  // admin.token.summary/list/show merged into admin.token (query) (T5615)
  {
    gateway: 'query',
    domain: 'admin',
    operation: 'token',
    description: 'admin.token (query) — summarize/list/show token telemetry; absorbs token.summary, token.list, token.show via action param',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'action', type: 'string', required: false, description: 'Action: summary (default), list, or show' },
      { name: 'tokenId', type: 'string', required: false, description: 'Token ID for show action' },
      { name: 'provider', type: 'string', required: false, description: 'Filter by provider' },
      { name: 'transport', type: 'string', required: false, description: 'Filter by transport' },
      { name: 'domain', type: 'string', required: false, description: 'Filter by domain' },
      { name: 'operationName', type: 'string', required: false, description: 'Filter by operation name' },
      { name: 'sessionId', type: 'string', required: false, description: 'Filter by session ID' },
      { name: 'taskId', type: 'string', required: false, description: 'Filter by task ID' },
      { name: 'limit', type: 'number', required: false, description: 'Maximum records to return' },
      { name: 'offset', type: 'number', required: false, description: 'Skip this many records before returning results' },
    ],
  },
  // admin.token.record/delete/clear merged into admin.token (mutate) (T5615)
  {
    gateway: 'mutate',
    domain: 'admin',
    operation: 'token',
    description: 'admin.token (mutate) — record/delete/clear token telemetry; absorbs token.record, token.delete, token.clear via action param',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'action', type: 'string', required: false, description: 'Action: record (default), delete, or clear' },
      { name: 'tokenId', type: 'string', required: false, description: 'Token ID for delete action' },
    ],
  },

  // ADR operations (ADR-017 §2, Tier 2 — admin domain)
  // admin.adr.list merged into adr.find (absent query = list all) (T5615)
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'adr.show',
    description: 'admin.adr.show (query) — retrieve single ADR by ID with frontmatter',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['adrId'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'adr.sync',
    description: 'admin.adr.sync (mutate) — sync .cleo/adrs/ markdown files into architecture_decisions DB table; absorbs adr.validate via validate flag',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.adr.validate removed — merged into adr.sync via validate flag (T5615)
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'adr.find',
    description: 'admin.adr.find (query) — fuzzy search ADRs; absorbs adr.list when query absent',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'query', type: 'string', required: false, description: 'Search query (omit to list all ADRs)' },
      { name: 'status', type: 'string', required: false, description: 'Filter ADRs by status' },
      { name: 'since', type: 'string', required: false, description: 'Filter ADRs created on or after this date' },
      { name: 'limit', type: 'number', required: false, description: 'Maximum ADRs to return' },
      { name: 'offset', type: 'number', required: false, description: 'Skip this many ADRs before returning results' },
    ],
  },
  // admin.doctor removed — merged into admin.health via mode:"diagnose" param (T5615)
  // admin.fix removed — merged into admin.health (mutate) via mode:"repair" param (T5615)
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'health',
    description: 'admin.health (mutate) — auto-fix failed health/doctor checks; mode:"repair" form of admin.health query (T5615)',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.context.inject moved from session.context.inject (T5615)
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'context.inject',
    description: 'admin.context.inject (mutate) — inject protocol content into session context; moved from session domain (T5615)',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['protocolType'],
  },
  // admin.snapshot.export/export.tasks merged into admin.export via scope param (T5615)
  {
    gateway: 'query' as const,
    domain: 'admin',
    operation: 'export',
    description: 'admin.export (query) — export tasks; absorbs snapshot.export and export.tasks via scope param',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // admin.snapshot.import/import.tasks merged into admin.import via scope param (T5615)
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'import',
    description: 'admin.import (mutate) — import tasks; absorbs snapshot.import and import.tasks via scope param',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['file'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'admin',
    operation: 'detect',
    description: 'Refresh project-context.json — re-detect project type, framework, and LLM hints',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },

  // ---------------------------------------------------------------------------
  // nexus.share — multi-contributor operations
  // ---------------------------------------------------------------------------
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'share.status',
    description: 'nexus.share.status (query) — sharing status',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // nexus.share.remotes removed — git CLI wrapper (T5615)
  // nexus.share.sync.status removed — git CLI wrapper (T5615)
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'share.snapshot.export',
    description: 'nexus.share.snapshot.export (mutate) — export project snapshot',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'share.snapshot.import',
    description: 'nexus.share.snapshot.import (mutate) — import project snapshot',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: [],
  },
  // nexus.share.sync.gitignore/remote.add/remote.remove/share.push/share.pull removed — git wrappers (T5615)

  // ---------------------------------------------------------------------------
  // nexus — Cross-project coordination (BRAIN Network)
  // ---------------------------------------------------------------------------

  // Query operations
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'status',
    description: 'nexus.status (query) — overall NEXUS health status',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'list',
    description: 'nexus.list (query) — list all registered NEXUS projects',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'show',
    description: 'nexus.show (query) — show a specific project by name or hash',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['name'],
  },
  // nexus.query renamed to nexus.resolve — 'query' violates VERB-STANDARDS (T5615)
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'resolve',
    description: 'nexus.resolve (query) — resolve a cross-project project:taskId reference; renamed from nexus.query (T5615)',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'deps',
    description: 'nexus.deps (query) — cross-project dependency analysis',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'graph',
    description: 'nexus.graph (query) — global dependency graph across all projects',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'path.show',
    description: 'nexus.path.show (query) — show critical dependency path across projects',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'blockers.show',
    description: 'nexus.blockers.show (query) — show blocking impact for a task query',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'orphans.list',
    description: 'nexus.orphans.list (query) — list orphaned cross-project dependencies',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  // nexus.critical-path/blocking/orphans removed — aliases for path.show/blockers.show/orphans.list (T5615)
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'discover',
    description: 'nexus.discover (query) — discover related tasks across registered projects',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['query'],
  },
  {
    gateway: 'query' as const,
    domain: 'nexus',
    operation: 'search',
    description: 'nexus.search (query) — search for patterns across registered projects',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['pattern'],
  },

  // Mutate operations
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'init',
    description: 'nexus.init (mutate) — initialize NEXUS (creates registry and directories)',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'register',
    description: 'nexus.register (mutate) — register a project in NEXUS',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['path'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'unregister',
    description: 'nexus.unregister (mutate) — remove a project from NEXUS',
    tier: 2,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['name'],
  },
  // nexus.sync.all merged into nexus.sync via optional name param (T5615)
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'sync',
    description: 'nexus.sync (mutate) — sync project(s) metadata; absorbs sync.all when name omitted',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'name', type: 'string', required: false, description: 'Project name to sync (omit to sync all)' },
    ],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'permission.set',
    description: 'nexus.permission.set (mutate) — update project permissions',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['name', 'level'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'nexus',
    operation: 'reconcile',
    description: 'nexus.reconcile (mutate) — reconcile project identity with global nexus registry',
    tier: 2,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },

  // ---------------------------------------------------------------------------
  // sticky — Ephemeral notes for quick capture (T5282)
  // ---------------------------------------------------------------------------

  // Query operations
  {
    gateway: 'query' as const,
    domain: 'sticky',
    operation: 'list',
    description: 'sticky.list (query) — list sticky notes',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
  },
  {
    gateway: 'query' as const,
    domain: 'sticky',
    operation: 'show',
    description: 'sticky.show (query) — show a specific sticky note',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['stickyId'],
  },

  // Mutate operations
  {
    gateway: 'mutate' as const,
    domain: 'sticky',
    operation: 'add',
    description: 'sticky.add (mutate) — create a new sticky note',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['content'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sticky',
    operation: 'convert',
    description: 'sticky.convert (mutate) — convert sticky to task, memory, task_note, or session_note',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['stickyId', 'targetType'],
    params: [
      { name: 'stickyId', type: 'string', required: true, description: 'ID of the sticky note' },
      { name: 'targetType', type: 'string', required: true, description: 'Target type: task, memory, task_note, or session_note' },
      { name: 'title', type: 'string', required: false, description: 'Optional task title (for task conversion)' },
      { name: 'memoryType', type: 'string', required: false, description: 'Optional memory type (for memory conversion)' },
      { name: 'taskId', type: 'string', required: false, description: 'Target task ID (required for task_note conversion)' },
      { name: 'sessionId', type: 'string', required: false, description: 'Target session ID (optional for session_note conversion, defaults to active session)' },
    ],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sticky',
    operation: 'archive',
    description: 'sticky.archive (mutate) — archive sticky notes',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['stickyId'],
  },
  {
    gateway: 'mutate' as const,
    domain: 'sticky',
    operation: 'purge',
    description: 'sticky.purge (mutate) — permanently delete sticky notes',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: ['stickyId'],
  },
  // orchestrate — tessera template operations (T5411)
  // tessera.show removed — merged into tessera.list via optional id param (T5615)
  {
    gateway: 'query',
    domain: 'orchestrate',
    operation: 'tessera.list',
    description: 'orchestrate.tessera.list (query) — list Tessera templates; absorbs tessera.show via optional id param',
    tier: 1,
    idempotent: true,
    sessionRequired: false,
    requiredParams: [],
    params: [
      { name: 'id', type: 'string', required: false, description: 'Optional template ID for single-item lookup (replaces tessera.show)' },
    ],
  },
  {
    gateway: 'mutate',
    domain: 'orchestrate',
    operation: 'tessera.instantiate',
    description: 'orchestrate.tessera.instantiate (mutate) — instantiate a Tessera template into a chain instance',
    tier: 1,
    idempotent: false,
    sessionRequired: false,
    requiredParams: ['templateId', 'epicId'],
  },
];

// ---------------------------------------------------------------------------
// Gateway Matrix Derivation
// ---------------------------------------------------------------------------

/**
 * Derive a gateway operation matrix from the registry.
 *
 * Returns `Record<string, string[]>` containing:
 * - All canonical domains with their operations
 *
 * This is the SINGLE derivation point — gateways use this instead of
 * maintaining independent operation lists.
 */
export function deriveGatewayMatrix(gateway: Gateway): Record<string, string[]> {
  const matrix: Record<string, string[]> = {};

  for (const op of OPERATIONS) {
    if (op.gateway !== gateway) continue;
    if (!matrix[op.domain]) matrix[op.domain] = [];
    matrix[op.domain].push(op.operation);
  }

  return matrix;
}

/**
 * Get all accepted domain names for a gateway (canonical only).
 */
export function getGatewayDomains(gateway: Gateway): string[] {
  return Object.keys(deriveGatewayMatrix(gateway));
}

// ---------------------------------------------------------------------------
// Lookup & Validation
// ---------------------------------------------------------------------------

/**
 * Resolves a domain + operation to its registered definition.
 */
export function resolve(gateway: Gateway, domain: string, operation: string): Resolution | undefined {
  const def = OPERATIONS.find(
    o => o.gateway === gateway && o.domain === domain && o.operation === operation,
  );

  if (!def) return undefined;

  return { domain: def.domain, operation: def.operation, def };
}

/**
 * Validates that all required parameters are present in the request.
 * Returns an array of missing parameter keys.
 */
export function validateRequiredParams(def: OperationDef, params?: Record<string, unknown>): string[] {
  if (!def.requiredParams || def.requiredParams.length === 0) return [];
  const provided = params || {};
  return def.requiredParams.filter(key => provided[key] === undefined || provided[key] === null || provided[key] === '');
}

/** Get all operations for a specific canonical domain. */
export function getByDomain(domain: CanonicalDomain): OperationDef[] {
  return OPERATIONS.filter(o => o.domain === domain);
}

/** Get all operations for a specific gateway. */
export function getByGateway(gateway: Gateway): OperationDef[] {
  return OPERATIONS.filter(o => o.gateway === gateway);
}

/** Get all operations available at or below a specific tier. */
export function getByTier(tier: Tier): OperationDef[] {
  return OPERATIONS.filter(o => o.tier <= tier);
}

/** Get a list of canonical domains that actually have operations registered. */
export function getActiveDomains(): CanonicalDomain[] {
  const active = new Set(OPERATIONS.map(o => o.domain));
  return Array.from(active);
}

/**
 * Returns summary counts of operations for module validation.
 */
export function getCounts(): { query: number; mutate: number; total: number } {
  return {
    query: OPERATIONS.filter(o => o.gateway === 'query').length,
    mutate: OPERATIONS.filter(o => o.gateway === 'mutate').length,
    total: OPERATIONS.length,
  };
}

// Module load validation (dynamic, no hardcoded operation totals)
const counts = getCounts();
if (counts.total !== OPERATIONS.length) {
  console.warn(`[Registry] Operation count mismatch: total=${counts.total}, registry=${OPERATIONS.length}`);
}
