-- T13193 R-3 (S5 rebase, journal spec §3.5 Rule 5) — held rows.
--
-- A local op a rebase cannot replay (the stream refused it: a dangling
-- reference, a typed rule, a guard, a post-apply check) stays rewound and is
-- HELD until its echo is decided. Its row undo carries the hold:
--
-- held_at: when the op was held (ISO-8601); NULL when it is not held.
-- held_reason: what refused the replay, the conflict preview `cleo show`
--   returns with E_SYNC_HELD.
-- held_effect: the op's row-count effect while held (+1 for an insert left
--   out, -1 for a delete left undone, else 0); `_sync_ledger.live` and
--   `.held` move by it, so the ledger check stays `count(*) + held`.
-- kept_json: what the rewind of a held insert kept that the stream cannot
--   bring back (its local-only columns and its FK children outside the sync
--   set, R7-2), restored if the insert is applied later (T13269).
--
-- Local-only, like the rest of _sync_row_undo.
--
-- Do not edit this file once applied: its hash is recorded per store.
ALTER TABLE _sync_row_undo ADD COLUMN held_at TEXT;
ALTER TABLE _sync_row_undo ADD COLUMN held_reason TEXT;
ALTER TABLE _sync_row_undo ADD COLUMN held_effect INTEGER NOT NULL DEFAULT 0;
ALTER TABLE _sync_row_undo ADD COLUMN kept_json TEXT;
CREATE INDEX IF NOT EXISTS _sync_row_undo_held ON _sync_row_undo (tbl) WHERE held_at IS NOT NULL;
