-- T12757 (S3 intent subtraction) — apply intents. Journal spec
-- t12342-t12343-journal-design §3.3.
--
-- _sync_apply_intent: what an apply frame wrote, per (tbl, uid, col), with
-- the exact enc() of the stored value. `col` is a column name, or '*I' /
-- '*D' for a row insert or delete, '*K' for a re-key (enc = the new uid). A
-- secret column records '<secret>'. The apply API records an intent in the
-- same transaction as each write it performs (§3.2). The sealer subtracts a
-- frame's intents from that frame's captures field by field, seals only the
-- residual fields as local writes, and deletes the intents with the frame.
-- Local-only.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_apply_intent (
  frame TEXT NOT NULL,
  tbl   TEXT NOT NULL,
  uid   TEXT NOT NULL,
  col   TEXT NOT NULL,
  enc   TEXT NOT NULL,
  PRIMARY KEY (frame, tbl, uid, col)
) WITHOUT ROWID;
