/**
 * Normalized provider response types for the CLEO LLM transport layer.
 *
 * Ported from Hermes `agent/transports/types.py` (Python dataclasses →
 * TypeScript interfaces, snake_case → camelCase). These types define the
 * canonical shape that all provider transports normalize responses to. The
 * shared surface is intentionally minimal — only fields that every downstream
 * consumer reads are top-level. Protocol-specific state goes in `providerData`
 * dicts so that protocol-aware code paths can access it without polluting the
 * shared type.
 *
 * @module llm/normalized-response
 * @task T9263
 * @epic T-LLM-CRED-CENTRALIZATION
 */

import type { ModelTransport } from '../operations/llm.js';

/**
 * Token usage reported by the provider for a single API call.
 *
 * `cachedTokens` is only populated when the provider supports prompt-cache
 * read accounting (Anthropic extended caching, Gemini cached content).
 */
export interface NormalizedUsage {
  /** Tokens consumed by the prompt. */
  inputTokens: number;
  /** Tokens generated by the model. */
  outputTokens: number;
  /** Tokens served from prompt cache (if provider supports caching). */
  cachedTokens?: number;
}

/**
 * A single normalized tool call emitted by the model.
 *
 * `id` is the protocol-canonical identifier used when constructing tool result
 * messages. May be `null` when the provider omits it (rare in practice but
 * possible with some adapters).
 *
 * `providerData` carries per-tool-call protocol metadata that only
 * protocol-aware code reads. Examples:
 * - Codex: `{ call_id: "call_XXX", response_item_id: "fc_XXX" }`
 * - Gemini: `{ extra_content: { thought_signature: "..." } }`
 */
export interface NormalizedToolCall {
  /** Provider-assigned tool-call id (may be null if provider does not surface one). */
  id: string | null;
  /** Tool name as declared in the request. */
  name: string;
  /** Arguments as a JSON string (provider-agnostic). */
  arguments: string;
  /** Provider-specific extras (raw shape, do not depend on). */
  providerData?: Record<string, unknown>;
}

/**
 * Normalized API response from any LLM provider.
 *
 * Shared fields are truly cross-provider — every caller can rely on them
 * without branching on transport. Protocol-specific state goes in
 * `providerData` so that only protocol-aware code paths read it.
 *
 * `raw` is the unmodified SDK response object. Consumers MUST narrow it with
 * a type guard before accessing fields. NEVER log `raw` without scrubbing
 * auth headers.
 */
export interface NormalizedResponse {
  /** Response id from the provider (or a synthesized id if absent). */
  id: string;
  /** Model identifier as reported by the provider. */
  model: string;
  /** Plain text content (null when the model returned only tool calls). */
  content: string | null;
  /** Tool calls, or null when none. */
  toolCalls: NormalizedToolCall[] | null;
  /**
   * Provider-reported stop reason.
   * Common values: `'end_turn'`, `'tool_use'`, `'stop'`, `'max_tokens'`,
   * `'stop_sequence'`, `'tool_calls'`, `'length'`.
   */
  stopReason: string;
  /** Token usage for this call. */
  usage: NormalizedUsage;
  /**
   * Optional model-internal reasoning trace.
   * Populated for Anthropic extended-thinking and OpenAI o1-series models.
   */
  reasoning?: string | null;
  /** Provider-specific response-level extras (raw shape, do not depend on). */
  providerData?: Record<string, unknown>;
  /**
   * Raw provider response — DO NOT log this without scrubbing auth headers.
   *
   * Typed as `unknown` because the concrete SDK response shapes
   * (Anthropic.Message, OpenAI.ChatCompletion, …) are not imported from
   * contracts. Consumers MUST narrow with a type guard before accessing fields.
   */
  raw: unknown;
}

/**
 * A single message in a provider-neutral conversation turn.
 *
 * `toolUseId` is required when `role` is `'tool'` — it identifies which
 * tool call this result resolves, matching {@link NormalizedToolCall.id}.
 */
export interface TransportMessage {
  /** Conversation turn role. */
  role: 'user' | 'assistant' | 'tool';
  /** Message content as plain text. */
  content: string;
  /** Tool-result messages: id of the call this resolves. */
  toolUseId?: string;
}

/**
 * A tool definition passed to the provider.
 *
 * `inputSchema` is a JSON Schema object describing the tool's input parameters.
 * The transport layer passes it through verbatim after any provider-specific
 * adaptation (e.g. Anthropic wraps it in `{ type: "object", ... }`).
 */
export interface TransportTool {
  /** Tool name as it will appear in {@link NormalizedToolCall.name}. */
  name: string;
  /** Human-readable description for the model. */
  description: string;
  /** JSON Schema for input parameters. */
  inputSchema: Record<string, unknown>;
}

/**
 * Request parameters passed to {@link LlmTransport.complete}.
 *
 * `temperature` is normalized to the 0.0–1.0 range; each transport clamps it
 * to the provider's supported range before sending.
 *
 * `signal` may be used to abort in-flight requests (passed through to the
 * underlying fetch / SDK call where supported).
 */
export interface TransportRequest {
  /** Model identifier — provider-specific (e.g. `'claude-sonnet-4-6'`). */
  model: string;
  /** Conversation messages in provider-neutral form. */
  messages: TransportMessage[];
  /** Maximum tokens to generate (NOT input budget). */
  maxTokens: number;
  /** Optional system prompt (Anthropic top-level `system`) or system message (OpenAI). */
  system?: string;
  /** Optional tools the model may call. */
  tools?: TransportTool[];
  /** Sampling temperature in 0.0–1.0 range; provider clamps to its own range. */
  temperature?: number;
  /** AbortSignal for request cancellation. */
  signal?: AbortSignal;
}

/**
 * Provider transport contract.
 *
 * Each concrete transport (Anthropic, OpenAI, Gemini) implements this
 * interface and maps provider-specific API shapes to/from
 * {@link NormalizedResponse}. Role-resolver and executor code works
 * exclusively against this interface so providers are swappable.
 */
export interface LlmTransport {
  /**
   * Provider identifier — matches the `ModelTransport` union so role-resolver
   * can select the correct transport at runtime.
   */
  readonly provider: ModelTransport;
  /**
   * Execute a single completion call and return a normalized response.
   *
   * Implementations MUST:
   * - Never return raw credentials in the response envelope.
   * - Preserve the full provider response in {@link NormalizedResponse.raw}.
   * - Map provider-specific stop reasons to the canonical set where possible.
   *
   * @param request - Provider-neutral request parameters.
   * @returns A promise that resolves to a {@link NormalizedResponse}.
   */
  complete(request: TransportRequest): Promise<NormalizedResponse>;
}
