-- T13399 (T12341 §6.4, §9.2) — a held uid collision settles for every
-- replica that placed the loser, and the loser's origin is still known after
-- its ops are folded.
--
-- A replica other than the loser's origin can place the loser first and
-- write references to its uid. When the origin's K re-keys it, that replica
-- announces the same re-key under its own name (an alias-only K), so
-- receivers read its earlier references through the alias too.
--
-- _sync_uid_alias.placed: 1 when applying a K moved a loser this replica had
--   placed (it was not the K's origin): it owes the announcement.
-- _sync_uid_alias.followed_at: when the announcement was written (NULL: owed).
--
-- _sync_uid_ref_alias: one reference boundary per (table, old uid, origin):
--   references to old_uid written by `origin` before `hlc` mean new_uid. The
--   origin's K and every announcement each add one; _sync_uid_alias keeps one
--   row per re-keyed row and cannot hold more than one origin.
--
-- _sync_authored: every minted row this replica sealed an insert of, by
--   (table, uid, birth fingerprint). The settle path reads it to decide
--   whether this replica is the loser's origin; _sync_op alone forgets once a
--   sealed transaction's ops are folded or collected. Filled from the ops
--   still held.
--
-- Local-only, both stores.
--
-- Do not edit this file once applied: its hash is recorded per store.
ALTER TABLE _sync_uid_alias ADD COLUMN placed INTEGER NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE _sync_uid_alias ADD COLUMN followed_at TEXT;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS _sync_uid_ref_alias (
  tbl     TEXT NOT NULL,
  old_uid TEXT NOT NULL,
  origin  TEXT NOT NULL,
  new_uid TEXT NOT NULL,
  hlc     TEXT NOT NULL,
  PRIMARY KEY (tbl, old_uid, origin)
) WITHOUT ROWID;
--> statement-breakpoint
INSERT INTO _sync_uid_ref_alias (tbl, old_uid, origin, new_uid, hlc)
SELECT tbl, old_uid, origin, new_uid, hlc FROM _sync_uid_alias WHERE new_uid <> old_uid
ON CONFLICT (tbl, old_uid, origin) DO NOTHING;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS _sync_authored (
  tbl     TEXT NOT NULL,
  uid     TEXT NOT NULL,
  bfp     TEXT NOT NULL,
  replica TEXT NOT NULL,
  PRIMARY KEY (tbl, uid, bfp)
) WITHOUT ROWID;
--> statement-breakpoint
INSERT INTO _sync_authored (tbl, uid, bfp, replica)
SELECT o.tbl, o.uid, json_extract(o.body, '$.bfp'), t.replica
  FROM _sync_op o JOIN _sync_txn t ON t.txn = o.txn
 WHERE o.o = 'I' AND json_extract(o.body, '$.bfp') IS NOT NULL
ON CONFLICT (tbl, uid, bfp) DO NOTHING;
