-- T12984 (S3a) — the sealer's outbox and row metadata. Journal spec
-- t12342-t12343-journal-design §1.6, §2.5, §2.6, §4.3.
--
-- _sync_txn / _sync_op: sealed transactions and their ops, in local commit
-- order. `local_seq` is this replica's transaction counter; `txn` is
-- `<replica>:<local_seq>` (§2.6). The counter is persisted in
-- _sync_meta ('sealer.local_seq') and only ever rises, so a txn id is never
-- reused after old rows are collected. `state`: sealed -> segmented when a
-- persisted segment carries the transaction (S4); `inherited` for rows a
-- copied store carries from its original replica (§1.5); `folded` for
-- transactions at or below a stream's genesis cut (§2.11 §10). `unframed`
-- marks a singleton sealed from a capture with no validated frame (ruling (c)).
--
-- _sync_row_meta: per-row replication metadata (§1.6). Local-only; travels
-- inside checkpoint bundles (shash stripped). `bfp` is a minted row's
-- birth_fp, kept across a delete or re-key so every op carries it (T13030). `_sync_row_meta_tomb` indexes
-- FULL tombstones only (version > 0), the ones GC scans by HLC; a compacted
-- minimal tombstone (version 0, §1.7) is found by its key and needs no index
-- entry, which keeps it near the spec's ~190 B (T12986 measured ~155 B).
--
-- _sync_ledger: per sync-set table, the sealed row count (`live`) and the
-- rows a rebase holds unreplayed (`held`, §3.5 Rule 5). The ledger check
-- (§4.3) compares count(*) + held with it.
--
-- _sync_quarantine: captures the sealer could not read (a table that left
-- the sync set, a malformed image), moved out of the outbox so they never
-- stall it (T13036). A table with rows here is suspect: S3d's repair diff
-- re-derives it, and `cleo doctor` reports it.
--
-- Do not edit this file once applied: its hash is recorded per store.
-- (Unreleased until #1779 merges. It was edited during review; a dev or
-- Gate B scratch store that applied an earlier text fails with
-- E_SYNC_SCHEMA_HASH_DRIFT: reset it with dropSyncMachinery, or recreate it.)
CREATE TABLE IF NOT EXISTS _sync_txn (
  txn          TEXT PRIMARY KEY,
  local_seq    INTEGER NOT NULL UNIQUE,
  replica      TEXT NOT NULL,
  hlc          TEXT NOT NULL,
  scope        TEXT NOT NULL CHECK (scope IN ('project', 'global')),
  via          TEXT NOT NULL,
  kind         TEXT NOT NULL,
  actor        TEXT,
  frame        TEXT,
  unframed     INTEGER NOT NULL DEFAULT 0,
  op_count     INTEGER NOT NULL,
  state        TEXT NOT NULL DEFAULT 'sealed'
               CHECK (state IN ('sealed', 'segmented', 'inherited', 'folded')),
  sealed_at_ms INTEGER NOT NULL
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_txn_state ON _sync_txn (state, local_seq);
CREATE TABLE IF NOT EXISTS _sync_op (
  txn  TEXT NOT NULL,
  idx  INTEGER NOT NULL,
  tbl  TEXT NOT NULL,
  uid  TEXT NOT NULL,
  o    TEXT NOT NULL CHECK (o IN ('I', 'U', 'D', 'K')),
  hlc  TEXT NOT NULL,
  body TEXT NOT NULL,
  PRIMARY KEY (txn, idx)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_op_row ON _sync_op (tbl, uid);
CREATE TABLE IF NOT EXISTS _sync_row_meta (
  tbl         TEXT NOT NULL,
  uid         TEXT NOT NULL,
  hlc         TEXT NOT NULL,
  fhlc        TEXT,
  origin      TEXT NOT NULL,
  actor       TEXT,
  version     INTEGER NOT NULL,
  deleted     INTEGER NOT NULL DEFAULT 0,
  key_json    TEXT,
  sent        INTEGER NOT NULL DEFAULT 0,
  fk_excluded INTEGER NOT NULL DEFAULT 0,
  held        INTEGER NOT NULL DEFAULT 0,
  chash       TEXT,
  shash       TEXT,
  bfp         TEXT,
  PRIMARY KEY (tbl, uid)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_row_meta_tomb ON _sync_row_meta (hlc) WHERE deleted = 1 AND version > 0;
CREATE TABLE IF NOT EXISTS _sync_ledger (
  tbl  TEXT PRIMARY KEY,
  live INTEGER NOT NULL,
  held INTEGER NOT NULL DEFAULT 0
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS _sync_quarantine (
  seq               INTEGER PRIMARY KEY,
  tbl               TEXT NOT NULL,
  op                TEXT NOT NULL,
  rk                TEXT NOT NULL,
  uid               TEXT,
  img               TEXT NOT NULL,
  at_ms             INTEGER NOT NULL,
  frame             TEXT,
  reason            TEXT NOT NULL,
  quarantined_at_ms INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS _sync_quarantine_tbl ON _sync_quarantine (tbl);
