-- T12984 (S3a) — the sealer's outbox and row metadata. Journal spec
-- t12342-t12343-journal-design §1.6, §2.5, §2.6, §4.3.
--
-- _sync_txn / _sync_op: sealed transactions and their ops, in local commit
-- order. `local_seq` is this replica's transaction counter; `txn` is
-- `<replica>:<local_seq>` (§2.6). `state` moves sealed -> segmented when a
-- persisted segment carries the transaction (S4). `unframed` marks a
-- singleton sealed from a capture with no validated frame (ruling (c)).
--
-- _sync_row_meta: per-row replication metadata (§1.6). Local-only; travels
-- inside checkpoint bundles (shash stripped).
--
-- _sync_ledger: per sync-set table, the sealed row count (`live`) and the
-- rows a rebase holds unreplayed (`held`, §3.5 Rule 5). The ledger check
-- (§4.3) compares count(*) + held with it.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_txn (
  txn          TEXT PRIMARY KEY,
  local_seq    INTEGER NOT NULL UNIQUE,
  replica      TEXT NOT NULL,
  hlc          TEXT NOT NULL,
  scope        TEXT NOT NULL CHECK (scope IN ('project', 'global')),
  via          TEXT NOT NULL,
  kind         TEXT NOT NULL,
  actor        TEXT,
  frame        TEXT,
  unframed     INTEGER NOT NULL DEFAULT 0,
  op_count     INTEGER NOT NULL,
  state        TEXT NOT NULL DEFAULT 'sealed' CHECK (state IN ('sealed', 'segmented')),
  sealed_at_ms INTEGER NOT NULL
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_txn_state ON _sync_txn (state, local_seq);
CREATE TABLE IF NOT EXISTS _sync_op (
  txn  TEXT NOT NULL,
  idx  INTEGER NOT NULL,
  tbl  TEXT NOT NULL,
  uid  TEXT NOT NULL,
  o    TEXT NOT NULL CHECK (o IN ('I', 'U', 'D', 'K')),
  hlc  TEXT NOT NULL,
  body TEXT NOT NULL,
  PRIMARY KEY (txn, idx)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_op_row ON _sync_op (tbl, uid);
CREATE TABLE IF NOT EXISTS _sync_row_meta (
  tbl         TEXT NOT NULL,
  uid         TEXT NOT NULL,
  hlc         TEXT NOT NULL,
  fhlc        TEXT,
  origin      TEXT NOT NULL,
  actor       TEXT,
  version     INTEGER NOT NULL,
  deleted     INTEGER NOT NULL DEFAULT 0,
  key_json    TEXT,
  sent        INTEGER NOT NULL DEFAULT 0,
  fk_excluded INTEGER NOT NULL DEFAULT 0,
  held        INTEGER NOT NULL DEFAULT 0,
  chash       TEXT,
  shash       TEXT,
  PRIMARY KEY (tbl, uid)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_row_meta_tomb ON _sync_row_meta (deleted, hlc) WHERE deleted = 1;
CREATE TABLE IF NOT EXISTS _sync_ledger (
  tbl  TEXT PRIMARY KEY,
  live INTEGER NOT NULL,
  held INTEGER NOT NULL DEFAULT 0
) WITHOUT ROWID;
