-- T12343 S5-1 (journal spec §3.1 "Receive") — where a store's pull stands.
--
-- _sync_cursor: per stream, the PullCursor the journal client verifies the
-- next page against (the last applied stream seq, and per replica its pinned
-- device and last replicaSeq). It is advanced in the SAME local transaction
-- that stages the segments it covers (§3.1 step 3), so a crash re-pulls
-- nothing twice and loses nothing.
--
-- _sync_seen_txn: every transaction id this store has staged from a stream.
-- A transaction re-delivered under another segment (a replayed or re-sealed
-- segment, a retired replica's late segment carrying a txn already seen) is
-- skipped, never staged twice: a counter delta ($inc) applied twice would
-- double (T12343 S5-1).
--
-- Local-only.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_cursor (
  stream      TEXT PRIMARY KEY,
  cursor_json TEXT NOT NULL,
  updated_at  TEXT NOT NULL
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS _sync_seen_txn (
  stream TEXT NOT NULL,
  txn    TEXT NOT NULL,
  seq    INTEGER NOT NULL,
  PRIMARY KEY (stream, txn)
) WITHOUT ROWID;
