// @generated — DO NOT EDIT. Source: providers/hook-mappings.json
// Generated by scripts/generate-hook-types.ts

import type { ProviderHookProfile } from './types.js';

/**
 * All hook event categories (8 total).
 * @public
 */
export const HOOK_CATEGORIES = [
  'agent',
  'context',
  'memory',
  'pipeline',
  'prompt',
  'session',
  'task',
  'tool',
] as const;

/** Union type of valid hook category strings. */
export type HookCategory = (typeof HOOK_CATEGORIES)[number];

/**
 * Event source types: domain, provider.
 * @public
 */
export const EVENT_SOURCES = ['domain', 'provider'] as const;

/** Union type of valid event source types. */
export type EventSource = (typeof EVENT_SOURCES)[number];

/**
 * All canonical hook events (31 total: 16 provider, 15 domain).
 *
 * This replaces the previously hardcoded tuple in types.ts.
 * Single source of truth: providers/hook-mappings.json
 * @public
 */
export const CANONICAL_HOOK_EVENTS = [
  // Provider events
  'ConfigChange',
  'Notification',
  'PermissionRequest',
  'PostCompact',
  'PostModel',
  'PostToolUse',
  'PostToolUseFailure',
  'PreCompact',
  'PreModel',
  'PreToolUse',
  'PromptSubmit',
  'ResponseComplete',
  'SessionEnd',
  'SessionStart',
  'SubagentStart',
  'SubagentStop',
  // Domain events
  'ApprovalExpired',
  'ApprovalGranted',
  'ApprovalRequested',
  'MemoryDecisionStored',
  'MemoryLearningStored',
  'MemoryObserved',
  'MemoryPatternStored',
  'PipelineManifestAppended',
  'PipelineStageCompleted',
  'SessionEnded',
  'SessionStarted',
  'TaskBlocked',
  'TaskCompleted',
  'TaskCreated',
  'TaskStarted',
] as const;

/** Union type of all canonical hook event names. */
export type CanonicalHookEvent = (typeof CANONICAL_HOOK_EVENTS)[number];

/** Provider-sourced events only (original 16 CAAMP events). */
export const PROVIDER_HOOK_EVENTS = [
  'ConfigChange',
  'Notification',
  'PermissionRequest',
  'PostCompact',
  'PostModel',
  'PostToolUse',
  'PostToolUseFailure',
  'PreCompact',
  'PreModel',
  'PreToolUse',
  'PromptSubmit',
  'ResponseComplete',
  'SessionEnd',
  'SessionStart',
  'SubagentStart',
  'SubagentStop',
] as const;

/** Domain-sourced events only (CLEO business events). */
export const DOMAIN_HOOK_EVENTS = [
  'ApprovalExpired',
  'ApprovalGranted',
  'ApprovalRequested',
  'MemoryDecisionStored',
  'MemoryLearningStored',
  'MemoryObserved',
  'MemoryPatternStored',
  'PipelineManifestAppended',
  'PipelineStageCompleted',
  'SessionEnded',
  'SessionStarted',
  'TaskBlocked',
  'TaskCompleted',
  'TaskCreated',
  'TaskStarted',
] as const;

/** Metadata for each canonical event, derived from hook-mappings.json. */
export const EVENT_METADATA: Record<
  CanonicalHookEvent,
  {
    category: HookCategory;
    source: EventSource;
    canBlock: boolean;
    description: string;
  }
> = {
  ConfigChange: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'Configuration file changes during a session',
  },
  Notification: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'System notification or alert is emitted',
  },
  PermissionRequest: {
    category: 'tool',
    source: 'provider',
    canBlock: true,
    description: 'Permission dialog appears for a tool action',
  },
  PostCompact: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'After context window compaction completes',
  },
  PostModel: {
    category: 'agent',
    source: 'provider',
    canBlock: false,
    description: 'After receiving an LLM response',
  },
  PostToolUse: {
    category: 'tool',
    source: 'provider',
    canBlock: false,
    description: 'After a tool call succeeds',
  },
  PostToolUseFailure: {
    category: 'tool',
    source: 'provider',
    canBlock: false,
    description: 'After a tool call fails or times out',
  },
  PreCompact: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'Before context window compaction',
  },
  PreModel: {
    category: 'agent',
    source: 'provider',
    canBlock: true,
    description: 'Before sending a request to the LLM',
  },
  PreToolUse: {
    category: 'tool',
    source: 'provider',
    canBlock: true,
    description: 'Before a tool call executes (can block/modify)',
  },
  PromptSubmit: {
    category: 'prompt',
    source: 'provider',
    canBlock: true,
    description: 'User submits a prompt, before agent processes it',
  },
  ResponseComplete: {
    category: 'prompt',
    source: 'provider',
    canBlock: false,
    description: 'Agent finishes responding to a turn',
  },
  SessionEnd: {
    category: 'session',
    source: 'provider',
    canBlock: false,
    description: 'Session terminates or exits',
  },
  SessionStart: {
    category: 'session',
    source: 'provider',
    canBlock: false,
    description: 'Session begins, resumes, or is cleared',
  },
  SubagentStart: {
    category: 'agent',
    source: 'provider',
    canBlock: true,
    description: 'A subagent is spawned',
  },
  SubagentStop: {
    category: 'agent',
    source: 'provider',
    canBlock: false,
    description: 'A subagent finishes execution',
  },
  ApprovalExpired: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A workflow approval token has expired without response',
  },
  ApprovalGranted: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A workflow approval has been granted via /approve token',
  },
  ApprovalRequested: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A workflow approval gate has fired, awaiting human approval',
  },
  MemoryDecisionStored: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'A decision has been stored via memory.decision.store',
  },
  MemoryLearningStored: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'A learning has been stored via memory.learning.store',
  },
  MemoryObserved: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'An observation has been recorded to brain.db via memory.observe',
  },
  MemoryPatternStored: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'A pattern has been stored via memory.pattern.store',
  },
  PipelineManifestAppended: {
    category: 'pipeline',
    source: 'domain',
    canBlock: false,
    description:
      'A manifest entry has been appended to `pipeline_manifest` (`SQLite` table per ADR-027)',
  },
  PipelineStageCompleted: {
    category: 'pipeline',
    source: 'domain',
    canBlock: false,
    description: 'A LOOM lifecycle gate has passed validation',
  },
  SessionEnded: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO session has ended via session.end',
  },
  SessionStarted: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO session has been started via session.start',
  },
  TaskBlocked: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been blocked',
  },
  TaskCompleted: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been marked complete via tasks.complete',
  },
  TaskCreated: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been created via tasks.add',
  },
  TaskStarted: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been started via tasks.start',
  },
} as const;

/** Generated capability registry version and review date. */
export const HOOK_REGISTRY_EVIDENCE = { version: '2.0.0', lastUpdated: '2026-10-10' };

/** Complete fallback profiles generated from the registry. */
export const GENERATED_PROVIDER_HOOK_PROFILES: Record<string, ProviderHookProfile> = {
  'claude-code': {
    hookSystem: 'config',
    hookConfigPath: '$HOME/.claude/settings.json',
    hookFormat: 'json',
    handlerTypes: ['command', 'http', 'prompt', 'agent'],
    experimental: false,
    projectDelivery: {
      configPath: '.claude/settings.local.json',
      timeoutUnit: 'seconds',
      documentedVersions: ['2.1.296'],
      verifiedVersions: [],
      documentation: 'https://code.claude.com/docs/en/hooks',
      reviewedAt: '2026-10-10',
      trust: 'native-unverified',
    },
    mappings: {
      SessionStart: {
        nativeName: 'SessionStart',
        supported: true,
      },
      SessionEnd: {
        nativeName: 'SessionEnd',
        supported: true,
      },
      PromptSubmit: {
        nativeName: 'UserPromptSubmit',
        supported: true,
      },
      ResponseComplete: {
        nativeName: 'Stop',
        supported: true,
      },
      PreToolUse: {
        nativeName: 'PreToolUse',
        supported: true,
      },
      PostToolUse: {
        nativeName: 'PostToolUse',
        supported: true,
      },
      PostToolUseFailure: {
        nativeName: 'PostToolUseFailure',
        supported: true,
      },
      PermissionRequest: {
        nativeName: 'PermissionRequest',
        supported: true,
      },
      SubagentStart: {
        nativeName: 'SubagentStart',
        supported: true,
      },
      SubagentStop: {
        nativeName: 'SubagentStop',
        supported: true,
      },
      PreModel: {
        nativeName: null,
        supported: false,
      },
      PostModel: {
        nativeName: null,
        supported: false,
      },
      PreCompact: {
        nativeName: 'PreCompact',
        supported: true,
      },
      PostCompact: {
        nativeName: 'PostCompact',
        supported: true,
      },
      Notification: {
        nativeName: 'Notification',
        supported: true,
      },
      ConfigChange: {
        nativeName: 'ConfigChange',
        supported: true,
      },
    },
    providerOnlyEvents: [
      'StopFailure',
      'TeammateIdle',
      'TaskCompleted',
      'InstructionsLoaded',
      'WorktreeCreate',
      'WorktreeRemove',
      'Elicitation',
      'ElicitationResult',
    ],
  },
  cursor: {
    hookSystem: 'config',
    hookConfigPath: '.cursor/hooks.json',
    hookFormat: 'json',
    handlerTypes: ['command', 'prompt'],
    experimental: true,
    mappings: {
      SessionStart: {
        nativeName: 'sessionStart',
        supported: true,
      },
      SessionEnd: {
        nativeName: 'sessionEnd',
        supported: true,
      },
      PromptSubmit: {
        nativeName: 'beforeSubmitPrompt',
        supported: true,
      },
      ResponseComplete: {
        nativeName: 'stop',
        supported: true,
      },
      PreToolUse: {
        nativeName: 'preToolUse',
        supported: true,
      },
      PostToolUse: {
        nativeName: 'postToolUse',
        supported: true,
      },
      PostToolUseFailure: {
        nativeName: 'postToolUseFailure',
        supported: true,
      },
      PermissionRequest: {
        nativeName: null,
        supported: false,
      },
      SubagentStart: {
        nativeName: 'subagentStart',
        supported: true,
      },
      SubagentStop: {
        nativeName: 'subagentStop',
        supported: true,
      },
      PreModel: {
        nativeName: null,
        supported: false,
      },
      PostModel: {
        nativeName: null,
        supported: false,
      },
      PreCompact: {
        nativeName: 'preCompact',
        supported: true,
      },
      PostCompact: {
        nativeName: null,
        supported: false,
      },
      Notification: {
        nativeName: null,
        supported: false,
      },
      ConfigChange: {
        nativeName: null,
        supported: false,
      },
    },
    providerOnlyEvents: [
      'beforeShellExecution',
      'afterShellExecution',
      'beforeMCPExecution',
      'afterMCPExecution',
      'beforeReadFile',
      'afterFileEdit',
      'afterAgentResponse',
      'afterAgentThought',
      'beforeTabFileRead',
      'afterTabFileEdit',
    ],
  },
  'gemini-cli': {
    hookSystem: 'config',
    hookConfigPath: '$HOME/.gemini/settings.json',
    hookFormat: 'json',
    handlerTypes: ['command'],
    experimental: false,
    mappings: {
      SessionStart: {
        nativeName: 'SessionStart',
        supported: true,
      },
      SessionEnd: {
        nativeName: 'SessionEnd',
        supported: true,
      },
      PromptSubmit: {
        nativeName: 'BeforeAgent',
        supported: true,
      },
      ResponseComplete: {
        nativeName: 'AfterAgent',
        supported: true,
      },
      PreToolUse: {
        nativeName: 'BeforeTool',
        supported: true,
      },
      PostToolUse: {
        nativeName: 'AfterTool',
        supported: true,
      },
      PostToolUseFailure: {
        nativeName: null,
        supported: false,
      },
      PermissionRequest: {
        nativeName: null,
        supported: false,
      },
      SubagentStart: {
        nativeName: null,
        supported: false,
      },
      SubagentStop: {
        nativeName: null,
        supported: false,
      },
      PreModel: {
        nativeName: 'BeforeModel',
        supported: true,
      },
      PostModel: {
        nativeName: 'AfterModel',
        supported: true,
      },
      PreCompact: {
        nativeName: 'PreCompress',
        supported: true,
      },
      PostCompact: {
        nativeName: null,
        supported: false,
      },
      Notification: {
        nativeName: 'Notification',
        supported: true,
      },
      ConfigChange: {
        nativeName: null,
        supported: false,
      },
    },
    providerOnlyEvents: ['BeforeToolSelection'],
  },
  codex: {
    hookSystem: 'config',
    hookConfigPath: '.codex/hooks.json',
    hookFormat: 'json',
    handlerTypes: ['command'],
    experimental: true,
    projectDelivery: {
      configPath: '.codex/hooks.json',
      timeoutUnit: 'seconds',
      documentedVersions: ['0.162.1'],
      verifiedVersions: [],
      documentation: 'https://developers.openai.com/codex/hooks',
      reviewedAt: '2026-10-10',
      trust: 'native-unverified',
    },
    mappings: {
      SessionStart: {
        nativeName: 'SessionStart',
        supported: true,
      },
      SessionEnd: {
        nativeName: null,
        supported: false,
      },
      PromptSubmit: {
        nativeName: 'UserPromptSubmit',
        supported: true,
      },
      ResponseComplete: {
        nativeName: 'Stop',
        supported: true,
      },
      PreToolUse: {
        nativeName: 'PreToolUse',
        supported: true,
        notes: 'Documented by OpenAI; live version certification is separate from installation.',
      },
      PostToolUse: {
        nativeName: null,
        supported: false,
      },
      PostToolUseFailure: {
        nativeName: null,
        supported: false,
      },
      PermissionRequest: {
        nativeName: null,
        supported: false,
      },
      SubagentStart: {
        nativeName: null,
        supported: false,
      },
      SubagentStop: {
        nativeName: null,
        supported: false,
      },
      PreModel: {
        nativeName: null,
        supported: false,
      },
      PostModel: {
        nativeName: null,
        supported: false,
      },
      PreCompact: {
        nativeName: null,
        supported: false,
      },
      PostCompact: {
        nativeName: null,
        supported: false,
      },
      Notification: {
        nativeName: null,
        supported: false,
      },
      ConfigChange: {
        nativeName: null,
        supported: false,
      },
    },
    providerOnlyEvents: [],
  },
  opencode: {
    hookSystem: 'plugin',
    hookConfigPath: '.opencode/plugins/',
    hookFormat: 'javascript',
    handlerTypes: ['plugin'],
    experimental: false,
    projectDelivery: {
      configPath: '.opencode/plugins/cleo-project-hooks.js',
      timeoutUnit: 'milliseconds',
      documentedVersions: ['2.0.26'],
      verifiedVersions: [],
      documentation: 'https://opencode.ai/docs/plugins/',
      reviewedAt: '2026-10-10',
      trust: 'native-unverified',
    },
    mappings: {
      SessionStart: {
        nativeName: 'event:session.created',
        supported: true,
        notes: 'Via bus event subscriber',
      },
      SessionEnd: {
        nativeName: 'event:session.deleted',
        supported: true,
        notes: 'Via bus event subscriber',
      },
      PromptSubmit: {
        nativeName: 'chat.message',
        supported: true,
      },
      ResponseComplete: {
        nativeName: 'event:session.idle',
        supported: true,
        notes: 'Via bus event subscriber',
      },
      PreToolUse: {
        nativeName: 'tool.execute.before',
        supported: true,
      },
      PostToolUse: {
        nativeName: 'tool.execute.after',
        supported: true,
      },
      PostToolUseFailure: {
        nativeName: null,
        supported: false,
      },
      PermissionRequest: {
        nativeName: 'permission.ask',
        supported: true,
      },
      SubagentStart: {
        nativeName: null,
        supported: false,
      },
      SubagentStop: {
        nativeName: null,
        supported: false,
      },
      PreModel: {
        nativeName: 'chat.params',
        supported: true,
        notes: 'Modify LLM params before request',
      },
      PostModel: {
        nativeName: null,
        supported: false,
      },
      PreCompact: {
        nativeName: 'experimental.session.compacting',
        supported: true,
      },
      PostCompact: {
        nativeName: 'event:session.compacted',
        supported: true,
        notes: 'Via bus event subscriber',
      },
      Notification: {
        nativeName: null,
        supported: false,
      },
      ConfigChange: {
        nativeName: null,
        supported: false,
      },
    },
    providerOnlyEvents: [
      'chat.headers',
      'shell.env',
      'tool.definition',
      'command.execute.before',
      'experimental.chat.messages.transform',
      'experimental.chat.system.transform',
      'experimental.text.complete',
    ],
  },
  kimi: {
    hookSystem: 'none',
    hookConfigPath: null,
    hookFormat: null,
    handlerTypes: [],
    experimental: false,
    projectDelivery: {
      configPath: null,
      documentedVersions: [],
      verifiedVersions: [],
      documentation: 'https://kimi-cli.com/en/customization/hooks.html',
      reviewedAt: '2026-10-10',
      trust: 'native-unverified',
    },
    mappings: {
      SessionStart: {
        nativeName: null,
        supported: false,
      },
      SessionEnd: {
        nativeName: null,
        supported: false,
      },
      PromptSubmit: {
        nativeName: null,
        supported: false,
      },
      ResponseComplete: {
        nativeName: null,
        supported: false,
      },
      PreToolUse: {
        nativeName: null,
        supported: false,
      },
      PostToolUse: {
        nativeName: null,
        supported: false,
      },
      PostToolUseFailure: {
        nativeName: null,
        supported: false,
      },
      PermissionRequest: {
        nativeName: null,
        supported: false,
      },
      SubagentStart: {
        nativeName: null,
        supported: false,
      },
      SubagentStop: {
        nativeName: null,
        supported: false,
      },
      PreModel: {
        nativeName: null,
        supported: false,
      },
      PostModel: {
        nativeName: null,
        supported: false,
      },
      PreCompact: {
        nativeName: null,
        supported: false,
      },
      PostCompact: {
        nativeName: null,
        supported: false,
      },
      Notification: {
        nativeName: null,
        supported: false,
      },
      ConfigChange: {
        nativeName: null,
        supported: false,
      },
    },
    providerOnlyEvents: [],
  },
  pi: {
    hookSystem: 'extension',
    hookConfigPath: '$PI_CODING_AGENT_DIR/extensions/',
    hookFormat: 'typescript',
    handlerTypes: ['extension'],
    experimental: false,
    notes:
      "Pi is CAAMP's first-class primary harness (ADR-035). Events use snake_case. Extensions live at ~/.pi/agent/extensions/ (global) or <projectDir>/.pi/extensions/ (project).",
    nativeEventCatalog: 'pi',
    mappings: {
      SessionStart: {
        nativeName: 'session_start',
        supported: true,
      },
      SessionEnd: {
        nativeName: 'session_shutdown',
        supported: true,
      },
      PromptSubmit: {
        nativeName: 'input',
        supported: true,
      },
      ResponseComplete: {
        nativeName: null,
        supported: false,
      },
      PreToolUse: {
        nativeName: 'tool_call',
        supported: true,
      },
      PostToolUse: {
        nativeName: 'tool_result',
        supported: true,
      },
      PostToolUseFailure: {
        nativeName: null,
        supported: false,
      },
      PermissionRequest: {
        nativeName: null,
        supported: false,
      },
      SubagentStart: {
        nativeName: 'before_agent_start',
        supported: true,
      },
      SubagentStop: {
        nativeName: 'agent_end',
        supported: true,
      },
      PreModel: {
        nativeName: 'before_provider_request',
        supported: true,
      },
      PostModel: {
        nativeName: null,
        supported: false,
      },
      PreCompact: {
        nativeName: 'context',
        supported: true,
        notes: "Pi's context assembly event is the closest proxy for pre-compaction",
      },
      PostCompact: {
        nativeName: null,
        supported: false,
      },
      Notification: {
        nativeName: 'turn_end',
        supported: true,
        notes:
          'Pi emits turn_end when the assistant turn completes, which is the best proxy for a notification event',
      },
      ConfigChange: {
        nativeName: null,
        supported: false,
      },
    },
    providerOnlyEvents: [
      'session_switch',
      'session_fork',
      'agent_start',
      'turn_start',
      'message_start',
      'message_update',
      'message_end',
      'tool_execution_start',
      'tool_execution_end',
      'user_bash',
      'model_select',
      'resources_discover',
    ],
  },
  antigravity: {
    hookSystem: 'none',
    hookConfigPath: null,
    hookFormat: null,
    handlerTypes: [],
    experimental: false,
    mappings: {
      SessionStart: {
        nativeName: null,
        supported: false,
      },
      SessionEnd: {
        nativeName: null,
        supported: false,
      },
      PromptSubmit: {
        nativeName: null,
        supported: false,
      },
      ResponseComplete: {
        nativeName: null,
        supported: false,
      },
      PreToolUse: {
        nativeName: null,
        supported: false,
      },
      PostToolUse: {
        nativeName: null,
        supported: false,
      },
      PostToolUseFailure: {
        nativeName: null,
        supported: false,
      },
      PermissionRequest: {
        nativeName: null,
        supported: false,
      },
      SubagentStart: {
        nativeName: null,
        supported: false,
      },
      SubagentStop: {
        nativeName: null,
        supported: false,
      },
      PreModel: {
        nativeName: null,
        supported: false,
      },
      PostModel: {
        nativeName: null,
        supported: false,
      },
      PreCompact: {
        nativeName: null,
        supported: false,
      },
      PostCompact: {
        nativeName: null,
        supported: false,
      },
      Notification: {
        nativeName: null,
        supported: false,
      },
      ConfigChange: {
        nativeName: null,
        supported: false,
      },
    },
    providerOnlyEvents: [],
  },
};

/** Provider native-to-canonical maps generated from the same registry. */
export const PROVIDER_NATIVE_EVENT_MAPS: Record<string, Record<string, string>> = {
  'claude-code': {
    SessionStart: 'SessionStart',
    SessionEnd: 'SessionEnd',
    UserPromptSubmit: 'PromptSubmit',
    Stop: 'ResponseComplete',
    PreToolUse: 'PreToolUse',
    PostToolUse: 'PostToolUse',
    PostToolUseFailure: 'PostToolUseFailure',
    PermissionRequest: 'PermissionRequest',
    SubagentStart: 'SubagentStart',
    SubagentStop: 'SubagentStop',
    PreCompact: 'PreCompact',
    PostCompact: 'PostCompact',
    Notification: 'Notification',
    ConfigChange: 'ConfigChange',
  },
  cursor: {
    sessionStart: 'SessionStart',
    sessionEnd: 'SessionEnd',
    beforeSubmitPrompt: 'PromptSubmit',
    stop: 'ResponseComplete',
    preToolUse: 'PreToolUse',
    postToolUse: 'PostToolUse',
    postToolUseFailure: 'PostToolUseFailure',
    subagentStart: 'SubagentStart',
    subagentStop: 'SubagentStop',
    preCompact: 'PreCompact',
  },
  'gemini-cli': {
    SessionStart: 'SessionStart',
    SessionEnd: 'SessionEnd',
    BeforeAgent: 'PromptSubmit',
    AfterAgent: 'ResponseComplete',
    BeforeTool: 'PreToolUse',
    AfterTool: 'PostToolUse',
    BeforeModel: 'PreModel',
    AfterModel: 'PostModel',
    PreCompress: 'PreCompact',
    Notification: 'Notification',
  },
  codex: {
    SessionStart: 'SessionStart',
    UserPromptSubmit: 'PromptSubmit',
    Stop: 'ResponseComplete',
    PreToolUse: 'PreToolUse',
  },
  opencode: {
    'event:session.created': 'SessionStart',
    'event:session.deleted': 'SessionEnd',
    'chat.message': 'PromptSubmit',
    'event:session.idle': 'ResponseComplete',
    'tool.execute.before': 'PreToolUse',
    'tool.execute.after': 'PostToolUse',
    'permission.ask': 'PermissionRequest',
    'chat.params': 'PreModel',
    'experimental.session.compacting': 'PreCompact',
    'event:session.compacted': 'PostCompact',
  },
  kimi: {},
  pi: {
    session_start: 'SessionStart',
    session_shutdown: 'SessionEnd',
    input: 'PromptSubmit',
    tool_call: 'PreToolUse',
    tool_result: 'PostToolUse',
    before_agent_start: 'SubagentStart',
    agent_end: 'SubagentStop',
    before_provider_request: 'PreModel',
    context: 'PreCompact',
    turn_end: 'Notification',
    tool_execution_start: 'PreToolUse',
    tool_execution_end: 'PostToolUse',
  },
  antigravity: {},
};
