// @generated — DO NOT EDIT. Source: providers/hook-mappings.json
// Generated by scripts/generate-hook-types.ts

/**
 * All hook event categories (8 total).
 * @public
 */
export const HOOK_CATEGORIES = [
  'agent',
  'context',
  'memory',
  'pipeline',
  'prompt',
  'session',
  'task',
  'tool',
] as const;

/** Union type of valid hook category strings. */
export type HookCategory = (typeof HOOK_CATEGORIES)[number];

/**
 * Event source types: domain, provider.
 * @public
 */
export const EVENT_SOURCES = ['domain', 'provider'] as const;

/** Union type of valid event source types. */
export type EventSource = (typeof EVENT_SOURCES)[number];

/**
 * All canonical hook events (31 total: 16 provider, 15 domain).
 *
 * This replaces the previously hardcoded tuple in types.ts.
 * Single source of truth: providers/hook-mappings.json
 * @public
 */
export const CANONICAL_HOOK_EVENTS = [
  // Provider events
  'ConfigChange',
  'Notification',
  'PermissionRequest',
  'PostCompact',
  'PostModel',
  'PostToolUse',
  'PostToolUseFailure',
  'PreCompact',
  'PreModel',
  'PreToolUse',
  'PromptSubmit',
  'ResponseComplete',
  'SessionEnd',
  'SessionStart',
  'SubagentStart',
  'SubagentStop',
  // Domain events
  'ApprovalExpired',
  'ApprovalGranted',
  'ApprovalRequested',
  'MemoryDecisionStored',
  'MemoryLearningStored',
  'MemoryObserved',
  'MemoryPatternStored',
  'PipelineManifestAppended',
  'PipelineStageCompleted',
  'SessionEnded',
  'SessionStarted',
  'TaskBlocked',
  'TaskCompleted',
  'TaskCreated',
  'TaskStarted',
] as const;

/** Union type of all canonical hook event names. */
export type CanonicalHookEvent = (typeof CANONICAL_HOOK_EVENTS)[number];

/** Provider-sourced events only (original 16 CAAMP events). */
export const PROVIDER_HOOK_EVENTS = [
  'ConfigChange',
  'Notification',
  'PermissionRequest',
  'PostCompact',
  'PostModel',
  'PostToolUse',
  'PostToolUseFailure',
  'PreCompact',
  'PreModel',
  'PreToolUse',
  'PromptSubmit',
  'ResponseComplete',
  'SessionEnd',
  'SessionStart',
  'SubagentStart',
  'SubagentStop',
] as const;

/** Domain-sourced events only (CLEO business events). */
export const DOMAIN_HOOK_EVENTS = [
  'ApprovalExpired',
  'ApprovalGranted',
  'ApprovalRequested',
  'MemoryDecisionStored',
  'MemoryLearningStored',
  'MemoryObserved',
  'MemoryPatternStored',
  'PipelineManifestAppended',
  'PipelineStageCompleted',
  'SessionEnded',
  'SessionStarted',
  'TaskBlocked',
  'TaskCompleted',
  'TaskCreated',
  'TaskStarted',
] as const;

/** Metadata for each canonical event, derived from hook-mappings.json. */
export const EVENT_METADATA: Record<
  CanonicalHookEvent,
  {
    category: HookCategory;
    source: EventSource;
    canBlock: boolean;
    description: string;
  }
> = {
  ConfigChange: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'Configuration file changes during a session',
  },
  Notification: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'System notification or alert is emitted',
  },
  PermissionRequest: {
    category: 'tool',
    source: 'provider',
    canBlock: true,
    description: 'Permission dialog appears for a tool action',
  },
  PostCompact: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'After context window compaction completes',
  },
  PostModel: {
    category: 'agent',
    source: 'provider',
    canBlock: false,
    description: 'After receiving an LLM response',
  },
  PostToolUse: {
    category: 'tool',
    source: 'provider',
    canBlock: false,
    description: 'After a tool call succeeds',
  },
  PostToolUseFailure: {
    category: 'tool',
    source: 'provider',
    canBlock: false,
    description: 'After a tool call fails or times out',
  },
  PreCompact: {
    category: 'context',
    source: 'provider',
    canBlock: false,
    description: 'Before context window compaction',
  },
  PreModel: {
    category: 'agent',
    source: 'provider',
    canBlock: true,
    description: 'Before sending a request to the LLM',
  },
  PreToolUse: {
    category: 'tool',
    source: 'provider',
    canBlock: true,
    description: 'Before a tool call executes (can block/modify)',
  },
  PromptSubmit: {
    category: 'prompt',
    source: 'provider',
    canBlock: true,
    description: 'User submits a prompt, before agent processes it',
  },
  ResponseComplete: {
    category: 'prompt',
    source: 'provider',
    canBlock: false,
    description: 'Agent finishes responding to a turn',
  },
  SessionEnd: {
    category: 'session',
    source: 'provider',
    canBlock: false,
    description: 'Session terminates or exits',
  },
  SessionStart: {
    category: 'session',
    source: 'provider',
    canBlock: false,
    description: 'Session begins, resumes, or is cleared',
  },
  SubagentStart: {
    category: 'agent',
    source: 'provider',
    canBlock: true,
    description: 'A subagent is spawned',
  },
  SubagentStop: {
    category: 'agent',
    source: 'provider',
    canBlock: false,
    description: 'A subagent finishes execution',
  },
  ApprovalExpired: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A workflow approval token has expired without response',
  },
  ApprovalGranted: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A workflow approval has been granted via /approve token',
  },
  ApprovalRequested: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A workflow approval gate has fired, awaiting human approval',
  },
  MemoryDecisionStored: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'A decision has been stored via memory.decision.store',
  },
  MemoryLearningStored: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'A learning has been stored via memory.learning.store',
  },
  MemoryObserved: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'An observation has been recorded to brain.db via memory.observe',
  },
  MemoryPatternStored: {
    category: 'memory',
    source: 'domain',
    canBlock: false,
    description: 'A pattern has been stored via memory.pattern.store',
  },
  PipelineManifestAppended: {
    category: 'pipeline',
    source: 'domain',
    canBlock: false,
    description:
      'A manifest entry has been appended to pipeline_manifest (SQLite table per ADR-027)',
  },
  PipelineStageCompleted: {
    category: 'pipeline',
    source: 'domain',
    canBlock: false,
    description: 'A LOOM lifecycle gate has passed validation',
  },
  SessionEnded: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO session has ended via session.end',
  },
  SessionStarted: {
    category: 'session',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO session has been started via session.start',
  },
  TaskBlocked: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been blocked',
  },
  TaskCompleted: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been marked complete via tasks.complete',
  },
  TaskCreated: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been created via tasks.add',
  },
  TaskStarted: {
    category: 'task',
    source: 'domain',
    canBlock: false,
    description: 'A CLEO task has been started via tasks.start',
  },
} as const;
