-- T13193 (S5 rebase, journal spec §3.5 Rules 2-3) — what a scoped rebase
-- needs beyond the capture undo log.
--
-- _sync_row_undo: per sealed local op (txn, idx), the row's merge state just
-- before it (its _sync_row_meta row and its _sync_field_leave rows, as JSON;
-- NULL meta_json when the row had none). _sync_undo restores values; a rewind
-- must also restore the field HLCs, leaves and frontiers the op moved, or the
-- origin's merge state would disagree with every receiver's. Written by the
-- sealer only while undo is enabled; dropped with the transaction's undo when
-- its echo is sequenced. Local-only.
--
-- _sync_foreign_touch: the rows each applied foreign transaction touched, at
-- the capture position (sqlite_sequence of _sync_capture) when it applied.
-- The own-echo fast path: an own transaction is sequenced without a rebase
-- when no foreign touch at or after its own first capture hits its rows.
-- Holds only entries newer than the oldest unsequenced local transaction,
-- bounded by FOREIGN_TOUCH_MAX. Local-only.
--
-- _sync_sequenced: own transactions whose echo the stream has sequenced
-- (stream, seq). An unsequenced sealed local transaction is one with no row
-- here. Local-only.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_row_undo (
  txn       TEXT NOT NULL,
  idx       INTEGER NOT NULL,
  tbl       TEXT NOT NULL,
  uid       TEXT NOT NULL,
  meta_json TEXT,
  leave_json TEXT,
  PRIMARY KEY (txn, idx)
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS _sync_foreign_touch (
  tbl TEXT NOT NULL,
  uid TEXT NOT NULL,
  pos INTEGER NOT NULL,
  PRIMARY KEY (tbl, uid, pos)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS _sync_foreign_touch_pos ON _sync_foreign_touch (pos);
CREATE TABLE IF NOT EXISTS _sync_sequenced (
  txn    TEXT PRIMARY KEY,
  stream TEXT NOT NULL,
  seq    INTEGER NOT NULL,
  at     TEXT NOT NULL
) WITHOUT ROWID;
