/**
 * `cleo project link`: register the current project with Cleo Nexus and bind
 * the remote project to the local one.
 *
 * ## What is sent
 *
 * `POST /v1/projects` with `{ projectId, label }`, plus `initialKey` for a
 * new project:
 *
 * - `projectId` is the tracked, immutable `.cleo/project-id`
 *   (`readDeclaredProjectIdentity`), the key the server stores projects under,
 *   so the remote id IS the local id.
 * - `label` is the project's display name in plaintext
 *   ({@link getProjectDisplayName}), or `--label`. It must not look like a path.
 * - `initialKey` (onboarding B, T13101) is the project's first data key,
 *   wrapped by the account master key at version 1, which the server stores
 *   in the same transaction as the project. It is sent only when E3
 *   (`GET /v1/status?projectId=`) lists {@link NEXUS_FEATURE_PROJECT_INITIAL_KEY},
 *   names a full-profile device credential, and does not see the project yet.
 *   A re-link never sends a key. A project registered without one (by an
 *   older CLI, a server without the feature, or a device that could not
 *   unlock the account key) gets it from its first `cleo cloud push`
 *   (cleo-nexus #33).
 *
 * No filesystem path, git remote or directory layout is ever sent.
 *
 * ## Idempotency
 *
 * Registering the same id again answers 200 (201 on first registration) and
 * sets the server label to the one sent, so re-linking after a rename updates
 * the label. Linking twice is safe.
 *
 * ## Where the binding lives
 *
 * `<project>/.cleo/nexus-link.json`, keyed by API origin. It is machine-local:
 * `.cleo/.gitignore` denies everything not allow-listed, so the binding (which
 * names an account's organization) is never committed. It is not
 * `project-context.json`, which is tracked in git and regenerated by
 * `cleo upgrade`, and not the project `cleo.db`, so linking never opens or
 * migrates the task store. Each clone links itself, the same way each machine
 * signs itself in.
 *
 * @task T12712
 * @epic T12322
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { homedir, userInfo } from 'node:os';
import { join, resolve } from 'node:path';
import {
  NEXUS_FEATURE_PROJECT_INITIAL_KEY,
  type NexusProjectLink,
  type NexusProjectLinkResult,
  nexusCloudStatusSchema,
} from '@cleocode/contracts';
import type { InitialProjectKey } from '@cleocode/contracts/cloud';
import { readDeclaredProjectIdentity } from '@cleocode/paths';
import { z } from 'zod';
import { getCleoDirAbsolute, resolveOrCwd } from '../paths.js';
import { getProjectDisplayName } from '../project-info.js';
import { withLock } from '../store/file-utils.js';
import { Http, NexusError } from './http.js';
import { newProjectKey, wrapProjectKey } from './keys.js';
import { attachProjectReplica, type ProjectReplicaBinder } from './nexus-attach.js';
import {
  NexusAccountError,
  type NexusFlowOptions,
  requireNexusSession,
  resolveNexusApiUrl,
} from './nexus-auth.js';
import { FileNexusTokenStore } from './nexus-credentials.js';
import { isNexusDeviceEnabled, type NexusDeviceStore } from './nexus-device.js';
import { ensureNexusDeviceCredential, nexusApiErrorToAccountError } from './nexus-enrol.js';
import type { NexusVaultState } from './nexus-vault-state.js';
import { registerProject } from './projects.js';

/** File name of the binding, inside the project's `.cleo/` directory. */
export const NEXUS_LINK_FILE = 'nexus-link.json';

/** Longest label the server accepts (`RegisterProjectRequest.label`). */
export const NEXUS_LABEL_MAX = 120;

const linkSchema = z.looseObject({
  apiUrl: z.string(),
  localProjectId: z.string(),
  remoteProjectId: z.string(),
  organizationId: z.string(),
  label: z.string().nullable(),
  streamId: z.string(),
  linkedAt: z.string(),
  replicaId: z.string().nullish(),
  nexusDeviceId: z.string().nullish(),
  attachedAt: z.string().nullish(),
});

/**
 * The file envelope. Entries are kept as raw records and parsed one by one
 * ({@link mergeLinkEntry}), so an entry this version cannot read (written by
 * a newer CLI) is carried through unchanged instead of dropping the file.
 */
const linkFileSchema = z.looseObject({
  version: z.literal(1),
  links: z.record(z.string(), z.record(z.string(), z.json())),
});

/** A JSON value, as a link entry's raw fields hold them. */
type LinkJson = z.infer<ReturnType<typeof z.json>>;

/** One parsed entry as the contract type, or `null` when this version cannot read it. */
function toLink(raw: Record<string, LinkJson> | undefined): NexusProjectLink | null {
  if (raw === undefined) return null;
  const parsed = linkSchema.safeParse(raw);
  if (!parsed.success) return null;
  const e = parsed.data;
  return {
    apiUrl: e.apiUrl,
    localProjectId: e.localProjectId,
    remoteProjectId: e.remoteProjectId,
    organizationId: e.organizationId,
    label: e.label,
    streamId: e.streamId,
    linkedAt: e.linkedAt,
    ...(e.replicaId ? { replicaId: e.replicaId } : {}),
    ...(e.nexusDeviceId ? { nexusDeviceId: e.nexusDeviceId } : {}),
    ...(e.attachedAt ? { attachedAt: e.attachedAt } : {}),
  };
}

/**
 * The entry to store for this link: the new values over the old entry, so a
 * relink that attached nothing keeps the cached replica fields, and fields a
 * newer CLI wrote survive.
 */
function mergeLinkEntry(
  old: Record<string, LinkJson> | undefined,
  link: NexusProjectLink,
  clearReplica: boolean,
): Record<string, LinkJson> {
  const fresh: Record<string, LinkJson> = {
    apiUrl: link.apiUrl,
    localProjectId: link.localProjectId,
    remoteProjectId: link.remoteProjectId,
    organizationId: link.organizationId,
    label: link.label,
    streamId: link.streamId,
    linkedAt: link.linkedAt,
    ...(link.replicaId ? { replicaId: link.replicaId } : {}),
    ...(link.nexusDeviceId ? { nexusDeviceId: link.nexusDeviceId } : {}),
    ...(link.attachedAt ? { attachedAt: link.attachedAt } : {}),
  };
  // A device-mode attach that failed must not leave the old replica and
  // device ids looking current (review N1): they are cleared.
  const cleared: Record<string, LinkJson> = clearReplica
    ? { replicaId: null, nexusDeviceId: null, attachedAt: null }
    : {};
  return { ...(old ?? {}), ...cleared, ...fresh };
}

type NexusLinkFile = z.infer<typeof linkFileSchema>;

/** Options for {@link linkProjectToNexus}. */
export interface NexusLinkOptions extends NexusFlowOptions {
  /** Project root; defaults to the resolved current project. */
  projectRoot?: string;
  /** Label to register (`--label`); defaults to {@link getProjectDisplayName}. */
  label?: string;
  /** Device store (with device credentials); defaults to `<cleoHome>/nexus-device.json`. */
  deviceStore?: NexusDeviceStore;
  /** Replica binding (tests); defaults to the canonical project store. */
  replicaBinder?: ProjectReplicaBinder;
  /** CLEO version reported in presence; defaults to the installed one. */
  cliVersion?: string;
  /** `--rebind`: give this store a new replica id before attaching (see {@link attachProjectReplica}). */
  rebind?: boolean;
  /** Vault state (trust pins read while unlocking the account key); defaults to `<cleoHome>/nexus-vault.json`. */
  vaultState?: NexusVaultState;
}

/**
 * Path separators and their look-alikes: `/`, `\`, fullwidth ／ ＼, division
 * slash ∕, set minus ∖, fraction slash ⁄, big solidi ⧸ ⧹, small reverse
 * solidus ﹨. Plus C0/C1 control characters.
 */
const LABEL_FORBIDDEN =
  /[/\\\uFF0F\uFF3C\u2215\u2216\u2044\u29F8\u29F9\uFE68\u0000-\u001f\u007f-\u009f]/;

/** The OS account name, or `null` when the platform cannot say. */
function osUsername(): string | null {
  try {
    return userInfo().username || null;
  } catch {
    return null;
  }
}

/**
 * Validate a project label: 1-120 characters; no path separator or look-alike
 * slash, no drive letter (`C:`), no leading `~`, no control characters; and
 * not the OS username, which would leak the account name. A label is a name,
 * never a path.
 *
 * @param raw - Candidate label.
 * @returns The trimmed label.
 * @throws {NexusAccountError} `E_NEXUS_INVALID_LABEL`.
 */
export function validateNexusProjectLabel(raw: string): string {
  const label = raw.trim();
  const pathLike = LABEL_FORBIDDEN.test(label) || label.startsWith('~') || /^[A-Za-z]:/.test(label);
  if (!label || label.length > NEXUS_LABEL_MAX || pathLike) {
    throw new NexusAccountError(
      'E_NEXUS_INVALID_LABEL',
      `invalid project label "${label}": use 1-${NEXUS_LABEL_MAX} characters with no slash or backslash (or look-alike), drive letter or leading "~" (a name, not a path)`,
      'pass `--label <name>`',
    );
  }
  const username = osUsername();
  if (username !== null && label.toLowerCase() === username.toLowerCase()) {
    throw new NexusAccountError(
      'E_NEXUS_INVALID_LABEL',
      'the project label equals your OS username, which would reveal it to the server',
      'pass `--label <name>` with a different name',
    );
  }
  return label;
}

/**
 * The label to send: `--label`, else the project's display name. A project
 * rooted at the home directory has no meaningful name (its basename is the
 * account name), so it must be labelled explicitly.
 */
function resolveLinkLabel(projectRoot: string, explicit: string | undefined): string {
  if (explicit !== undefined) return validateNexusProjectLabel(explicit);
  if (resolve(projectRoot) === resolve(homedir())) {
    throw new NexusAccountError(
      'E_NEXUS_INVALID_LABEL',
      'this project is your home directory; its name would reveal your account name',
      'pass `--label <name>`',
    );
  }
  return validateNexusProjectLabel(getProjectDisplayName(projectRoot));
}

/**
 * Path of the binding file for a project.
 *
 * @param projectRoot - Project root.
 * @returns `<project>/.cleo/nexus-link.json`.
 */
export function nexusLinkPath(projectRoot: string): string {
  return join(getCleoDirAbsolute(projectRoot), NEXUS_LINK_FILE);
}

/** Read the binding file; missing or malformed reads as empty. */
function readLinkFile(path: string): NexusLinkFile {
  try {
    const parsed = linkFileSchema.safeParse(JSON.parse(readFileSync(path, 'utf-8')));
    if (parsed.success) return parsed.data;
  } catch {
    /* missing or unreadable */
  }
  return { version: 1, links: {} };
}

/**
 * The stored binding for a project and origin, if any.
 *
 * @param projectRoot - Project root.
 * @param apiUrl - API URL (any URL on the origin).
 * @returns The binding, or `null`.
 */
export function readNexusProjectLink(projectRoot: string, apiUrl: string): NexusProjectLink | null {
  return toLink(readLinkFile(nexusLinkPath(projectRoot)).links[new URL(apiUrl).origin]);
}

/** Map an API failure to a Nexus error; a 401 means the session expired. */
function toLinkError(err: unknown): Error {
  if (err instanceof NexusError) {
    if (err.status === 401) {
      return new NexusAccountError(
        'E_NEXUS_SESSION_EXPIRED',
        'the Nexus session expired or was revoked',
        'run `cleo login nexus` again',
      );
    }
    const remedy = typeof err.details?.['remedy'] === 'string' ? err.details['remedy'] : undefined;
    return new NexusAccountError('E_NEXUS_REQUEST_FAILED', err.message, remedy);
  }
  return err instanceof Error ? err : new Error(String(err));
}

/**
 * `POST /v1/projects`, retried once on 409 `project-id-taken` (contract
 * §4.0.4, N3): the same new project id was registered concurrently, so the
 * retry takes the existing-project path (200, or `project-other-account` when
 * another account won).
 */
async function registerProjectOnce(
  http: Http,
  req: Parameters<typeof registerProject>[1],
): Promise<Awaited<ReturnType<typeof registerProject>>> {
  try {
    return await registerProject(http, req);
  } catch (err) {
    if (
      err instanceof NexusError &&
      err.status === 409 &&
      err.details?.['reason'] === 'project-id-taken'
    ) {
      return registerProject(http, req);
    }
    throw err;
  }
}

/**
 * Whether a refusal of a registration that carried `initialKey` means the
 * key, not the project, was refused: 409 `keys-exist` (the project was
 * registered with a key since the E3 probe) or a credential without
 * `keys:write` (403). Either way the project is registered without it.
 */
function initialKeyRefused(err: unknown): boolean {
  if (!(err instanceof NexusError)) return false;
  if (err.status === 409) return err.details?.['reason'] === 'keys-exist';
  return (
    err.status === 403 &&
    err.details?.['reason'] === 'insufficient-scope' &&
    err.details?.['requiredScope'] === 'keys:write'
  );
}

/**
 * {@link registerProjectOnce}. When the server refuses the `initialKey` it
 * carried ({@link initialKeyRefused}), the registration is sent once more
 * without it, as a re-link: a project that already has a key never gets a
 * second one from link.
 */
async function registerLinkedProject(
  http: Http,
  req: Parameters<typeof registerProject>[1],
): Promise<Awaited<ReturnType<typeof registerProject>>> {
  try {
    return await registerProjectOnce(http, req);
  } catch (err) {
    if (req.initialKey === undefined || !initialKeyRefused(err)) throw err;
    const { initialKey: _refused, ...plain } = req;
    return registerProjectOnce(http, plain);
  }
}

/**
 * Whether this registration may carry the project's first data key: E3 lists
 * {@link NEXUS_FEATURE_PROJECT_INITIAL_KEY}, the credential is a full-profile
 * device (`keys:write`), and this account does not see the project yet. Any
 * failure (a server without E3, a refused or malformed answer) answers
 * `false`, so the registration is the one older servers get. One attempt: a
 * server that does not answer fails the registration itself.
 */
async function serverTakesInitialKey(
  opts: NexusLinkOptions,
  apiUrl: string,
  bearer: string,
  projectId: string,
): Promise<boolean> {
  const http = new Http({
    baseUrl: apiUrl,
    token: bearer,
    maxAttempts: 1,
    ...(opts.fetch ? { fetch: opts.fetch } : {}),
  });
  try {
    const status = await http.request(
      'GET',
      `/v1/status?projectId=${encodeURIComponent(projectId)}`,
      nexusCloudStatusSchema,
    );
    return (
      (status.features ?? []).includes(NEXUS_FEATURE_PROJECT_INITIAL_KEY) &&
      status.credential.profile === 'device' &&
      status.project?.registered === false
    );
  } catch {
    return false;
  }
}

/**
 * A new project data key wrapped by the account master key at version 1, for
 * `initialKey`. The account key is only read here (a read-only unlock): link
 * never mints it, `cleo login` provisions it (onboarding A). When this device
 * cannot unlock it, the answer is a warning instead, and the project's first
 * `cleo cloud push` creates the key. Nothing here logs or returns a key in
 * plaintext.
 */
async function newInitialProjectKey(
  opts: NexusLinkOptions,
  apiUrl: string,
  projectId: string,
): Promise<{ initialKey: InitialProjectKey } | { warning: string }> {
  try {
    // Imported here, not at the top: nexus-vault-keys imports nexus-cloud, which imports this module.
    const { connectNexusVault, unlockNexusAccountKey } = await import('./nexus-vault-keys.js');
    const conn = await connectNexusVault({
      apiUrl,
      ...(opts.store ? { store: opts.store } : {}),
      ...(opts.fetch ? { fetch: opts.fetch } : {}),
      ...(opts.deviceStore ? { deviceStore: opts.deviceStore } : {}),
      ...(opts.vaultState ? { vaultState: opts.vaultState } : {}),
    });
    const { masterKey } = await unlockNexusAccountKey(conn, { readOnly: true });
    return {
      initialKey: { wrappedProjectKey: wrapProjectKey(masterKey, newProjectKey(), projectId, 1) },
    };
  } catch (err) {
    const why =
      err instanceof NexusAccountError && err.code === 'E_NEXUS_VAULT_EMPTY'
        ? 'this account has no encryption key yet'
        : err instanceof NexusAccountError
          ? `${err.code}: ${err.message}`
          : err instanceof Error
            ? err.message
            : String(err);
    return {
      warning: `the project was registered without its encryption key (${why}); the first \`cleo cloud push\` creates it`,
    };
  }
}

/**
 * Register the project with Nexus (label only, never a path; a new project
 * with its first data key when the server takes it) and persist the binding
 * in `.cleo/nexus-link.json`. Idempotent.
 *
 * @param opts - Project root, label, API URL, store and test overrides.
 * @returns The binding, whether it already existed, and the key version the
 *   registration stored.
 * @throws {NexusAccountError} Not signed in, expired session, invalid label,
 *   not a CLEO project, or an API refusal (e.g. the id belongs to another account).
 */
export async function linkProjectToNexus(
  opts: NexusLinkOptions = {},
): Promise<NexusProjectLinkResult> {
  const apiUrl = resolveNexusApiUrl(opts.apiUrl);
  const store = opts.store ?? new FileNexusTokenStore();
  const deviceMode = isNexusDeviceEnabled();
  // With device credentials (the default) the device credential is used, upgrading a 9.24
  // session first (contract §3.4); otherwise the 9.24 session, as before.
  const handle = deviceMode
    ? await ensureNexusDeviceCredential({
        apiUrl,
        store,
        ...(opts.fetch ? { fetch: opts.fetch } : {}),
        ...(opts.deviceStore ? { deviceStore: opts.deviceStore } : {}),
      })
    : null;
  const bearer = handle
    ? handle.device.currentBearer()
    : (await requireNexusSession(apiUrl, store)).bearer();
  if (bearer === null) {
    throw new NexusAccountError(
      'E_NEXUS_NOT_SIGNED_IN',
      `not signed in to Cleo Nexus at ${apiUrl}`,
      'run `cleo login nexus`',
    );
  }

  let projectRoot: string;
  try {
    projectRoot = resolveOrCwd(opts.projectRoot);
  } catch {
    throw new NexusAccountError(
      'E_NEXUS_NOT_A_PROJECT',
      'not inside a CLEO project',
      'run `cleo init` first',
    );
  }
  const identity = readDeclaredProjectIdentity(projectRoot);
  if (!identity) {
    throw new NexusAccountError(
      'E_NEXUS_NOT_A_PROJECT',
      'this project has no project id (.cleo/project-id)',
      'run `cleo init` or `cleo upgrade` to assign one',
    );
  }
  const projectId = identity.projectId;
  const label = resolveLinkLabel(projectRoot, opts.label);

  const warnings: string[] = handle ? [...handle.warnings] : [];
  // Onboarding B: a new project is registered with its first data key. A 9.24
  // session has no account key, so it never sends one.
  let initialKey: InitialProjectKey | undefined;
  if (handle && (await serverTakesInitialKey(opts, apiUrl, bearer, projectId))) {
    const minted = await newInitialProjectKey(opts, apiUrl, projectId);
    if ('initialKey' in minted) initialKey = minted.initialKey;
    else warnings.push(minted.warning);
  }

  const http = new Http({
    baseUrl: apiUrl,
    token: bearer,
    ...(opts.fetch ? { fetch: opts.fetch } : {}),
  });
  let registered: Awaited<ReturnType<typeof registerProject>>;
  try {
    registered = await registerLinkedProject(http, {
      projectId,
      label,
      ...(initialKey ? { initialKey } : {}),
    });
  } catch (err) {
    throw deviceMode ? nexusApiErrorToAccountError(err) : toLinkError(err);
  }

  // Steps 3 to 5 of §3.6: attach this store's replica to the device and
  // report presence. A 9.24 session cannot attach (the route needs a device).
  // An attach failure never fails the link: the project is registered, the
  // binding below is still written, and the warning names the remedy.
  let replica: NexusProjectLinkResult['replica'] = null;
  let attachError: NexusProjectLinkResult['attachError'] = null;
  if (handle === null && opts.rebind === true) {
    warnings.push(
      '--rebind needs device credentials (CLEO_NEXUS_DEVICE turns them off), so nothing was attached or rebound',
    );
  }
  if (handle) {
    try {
      const attached = await attachProjectReplica({
        apiUrl,
        bearer,
        deviceId: handle.device.deviceId,
        projectId: registered.project.projectId,
        projectRoot,
        cliVersion: opts.cliVersion ?? (await installedCleoVersion()),
        ...(opts.rebind === true ? { rebind: true } : {}),
        ...(opts.replicaBinder ? { binder: opts.replicaBinder } : {}),
        ...(opts.fetch ? { fetch: opts.fetch } : {}),
      });
      replica = attached.replica;
      warnings.push(...attached.warnings);
    } catch (err) {
      const mapped = nexusApiErrorToAccountError(err);
      const code = mapped instanceof NexusAccountError ? mapped.code : 'E_NEXUS_REQUEST_FAILED';
      const fix =
        mapped instanceof NexusAccountError && mapped.fix
          ? mapped.fix
          : 're-run `cleo project link`';
      attachError = {
        code,
        message: mapped.message,
        fix: mapped instanceof NexusAccountError && mapped.fix ? mapped.fix : null,
      };
      warnings.push(
        `the project is linked, but this machine's copy was not attached to it (${code}: ${mapped.message}); ${fix}`,
      );
    }
  }

  const linkPath = nexusLinkPath(projectRoot);
  const link: NexusProjectLink = {
    apiUrl,
    localProjectId: projectId,
    remoteProjectId: registered.project.projectId,
    organizationId: registered.project.organizationId,
    label: registered.project.label,
    streamId: registered.streamId,
    linkedAt: new Date().toISOString(),
    ...(replica
      ? {
          replicaId: replica.replicaId,
          nexusDeviceId: replica.deviceId,
          attachedAt: new Date().toISOString(),
        }
      : {}),
  };
  // Locked read-modify-write: concurrent links (other origins, other shells)
  // never drop each other's entries. withLock needs a parseable file to read,
  // so seed an empty one exclusively ('wx') when there is none.
  try {
    writeFileSync(linkPath, `${JSON.stringify({ version: 1, links: {} })}\n`, { flag: 'wx' });
  } catch (err) {
    if (!(err instanceof Error && 'code' in err && err.code === 'EEXIST')) throw err;
  }
  await withLock<NexusLinkFile>(linkPath, (current) => {
    const parsed = linkFileSchema.safeParse(current);
    if (!parsed.success) {
      // Never overwrite a file this version cannot read (a newer format):
      // that would drop every other origin's binding.
      throw new NexusAccountError(
        'E_NEXUS_LINK_FILE_UNSUPPORTED',
        `${linkPath} is not a version 1 link file this CLEO can update`,
        'upgrade CLEO, or move the file aside and run `cleo project link` again',
      );
    }
    const links = parsed.data.links;
    return {
      ...parsed.data,
      version: 1,
      links: {
        ...links,
        [apiUrl]: mergeLinkEntry(links[apiUrl], link, handle !== null && replica === null),
      },
    };
  });
  // The envelope reports what is stored, cached replica fields included.
  const stored = readNexusProjectLink(projectRoot, apiUrl) ?? link;

  return {
    link: stored,
    alreadyLinked: !registered.created,
    linkPath,
    replica,
    attachError,
    initialKeyVersion: initialKey ? (registered.initialKeyVersion ?? null) : null,
    warnings,
  };
}

/** The installed CLEO version, for presence. */
async function installedCleoVersion(): Promise<string> {
  const { getCleoVersion } = await import('../scaffold/ensure-config.js');
  return getCleoVersion();
}
