/**
 * `cleo project link`: register the current project with Cleo Nexus and bind
 * the remote project to the local one.
 *
 * ## What is sent
 *
 * `POST /v1/projects` with `{ projectId, label }` only:
 *
 * - `projectId` is the tracked, immutable `.cleo/project-id`
 *   (`readDeclaredProjectIdentity`), the key the server stores projects under,
 *   so the remote id IS the local id.
 * - `label` is the project's display name in plaintext
 *   ({@link getProjectDisplayName}), or `--label`. It must not look like a path.
 *
 * No filesystem path, git remote or directory layout is ever sent.
 *
 * ## Idempotency
 *
 * Registering the same id again answers 200 (201 on first registration) and
 * sets the server label to the one sent, so re-linking after a rename updates
 * the label. Linking twice is safe.
 *
 * ## Where the binding lives
 *
 * `<project>/.cleo/nexus-link.json`, keyed by API origin. It is machine-local:
 * `.cleo/.gitignore` denies everything not allow-listed, so the binding (which
 * names an account's organization) is never committed. It is not
 * `project-context.json`, which is tracked in git and regenerated by
 * `cleo upgrade`, and not the project `cleo.db`, so linking never opens or
 * migrates the task store. Each clone links itself, the same way each machine
 * signs itself in.
 *
 * @task T12712
 * @epic T12322
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { NexusProjectLink, NexusProjectLinkResult } from '@cleocode/contracts';
import { readDeclaredProjectIdentity } from '@cleocode/paths';
import { z } from 'zod';
import { getCleoDirAbsolute, resolveOrCwd } from '../paths.js';
import { getProjectDisplayName } from '../project-info.js';
import { writeJsonFileAtomic } from '../store/file-utils.js';
import { Http, NexusError } from './http.js';
import {
  NexusAccountError,
  type NexusFlowOptions,
  requireNexusSession,
  resolveNexusApiUrl,
} from './nexus-auth.js';
import { FileNexusTokenStore } from './nexus-credentials.js';
import { registerProject } from './projects.js';

/** File name of the binding, inside the project's `.cleo/` directory. */
export const NEXUS_LINK_FILE = 'nexus-link.json';

/** Longest label the server accepts (`RegisterProjectRequest.label`). */
export const NEXUS_LABEL_MAX = 120;

const linkSchema = z.object({
  apiUrl: z.string(),
  localProjectId: z.string(),
  remoteProjectId: z.string(),
  organizationId: z.string(),
  label: z.string().nullable(),
  streamId: z.string(),
  linkedAt: z.string(),
});

const linkFileSchema = z.object({
  version: z.literal(1),
  links: z.record(z.string(), linkSchema),
});

type NexusLinkFile = z.infer<typeof linkFileSchema>;

/** Options for {@link linkProjectToNexus}. */
export interface NexusLinkOptions extends NexusFlowOptions {
  /** Project root; defaults to the resolved current project. */
  projectRoot?: string;
  /** Label to register (`--label`); defaults to {@link getProjectDisplayName}. */
  label?: string;
}

/**
 * Validate a project label: 1-120 characters, no path separators, no
 * home-directory shorthand, no control characters. A label is a name, never a
 * path.
 *
 * @param raw - Candidate label.
 * @returns The trimmed label.
 * @throws {NexusAccountError} `E_NEXUS_INVALID_LABEL`.
 */
export function validateNexusProjectLabel(raw: string): string {
  const label = raw.trim();
  const invalid = /[/\\\u0000-\u001f\u007f]/.test(label) || label.startsWith('~');
  if (!label || label.length > NEXUS_LABEL_MAX || invalid) {
    throw new NexusAccountError(
      'E_NEXUS_INVALID_LABEL',
      `invalid project label "${label}": use 1-${NEXUS_LABEL_MAX} characters with no "/", "\\" or leading "~" (a name, not a path)`,
      'pass `--label <name>`',
    );
  }
  return label;
}

/**
 * Path of the binding file for a project.
 *
 * @param projectRoot - Project root.
 * @returns `<project>/.cleo/nexus-link.json`.
 */
export function nexusLinkPath(projectRoot: string): string {
  return join(getCleoDirAbsolute(projectRoot), NEXUS_LINK_FILE);
}

/** Read the binding file; missing or malformed reads as empty. */
function readLinkFile(path: string): NexusLinkFile {
  try {
    const parsed = linkFileSchema.safeParse(JSON.parse(readFileSync(path, 'utf-8')));
    if (parsed.success) return parsed.data;
  } catch {
    /* missing or unreadable */
  }
  return { version: 1, links: {} };
}

/**
 * The stored binding for a project and origin, if any.
 *
 * @param projectRoot - Project root.
 * @param apiUrl - API URL (any URL on the origin).
 * @returns The binding, or `null`.
 */
export function readNexusProjectLink(projectRoot: string, apiUrl: string): NexusProjectLink | null {
  return readLinkFile(nexusLinkPath(projectRoot)).links[new URL(apiUrl).origin] ?? null;
}

/** Map an API failure to a Nexus error; a 401 means the session expired. */
function toLinkError(err: unknown): Error {
  if (err instanceof NexusError) {
    if (err.status === 401) {
      return new NexusAccountError(
        'E_NEXUS_SESSION_EXPIRED',
        'the Nexus session expired or was revoked',
        'run `cleo login nexus` again',
      );
    }
    const remedy = typeof err.details?.['remedy'] === 'string' ? err.details['remedy'] : undefined;
    return new NexusAccountError('E_NEXUS_REQUEST_FAILED', err.message, remedy);
  }
  return err instanceof Error ? err : new Error(String(err));
}

/**
 * Register the project with Nexus (label only, never a path) and persist the
 * binding in `.cleo/nexus-link.json`. Idempotent.
 *
 * @param opts - Project root, label, API URL, store and test overrides.
 * @returns The binding and whether it already existed.
 * @throws {NexusAccountError} Not signed in, expired session, invalid label,
 *   not a CLEO project, or an API refusal (e.g. the id belongs to another account).
 */
export async function linkProjectToNexus(
  opts: NexusLinkOptions = {},
): Promise<NexusProjectLinkResult> {
  const apiUrl = resolveNexusApiUrl(opts.apiUrl);
  const store = opts.store ?? new FileNexusTokenStore();
  const session = await requireNexusSession(apiUrl, store);

  let projectRoot: string;
  try {
    projectRoot = resolveOrCwd(opts.projectRoot);
  } catch {
    throw new NexusAccountError(
      'E_NEXUS_NOT_A_PROJECT',
      'not inside a CLEO project',
      'run `cleo init` first',
    );
  }
  const identity = readDeclaredProjectIdentity(projectRoot);
  if (!identity) {
    throw new NexusAccountError(
      'E_NEXUS_NOT_A_PROJECT',
      'this project has no project id (.cleo/project-id)',
      'run `cleo init` or `cleo upgrade` to assign one',
    );
  }
  const projectId = identity.projectId;
  const label = validateNexusProjectLabel(opts.label ?? getProjectDisplayName(projectRoot));

  const http = new Http({
    baseUrl: apiUrl,
    token: session.bearer(),
    ...(opts.fetch ? { fetch: opts.fetch } : {}),
  });
  let registered: Awaited<ReturnType<typeof registerProject>>;
  try {
    registered = await registerProject(http, { projectId, label });
  } catch (err) {
    throw toLinkError(err);
  }

  const linkPath = nexusLinkPath(projectRoot);
  const file = readLinkFile(linkPath);
  const link: NexusProjectLink = {
    apiUrl,
    localProjectId: projectId,
    remoteProjectId: registered.project.projectId,
    organizationId: registered.project.organizationId,
    label: registered.project.label,
    streamId: registered.streamId,
    linkedAt: new Date().toISOString(),
  };
  writeJsonFileAtomic(linkPath, { version: 1, links: { ...file.links, [apiUrl]: link } });

  return {
    link,
    alreadyLinked: !registered.created,
    linkPath,
  };
}
