#!/usr/bin/env tsx
/**
 * T1907 — Freshness sentinel: checks if the BRAIN dream cycle is overdue.
 *
 * Invokes `cleo memory dream --status` against a canary project and alerts
 * if `isOverdue=true`. Used as a daily CI gate to catch silent regressions
 * in the dream-cycle / consolidation pipeline (T1682 silent-failure pattern).
 *
 * Exit codes:
 *   0 — engine is healthy (isOverdue=false)
 *   1 — engine is overdue (isOverdue=true) or check failed
 *
 * Environment:
 *   CLEO_PROJECT_ROOT — path to the project whose brain.db should be checked
 *                       (defaults to current working directory)
 *   GITHUB_TOKEN      — required for GH issue creation alert
 *   GITHUB_REPOSITORY — owner/repo for GH issue creation (e.g. "org/repo")
 *   DRY_RUN           — set to "1" to print alert text without creating issues
 *
 * @task T1907
 * @epic T1892
 */

import { spawnSync } from 'node:child_process';

// ============================================================================
// Types
// ============================================================================

interface DreamStatus {
  lastConsolidatedAt: string | null;
  observationsSinceLastConsolidation: number;
  idleMinutesSinceLastRetrieval: number;
  tickLoopAlive: boolean;
  lastTickAt: string | null;
  dreamInFlight: boolean;
  lastError: string | null;
  isOverdue: boolean;
}

interface CleoCmdResult {
  success: boolean;
  data?: DreamStatus;
  error?: { message: string };
}

// ============================================================================
// Helpers
// ============================================================================

function getDreamStatus(projectRoot: string): DreamStatus {
  const result = spawnSync('cleo', ['memory', 'dream', '--status', '--json'], {
    cwd: projectRoot,
    encoding: 'utf-8',
    timeout: 30_000,
  });

  if (result.error) {
    throw new Error(`cleo spawn failed: ${result.error.message}`);
  }

  const raw = result.stdout?.trim() ?? '';
  if (!raw) {
    const stderr = result.stderr?.trim() ?? '';
    throw new Error(`cleo memory dream --status produced no output. stderr: ${stderr}`);
  }

  let parsed: CleoCmdResult;
  try {
    parsed = JSON.parse(raw) as CleoCmdResult;
  } catch {
    throw new Error(`Failed to parse cleo output as JSON: ${raw.slice(0, 200)}`);
  }

  if (!parsed.success || !parsed.data) {
    throw new Error(
      `cleo memory dream --status returned failure: ${parsed.error?.message ?? 'unknown'}`,
    );
  }

  return parsed.data;
}

function createGitHubIssue(status: DreamStatus, repo: string, token: string): void {
  const title = `[Freshness Sentinel] BRAIN dream cycle is overdue`;
  const body = [
    '## Dream Cycle Overdue Alert',
    '',
    `The BRAIN consolidation pipeline has not run recently enough.`,
    '',
    '### Status',
    '```json',
    JSON.stringify(status, null, 2),
    '```',
    '',
    '### Actions',
    '- Run `cleo memory dream` manually to trigger consolidation',
    '- Check that the sentient daemon is running (`cleo sentient status`)',
    '- Review the brain.db consolidation events log',
    '',
    `_Generated by freshness-sentinel at ${new Date().toISOString()}_`,
  ].join('\n');

  const result = spawnSync(
    'gh',
    ['issue', 'create', '--repo', repo, '--title', title, '--body', body, '--label', 'automation'],
    { encoding: 'utf-8', timeout: 30_000 },
  );

  if (result.error) {
    console.warn(
      `[freshness-sentinel] WARNING: Failed to create GH issue: ${result.error.message}`,
    );
    return;
  }

  if (result.status !== 0) {
    console.warn(
      `[freshness-sentinel] WARNING: gh issue create failed (exit ${result.status}): ${result.stderr?.slice(0, 200)}`,
    );
    return;
  }

  console.log(`[freshness-sentinel] Created GH issue: ${result.stdout?.trim()}`);
}

// ============================================================================
// Main
// ============================================================================

async function main(): Promise<void> {
  const projectRoot = process.env['CLEO_PROJECT_ROOT'] ?? process.cwd();
  const dryRun = process.env['DRY_RUN'] === '1';
  const githubToken = process.env['GITHUB_TOKEN'];
  const githubRepo = process.env['GITHUB_REPOSITORY'];

  console.log(`[freshness-sentinel] Checking dream cycle health for: ${projectRoot}`);

  let status: DreamStatus;
  try {
    status = getDreamStatus(projectRoot);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[freshness-sentinel] ERROR: Failed to get dream status: ${message}`);
    process.exit(1);
  }

  console.log('[freshness-sentinel] Status:', JSON.stringify(status, null, 2));

  if (!status.isOverdue) {
    console.log('[freshness-sentinel] OK: Dream cycle is healthy.');
    process.exit(0);
  }

  console.warn('[freshness-sentinel] ALERT: Dream cycle is overdue!');
  console.warn(
    `  observations since last consolidation: ${status.observationsSinceLastConsolidation}`,
  );
  console.warn(`  last consolidated: ${status.lastConsolidatedAt ?? 'never'}`);
  console.warn(`  tick loop alive: ${status.tickLoopAlive}`);

  if (dryRun) {
    console.log('[freshness-sentinel] DRY_RUN=1: skipping alert creation');
    process.exit(1);
  }

  if (githubToken && githubRepo) {
    createGitHubIssue(status, githubRepo, githubToken);
  } else {
    console.warn(
      '[freshness-sentinel] No GITHUB_TOKEN or GITHUB_REPOSITORY set — skipping GH issue creation',
    );
  }

  process.exit(1);
}

main().catch((err) => {
  console.error('[freshness-sentinel] Unhandled error:', err);
  process.exit(1);
});
