/**
 * Claude SDK Spawn Provider — Vercel AI SDK edition.
 *
 * Implements {@link AdapterSpawnProvider} using the Vercel AI SDK
 * (`ai` v6 + `@ai-sdk/anthropic`) instead of the legacy
 * `@anthropic-ai/claude-agent-sdk`. CLEO retains its own orchestration
 * primitives (`composeSpawnPayload`, playbook runtime, agent registry);
 * the SDK is strictly the LLM bridge.
 *
 * Differences from `ClaudeCodeSpawnProvider`:
 * - Uses `generateText()` via Vercel AI SDK instead of a detached child process
 * - Awaits full completion before returning (synchronous output capture)
 * - Session IDs are generated by CLEO and tracked in `SessionStore`
 * - No temp files, no OS PIDs — tracking is purely in-memory session IDs
 * - `canSpawn()` uses 3-tier key resolution (env var → stored key → Claude Code OAuth)
 *
 * CANT enrichment is identical to the CLI provider: `buildCantEnrichedPrompt()`
 * is called before `generateText()` and the result is passed as the user prompt.
 *
 * @task T581 (original)
 * @task T933 (SDK consolidation — Vercel AI SDK migration)
 * @see T752 — canSpawn() OAuth fix
 * @see ADR-052 — SDK consolidation decision
 */

import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { AdapterSpawnProvider, SpawnContext, SpawnResult } from '@cleocode/contracts';
import { getErrorMessage } from '@cleocode/contracts';
import { SessionStore } from './session-store.js';
import { resolveTools } from './tool-bridge.js';

// ---------------------------------------------------------------------------
// Inline 3-tier Anthropic key resolver
// NOTE: Cannot import from @cleocode/core — circular dependency
//       (@cleocode/core depends on @cleocode/adapters). This is a deliberate
//       inline copy of the resolution logic from anthropic-key-resolver.ts.
//       Keep in sync with packages/core/src/memory/anthropic-key-resolver.ts.
//       T752 — OAuth fix for canSpawn()
// ---------------------------------------------------------------------------

/**
 * Resolve the Anthropic API key using a 3-tier priority chain:
 * 1. `ANTHROPIC_API_KEY` environment variable
 * 2. `~/.local/share/cleo/anthropic-key` (user-stored via cleo config)
 * 3. `~/.claude/.credentials.json` → claudeAiOauth.accessToken (Claude Code OAuth)
 *
 * @returns The key/token string, or null if unavailable.
 */
function resolveAnthropicApiKey(): string | null {
  // 1. Explicit env var
  const envKey = process.env.ANTHROPIC_API_KEY;
  if (envKey?.trim()) return envKey;

  // 2. CLEO global stored key
  try {
    const xdg = process.env.XDG_DATA_HOME || join(homedir(), '.local', 'share');
    const keyFile = join(xdg, 'cleo', 'anthropic-key');
    if (existsSync(keyFile)) {
      const stored = readFileSync(keyFile, 'utf-8').trim();
      if (stored) return stored;
    }
  } catch {
    // Not available — continue
  }

  // 3. Claude Code OAuth token (free for Claude Code users)
  try {
    const credPath = join(homedir(), '.claude', '.credentials.json');
    if (!existsSync(credPath)) return null;
    const raw = readFileSync(credPath, 'utf-8');
    const creds = JSON.parse(raw) as {
      claudeAiOauth?: { accessToken?: string; expiresAt?: number };
    };
    const token = creds.claudeAiOauth?.accessToken;
    if (token?.trim()) {
      const expiresAt = creds.claudeAiOauth?.expiresAt;
      if (expiresAt && Date.now() > expiresAt) return null;
      return token;
    }
  } catch {
    // Credentials file missing or unreadable — not an error
  }

  return null;
}

/** Model used when no model is specified in spawn options. */
const DEFAULT_MODEL = 'claude-sonnet-4-5';

/**
 * Spawn provider that uses the Vercel AI SDK (`ai` v6 + `@ai-sdk/anthropic`)
 * for programmatic subagent execution.
 *
 * Each call to `spawn()` runs a single `generateText()` call to completion and
 * captures the output. Sessions are tracked in `SessionStore` so callers can
 * inspect active sessions via `listRunning()` and remove them via `terminate()`.
 *
 * @remarks
 * Unlike the legacy `@anthropic-ai/claude-agent-sdk`, the Vercel AI SDK is
 * strictly an LLM bridge — it does not manage a Claude Code subprocess or
 * provide built-in MCP server wiring. Tool use is available through the SDK's
 * tool system, but CLEO orchestration (composeSpawnPayload, playbooks, the
 * agent registry) remains the source of truth for scaffolding.
 */
export class ClaudeSDKSpawnProvider implements AdapterSpawnProvider {
  /** In-memory session registry. */
  private readonly sessions = new SessionStore();

  /**
   * Check whether the SDK can be used in the current environment.
   *
   * Uses 3-tier key resolution so the provider works with:
   * - `ANTHROPIC_API_KEY` environment variable (explicit)
   * - `~/.local/share/cleo/anthropic-key` (user-stored via cleo config)
   * - Claude Code OAuth token (zero-config for Claude Code users)
   *
   * @returns `true` when any Anthropic credential is available
   */
  async canSpawn(): Promise<boolean> {
    return !!resolveAnthropicApiKey();
  }

  /**
   * Spawn a subagent using the Vercel AI SDK.
   *
   * Enriches the prompt via CANT context, runs `generateText()` to completion,
   * and returns a `SpawnResult` with the final output and exit code.
   *
   * @param context - Spawn context with taskId, prompt, options
   * @returns Resolved spawn result (status: 'completed' or 'failed')
   */
  async spawn(context: SpawnContext): Promise<SpawnResult> {
    const instanceId = `sdk-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
    const sessionId = `cleo-${instanceId}`;
    const startTime = new Date().toISOString();

    // Register in session store immediately so listRunning() reflects it
    // before the async generation starts.
    this.sessions.add({
      instanceId,
      sessionId,
      taskId: context.taskId,
      startTime,
    });

    try {
      // CANT enrichment — best-effort, identical to ClaudeCodeSpawnProvider.
      let enrichedPrompt = context.prompt;
      try {
        const { buildCantEnrichedPrompt } = await import('../../cant-context.js');
        enrichedPrompt = await buildCantEnrichedPrompt({
          projectDir: context.workingDirectory ?? process.cwd(),
          basePrompt: context.prompt,
          agentName: (context.options?.agentName as string) ?? undefined,
        });
      } catch {
        // CANT enrichment unavailable — use raw prompt
      }

      // Lazy-import the SDK to avoid hard failures when credentials are absent
      // (canSpawn() guards the normal path, but tests may import this module
      // without a key).
      const { createAnthropic } = await import('@ai-sdk/anthropic');
      const { generateText } = await import('ai');

      const apiKey = resolveAnthropicApiKey();
      if (!apiKey) {
        this.sessions.remove(instanceId);
        return {
          instanceId,
          taskId: context.taskId,
          providerId: 'claude-sdk',
          status: 'failed',
          startTime,
          endTime: new Date().toISOString(),
          exitCode: 1,
          error: 'No Anthropic credentials available (env, stored key, or Claude Code OAuth)',
        };
      }

      // Build the Anthropic provider with the resolved key.
      const anthropicProvider = createAnthropic({ apiKey });

      // Record the tool allowlist in metadata even though the AI SDK lacks
      // built-in tool execution for arbitrary Claude Code tools. Downstream
      // orchestration (composeSpawnPayload) applies allowlists before prompt
      // composition; this array is surfaced so telemetry remains complete.
      const toolAllowlist = context.options?.toolAllowlist as string[] | undefined;
      const allowedTools = resolveTools(toolAllowlist);

      const modelId = (context.options?.model as string) ?? DEFAULT_MODEL;

      const result = await generateText({
        model: anthropicProvider(modelId),
        prompt: enrichedPrompt,
        providerOptions: {
          anthropic: {
            // Preserve allowlist metadata for trace visibility.
            cleoAllowedTools: allowedTools,
          },
        },
      });

      const endTime = new Date().toISOString();
      this.sessions.remove(instanceId);

      const output = (result.text ?? '').trim();

      return {
        instanceId,
        taskId: context.taskId,
        providerId: 'claude-sdk',
        status: 'completed',
        output,
        exitCode: 0,
        startTime,
        endTime,
      };
    } catch (error) {
      const endTime = new Date().toISOString();
      this.sessions.remove(instanceId);

      return {
        instanceId,
        taskId: context.taskId,
        providerId: 'claude-sdk',
        status: 'failed',
        startTime,
        endTime,
        exitCode: 1,
        error: getErrorMessage(error),
      };
    }
  }

  /**
   * List sessions currently tracked as active (spawned but not yet completed).
   *
   * Because SDK sessions run to completion inside `spawn()`, this list is
   * typically empty unless concurrent spawns are in flight.
   *
   * @returns Array of in-flight spawn results
   */
  async listRunning(): Promise<SpawnResult[]> {
    return this.sessions.listActive().map((entry) => ({
      instanceId: entry.instanceId,
      taskId: entry.taskId,
      providerId: 'claude-sdk',
      status: 'running' as const,
      startTime: entry.startTime,
    }));
  }

  /**
   * Remove a session from tracking.
   *
   * The underlying `generateText()` call runs inside `spawn()` and cannot be
   * cancelled externally once the HTTP request is in flight. Removing the
   * entry from the store prevents it from appearing in `listRunning()` but
   * does not interrupt the in-progress request.
   *
   * @param instanceId - ID of the spawn instance to terminate
   */
  async terminate(instanceId: string): Promise<void> {
    this.sessions.remove(instanceId);
  }
}
