/**
 * Canonical cost tracking with cache economics for LLM usage.
 *
 * Ported from Hermes `agent/usage_pricing.py` (spec section 7.5).
 * MVP slice: static pricing snapshot for major providers + cost helpers.
 *
 * Resolution priority:
 *   1. Exact model ID match in {@link PRICING_SNAPSHOT}
 *   2. Alias-strip (trailing date / version suffix removed)
 *   3. `null` → caller logs / tracks unknown model
 *
 * @module llm/usage-pricing
 * @task T9274
 * @epic T9261 (T-LLM-CRED-CENTRALIZATION Phase 3)
 */

import type { NormalizedUsage } from '@cleocode/contracts';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * Source attribution for a pricing entry.
 */
export type PricingSource =
  | 'official_docs_snapshot' // From provider documentation (manual snapshot)
  | 'provider_cost_api' // Fetched from provider's cost API
  | 'user_override'; // User-configured in config.json

/**
 * Per-million-token cost in USD for a model.
 *
 * Cache pricing is OPTIONAL — providers without prompt caching omit those
 * fields and `computeCost` treats them as the same as input/output rates.
 *
 * @task T9274 (T-LLM-CRED Phase 3)
 */
export interface PricingEntry {
  /** USD per million prompt tokens. */
  inputCostPerMillion: number;
  /** USD per million completion tokens. */
  outputCostPerMillion: number;
  /** USD per million cache-read tokens (Anthropic ephemeral cache hit). */
  cacheReadCostPerMillion?: number;
  /** USD per million cache-write tokens (Anthropic ephemeral cache miss / first write). */
  cacheWriteCostPerMillion?: number;
  /** Attribution for this pricing entry. */
  source: PricingSource;
  /** Snapshot date YYYY-MM-DD (present for `official_docs_snapshot` entries). */
  snapshotDate?: string;
}

/**
 * Canonical usage record — superset of {@link NormalizedUsage} with reasoning
 * tokens, explicit cache-write accounting, and an optional request count for
 * cost aggregation.
 */
export interface CanonicalUsage {
  /** Tokens consumed by the prompt (non-cached). */
  inputTokens: number;
  /** Tokens generated by the model. */
  outputTokens: number;
  /** Tokens served from prompt cache (read hit). */
  cacheReadTokens?: number;
  /** Tokens written to prompt cache (cache miss / first write). */
  cacheWriteTokens?: number;
  /** Model-internal reasoning tokens (o1 / extended-thinking). Billed at output rate. */
  reasoningTokens?: number;
  /** Number of API requests included in this usage record (default 1). */
  requestCount?: number;
}

// ---------------------------------------------------------------------------
// Static pricing snapshot
// ---------------------------------------------------------------------------

/**
 * Static pricing snapshot (USD per million tokens).
 *
 * Sources:
 * - Anthropic: https://www.anthropic.com/pricing (2026-05-13)
 * - OpenAI: https://openai.com/pricing (2026-05-13)
 * - Google Gemini: https://ai.google.dev/pricing (2026-05-13)
 * - DeepSeek: https://api-docs.deepseek.com/quick_start/pricing (2026-05-13)
 *
 * Add new entries as providers expand. User overrides are applied via a
 * separate overrides map passed to {@link computeCost}.
 *
 * @remarks All values are frozen — mutate via `computeCost(usage, model, overrides)`.
 */
export const PRICING_SNAPSHOT: Readonly<Record<string, PricingEntry>> = Object.freeze({
  // ── Anthropic ────────────────────────────────────────────────────────────
  'claude-haiku-4-5-20251001': {
    inputCostPerMillion: 1.0,
    outputCostPerMillion: 5.0,
    cacheReadCostPerMillion: 0.1,
    cacheWriteCostPerMillion: 1.25,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
  'claude-sonnet-4-6-20251001': {
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
    cacheReadCostPerMillion: 0.3,
    cacheWriteCostPerMillion: 3.75,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
  'claude-opus-4-7-20251101': {
    inputCostPerMillion: 15.0,
    outputCostPerMillion: 75.0,
    cacheReadCostPerMillion: 1.5,
    cacheWriteCostPerMillion: 18.75,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
  'claude-3-5-sonnet-20241022': {
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
    cacheReadCostPerMillion: 0.3,
    cacheWriteCostPerMillion: 3.75,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },

  // ── OpenAI ───────────────────────────────────────────────────────────────
  'gpt-4o': {
    inputCostPerMillion: 2.5,
    outputCostPerMillion: 10.0,
    cacheReadCostPerMillion: 1.25,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
  'gpt-4o-mini': {
    inputCostPerMillion: 0.15,
    outputCostPerMillion: 0.6,
    cacheReadCostPerMillion: 0.075,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
  'gpt-4-turbo': {
    inputCostPerMillion: 10.0,
    outputCostPerMillion: 30.0,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
  'gpt-3.5-turbo': {
    inputCostPerMillion: 0.5,
    outputCostPerMillion: 1.5,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },

  // ── Google Gemini ─────────────────────────────────────────────────────────
  'gemini-1.5-pro': {
    inputCostPerMillion: 1.25,
    outputCostPerMillion: 5.0,
    cacheReadCostPerMillion: 0.3125,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
  'gemini-1.5-flash': {
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
    cacheReadCostPerMillion: 0.01875,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },

  // ── DeepSeek ─────────────────────────────────────────────────────────────
  'deepseek-chat': {
    inputCostPerMillion: 0.27,
    outputCostPerMillion: 1.1,
    cacheReadCostPerMillion: 0.07,
    source: 'official_docs_snapshot',
    snapshotDate: '2026-05-13',
  },
});

// ---------------------------------------------------------------------------
// Suffix patterns stripped for alias resolution (applied in order)
// ---------------------------------------------------------------------------

/** Patterns stripped from a model ID when performing alias-fallback lookup. */
const ALIAS_STRIP_PATTERNS: ReadonlyArray<RegExp> = Object.freeze([
  /-\d{8}$/, // trailing YYYYMMDD date stamp
  /-latest$/, // trailing -latest
  /-\d+\.\d+$/, // trailing -X.Y version
]);

// ---------------------------------------------------------------------------
// Public helpers
// ---------------------------------------------------------------------------

/**
 * Look up the pricing entry for a model.
 *
 * Resolution order:
 *   1. Exact match in {@link PRICING_SNAPSHOT}.
 *   2. Alias-strip: each {@link ALIAS_STRIP_PATTERNS} is tried in order.
 *   3. `null` when no entry is found.
 *
 * @param model - Provider model ID (e.g. `'claude-sonnet-4-6-20251001'`).
 * @returns The matching {@link PricingEntry} or `null`.
 */
export function lookupPricing(model: string): PricingEntry | null {
  const exact = PRICING_SNAPSHOT[model];
  if (exact !== undefined) return exact;

  for (const pattern of ALIAS_STRIP_PATTERNS) {
    const stripped = model.replace(pattern, '');
    if (stripped !== model) {
      const alias = PRICING_SNAPSHOT[stripped];
      if (alias !== undefined) return alias;
    }
  }

  return null;
}

/**
 * Compute USD cost for a usage record at a given model's pricing tier.
 *
 * Cost breakdown:
 * - **Input tokens** → `inputCostPerMillion`
 * - **Output tokens** → `outputCostPerMillion`
 * - **Cache-read tokens** → `cacheReadCostPerMillion` (falls back to `inputCostPerMillion`)
 * - **Cache-write tokens** → `cacheWriteCostPerMillion` (falls back to `inputCostPerMillion`)
 * - **Reasoning tokens** → `outputCostPerMillion` (billed at output rate, per Anthropic/OpenAI)
 *
 * Returns `0` for unknown models — callers should log or track these separately.
 *
 * @param usage - Usage record ({@link CanonicalUsage} or {@link NormalizedUsage}).
 * @param model - Provider model ID.
 * @returns Total cost in USD.
 */
export function computeCost(usage: CanonicalUsage | NormalizedUsage, model: string): number {
  const pricing = lookupPricing(model);
  if (pricing === null) return 0;

  const canon = toCanonicalUsage(usage);

  const inputCost = (canon.inputTokens / 1_000_000) * pricing.inputCostPerMillion;
  const outputCost = (canon.outputTokens / 1_000_000) * pricing.outputCostPerMillion;
  const cacheReadCost =
    ((canon.cacheReadTokens ?? 0) / 1_000_000) *
    (pricing.cacheReadCostPerMillion ?? pricing.inputCostPerMillion);
  const cacheWriteCost =
    ((canon.cacheWriteTokens ?? 0) / 1_000_000) *
    (pricing.cacheWriteCostPerMillion ?? pricing.inputCostPerMillion);
  const reasoningCost = ((canon.reasoningTokens ?? 0) / 1_000_000) * pricing.outputCostPerMillion;

  return inputCost + outputCost + cacheReadCost + cacheWriteCost + reasoningCost;
}

/**
 * Convert a {@link NormalizedUsage} or {@link CanonicalUsage} to a full
 * {@link CanonicalUsage} record.
 *
 * Field mapping:
 * - `NormalizedUsage.cachedTokens` → `cacheReadTokens`
 * - All other optional fields default to `undefined`.
 *
 * @param u - Source usage record.
 * @returns A {@link CanonicalUsage} with all optional fields filled or `undefined`.
 */
export function toCanonicalUsage(u: NormalizedUsage | CanonicalUsage): CanonicalUsage {
  // Determine cacheReadTokens: prefer explicit cacheReadTokens, then NormalizedUsage.cachedTokens
  const cacheReadTokens: number | undefined =
    'cacheReadTokens' in u && u.cacheReadTokens !== undefined
      ? u.cacheReadTokens
      : 'cachedTokens' in u && u.cachedTokens !== undefined
        ? u.cachedTokens
        : undefined;

  return {
    inputTokens: u.inputTokens,
    outputTokens: u.outputTokens,
    cacheReadTokens,
    cacheWriteTokens: 'cacheWriteTokens' in u ? u.cacheWriteTokens : undefined,
    reasoningTokens: 'reasoningTokens' in u ? u.reasoningTokens : undefined,
    requestCount: 'requestCount' in u ? u.requestCount : undefined,
  };
}
