/**
 * Rogue `.cleo/` directory forensic scanner and quarantine tool.
 *
 * Detects `.cleo/` directories that exist inside package sub-directories
 * (e.g. `packages/core/.cleo/`) — these are artefacts of agent misrouting
 * where CLEO initialised a project context inside a sub-package instead of
 * the monorepo root.
 *
 * Each rogue directory is fingerprinted with:
 *  - SHA-256 hashes for every contained file
 *  - Row counts from `tasks.db` and `brain.db`
 *  - The `__drizzle_migrations` snapshot from any SQLite database found
 *
 * Quarantine moves (never deletes) the directory to
 * `.cleo/quarantine/<pkg-name>-<ISO-timestamp>/` under the project root.
 *
 * @task T1868
 */

import { createHash } from 'node:crypto';
import type { Dirent } from 'node:fs';
import { mkdirSync, readdirSync, readFileSync, renameSync, statSync } from 'node:fs';
import { createRequire } from 'node:module';
import { basename, join, relative } from 'node:path';

// ---------------------------------------------------------------------------
// node:sqlite bootstrap (same pattern as project-health.ts)
// ---------------------------------------------------------------------------

const _require = createRequire(import.meta.url);

type DatabaseSyncModule = {
  DatabaseSync: new (
    path: string,
    options?: { readOnly?: boolean; timeout?: number },
  ) => {
    prepare(sql: string): { all(...args: unknown[]): unknown[]; get(...args: unknown[]): unknown };
    close(): void;
  };
};

let _dbCtor: DatabaseSyncModule['DatabaseSync'] | null | undefined;

function getDbCtor(): DatabaseSyncModule['DatabaseSync'] | null {
  if (_dbCtor !== undefined) return _dbCtor;
  try {
    const mod = _require('node:sqlite') as DatabaseSyncModule;
    _dbCtor = mod.DatabaseSync;
  } catch {
    _dbCtor = null;
  }
  return _dbCtor;
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** SHA-256 fingerprint of a single file inside the rogue directory. */
export interface RogueFileEntry {
  /** Path relative to the rogue `.cleo/` directory root. */
  path: string;
  /** Hex-encoded SHA-256 digest. */
  sha256: string;
  /** File size in bytes. */
  size: number;
}

/** A single row from `__drizzle_migrations` in a rogue database. */
export interface DrizzleMigrationEntry {
  /** Auto-increment primary key. */
  id: number;
  /** Migration content hash recorded by Drizzle. */
  hash: string;
  /** Human-readable migration name (may be null in older schemas). */
  name: string | null;
}

/** Row counts extracted from SQLite databases found inside the rogue directory. */
export interface RogueDbRowCounts {
  /** Number of rows in `tasks.db → tasks` (undefined if DB absent or unreadable). */
  tasks?: number;
  /** Number of rows in `brain.db → brain_observations` (undefined if DB absent or unreadable). */
  brain_observations?: number;
  /** Number of rows in `brain.db → brain_decisions` (undefined if DB absent or unreadable). */
  brain_decisions?: number;
}

/**
 * Full forensic report for a single rogue `.cleo/` directory.
 *
 * Generated by {@link scanRogueCleoDirs} and consumed by
 * {@link quarantineRogueCleoDir}.
 */
export interface RogueDirReport {
  /** Absolute path to the rogue `.cleo/` directory. */
  path: string;
  /** Package directory name (e.g. `"core"` for `packages/core/.cleo/`). */
  packageName: string;
  /** SHA-256 manifest of every file inside the rogue directory. */
  fileManifest: RogueFileEntry[];
  /** Row counts from SQLite databases found in the directory. */
  dbRowCounts: RogueDbRowCounts;
  /** Drizzle migration records found in `tasks.db` (empty if absent/unreadable). */
  drizzleMigrations: DrizzleMigrationEntry[];
  /** Total size of all files in bytes. */
  totalSize: number;
  /**
   * `true` when `project-info.json` exists inside the `.cleo/` dir, which is
   * the canonical marker of a legitimately-initialised project root.
   * `false` means this is definitely a rogue directory.
   */
  hasProjectInfoMarker: boolean;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Recursively collect all files under `dir`, returning absolute paths.
 *
 * Skips WAL sidecar files (`*.db-shm`, `*.db-wal`) from the walk so the
 * manifest only contains stable, copyable files.
 */
function collectFiles(dir: string): string[] {
  const results: string[] = [];
  const entries = readdirSync(dir, { withFileTypes: true }) as Dirent[];
  for (const entry of entries) {
    const fullPath = join(dir, String(entry.name));
    if (entry.isDirectory()) {
      results.push(...collectFiles(fullPath));
    } else if (entry.isFile()) {
      // Include WAL sidecars in manifest (for completeness) but flag them
      results.push(fullPath);
    }
  }
  return results;
}

/** Attempt to read an integer COUNT from a SQLite table. Returns `undefined` on any error. */
function safeRowCount(
  DbCtor: DatabaseSyncModule['DatabaseSync'],
  dbPath: string,
  table: string,
): number | undefined {
  try {
    const db = new DbCtor(dbPath, { readOnly: true, timeout: 3000 });
    try {
      const row = db.prepare(`SELECT COUNT(*) AS n FROM "${table}"`).get() as
        | { n: number }
        | undefined;
      return row?.n;
    } finally {
      db.close();
    }
  } catch {
    return undefined;
  }
}

/** Read the `__drizzle_migrations` table from a SQLite database. Returns [] on error. */
function readDrizzleMigrations(
  DbCtor: DatabaseSyncModule['DatabaseSync'],
  dbPath: string,
): DrizzleMigrationEntry[] {
  try {
    const db = new DbCtor(dbPath, { readOnly: true, timeout: 3000 });
    try {
      // Check the table exists first to avoid noisy errors
      const tableCheck = db
        .prepare(
          "SELECT COUNT(*) AS n FROM sqlite_master WHERE type='table' AND name='__drizzle_migrations'",
        )
        .get() as { n: number } | undefined;
      if (!tableCheck || tableCheck.n === 0) return [];

      const rows = db.prepare('SELECT id, hash, name FROM __drizzle_migrations ORDER BY id').all();
      return (rows as Array<{ id: number; hash: string; name: string | null }>).map((r) => ({
        id: r.id,
        hash: r.hash,
        name: r.name ?? null,
      }));
    } finally {
      db.close();
    }
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Scan for rogue `.cleo/` directories inside sub-packages of a monorepo.
 *
 * A directory is considered rogue when it:
 *  1. Exists as `.cleo/` directly inside a `packages/<name>/` directory.
 *  2. Does NOT contain `project-info.json` (the canonical legitimacy marker),
 *     OR it does contain one (recorded, but still quarantine-worthy when
 *     inside a sub-package).
 *
 * The function inspects the `packages/` directory under `projectRoot`. Any
 * `.cleo/` found at depth-1 under any package is returned as a report.
 *
 * @param projectRoot - Absolute path to the monorepo root (where the canonical
 *   `.cleo/` directory lives).
 * @returns Array of forensic reports — one per rogue directory found.
 */
export function scanRogueCleoDirs(projectRoot: string): RogueDirReport[] {
  const packagesDir = join(projectRoot, 'packages');
  let packageEntries: Dirent[];
  try {
    packageEntries = readdirSync(packagesDir, { withFileTypes: true }) as Dirent[];
  } catch {
    // Not a monorepo or no packages/ directory — no rogue dirs possible.
    return [];
  }

  const DbCtor = getDbCtor();
  const reports: RogueDirReport[] = [];

  for (const pkgEntry of packageEntries) {
    if (!pkgEntry.isDirectory()) continue;
    const pkgName = String(pkgEntry.name);
    const roguePath = join(packagesDir, pkgName, '.cleo');

    let rogueStats: ReturnType<typeof statSync> | null = null;
    try {
      rogueStats = statSync(roguePath);
    } catch {
      // No .cleo dir in this package — fine.
      continue;
    }
    if (!rogueStats.isDirectory()) continue;

    // Collect file manifest (async sha256 calls resolved synchronously via
    // readFileSync equivalent — we build the list first, hashes computed below).
    const allFiles = collectFiles(roguePath);
    const fileManifest: RogueFileEntry[] = [];
    let totalSize = 0;

    for (const filePath of allFiles) {
      let size = 0;
      try {
        size = statSync(filePath).size;
      } catch {
        /* skip */
      }
      totalSize += size;

      // Synchronous hash via readFileSync
      let hash = '';
      try {
        hash = createHash('sha256').update(readFileSync(filePath)).digest('hex');
      } catch {
        hash = '';
      }

      fileManifest.push({
        path: relative(roguePath, filePath),
        sha256: hash,
        size,
      });
    }

    // Marker file
    const hasProjectInfoMarker = allFiles.some((f) => basename(f) === 'project-info.json');

    // DB row counts
    const dbRowCounts: RogueDbRowCounts = {};
    const tasksDbPath = join(roguePath, 'tasks.db');
    const brainDbPath = join(roguePath, 'brain.db');

    if (DbCtor) {
      try {
        statSync(tasksDbPath);
        dbRowCounts.tasks = safeRowCount(DbCtor, tasksDbPath, 'tasks');
      } catch {
        /* tasks.db absent */
      }
      try {
        statSync(brainDbPath);
        dbRowCounts.brain_observations = safeRowCount(DbCtor, brainDbPath, 'brain_observations');
        dbRowCounts.brain_decisions = safeRowCount(DbCtor, brainDbPath, 'brain_decisions');
      } catch {
        /* brain.db absent */
      }
    }

    // Drizzle migrations from tasks.db (primary)
    let drizzleMigrations: DrizzleMigrationEntry[] = [];
    if (DbCtor) {
      try {
        statSync(tasksDbPath);
        drizzleMigrations = readDrizzleMigrations(DbCtor, tasksDbPath);
      } catch {
        /* tasks.db absent */
      }
    }

    reports.push({
      path: roguePath,
      packageName: pkgName,
      fileManifest,
      dbRowCounts,
      drizzleMigrations,
      totalSize,
      hasProjectInfoMarker,
    });
  }

  return reports;
}

/**
 * Quarantine a single rogue `.cleo/` directory by moving it atomically to
 * `.cleo/quarantine/<pkg-name>-<ISO-timestamp>/` under the project root.
 *
 * The move is a single `fs.renameSync` which is atomic on POSIX when source
 * and destination are on the same filesystem. This is NEVER a deletion — the
 * directory and all its contents are preserved verbatim.
 *
 * @param rogue   - Report produced by {@link scanRogueCleoDirs}.
 * @param projectRoot - Absolute path to the monorepo root.
 * @returns Object containing the absolute `quarantinePath` where the directory
 *   was moved.
 * @throws If the quarantine directory cannot be created or the rename fails.
 */
export function quarantineRogueCleoDir(
  rogue: RogueDirReport,
  projectRoot: string,
): { quarantinePath: string } {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const quarantineBase = join(projectRoot, '.cleo', 'quarantine');
  const quarantinePath = join(quarantineBase, `${rogue.packageName}-${timestamp}`);

  mkdirSync(quarantineBase, { recursive: true });
  renameSync(rogue.path, quarantinePath);

  return { quarantinePath };
}
