/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmconduitmessage_free: (a: number, b: number) => void;
export const wasmconduitmessage_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const wasmconduitmessage_id: (a: number) => [number, number];
export const wasmconduitmessage_from: (a: number) => [number, number];
export const wasmconduitmessage_content: (a: number) => [number, number];
export const wasmconduitmessage_timestamp: (a: number) => [number, number];
export const wasmconduitmessage_tags_json: (a: number) => [number, number];
export const wasmconduitmessage_metadata_json: (a: number) => [number, number];
export const wasmconduitmessage_toJson: (a: number) => [number, number];
export const wasmconduitmessage_fromJson: (a: number, b: number) => number;
export const __wbg_wasmconduitstate_free: (a: number, b: number) => void;
export const wasmconduitstate_Disconnected: () => number;
export const wasmconduitstate_Connecting: () => number;
export const wasmconduitstate_Connected: () => number;
export const wasmconduitstate_Reconnecting: () => number;
export const wasmconduitstate_Error: () => number;
export const wasmconduitstate_as_string: (a: number) => [number, number];
export const __wbg_wasmcantmetadata_free: (a: number, b: number) => void;
export const wasmcantmetadata_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const wasmcantmetadata_directive_type: (a: number) => [number, number];
export const wasmcantmetadata_addresses_json: (a: number) => [number, number];
export const wasmcantmetadata_task_refs_json: (a: number) => [number, number];
export const wasmcantmetadata_tags_json: (a: number) => [number, number];
export const wasmcantmetadata_toJson: (a: number) => [number, number];
export const parse_conduit_message: (a: number, b: number) => number;
export const create_conduit_state: (a: number, b: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
