-- T12344 (S5 apply) — the receive inbox and the conflict log. Journal spec
-- t12342-t12343-journal-design §3.1, §3.2.
--
-- _sync_inbox: every received transaction, staged in stream order, with its
-- apply status. Retention: 'applied' rows are deleted once a verified
-- checkpoint covers them; 'pending', 'void', 'conflict', 'held-skew' and
-- 'refused-schema' are kept until resolved. Local-only.
--
-- _sync_conflict: one row per conflict the apply recorded (a typed-rule
-- refusal or override, an edit of a deleted row, a delete over newer edits,
-- a concurrent divergent field edit, a guard refusal …). Never silently
-- dropped: `cleo cloud conflicts` reads it. Local-only.
--
-- _sync_field_leave: per (tbl, uid, col), the merge state row meta has no
-- place for (§3.6, T13223). `leave` is the HLC of the latest explicit leave:
-- of an absorbing state (a reopen) or a rank-max restore floor; a write
-- older than it does not override the column. `frontier` is a rank-max
-- column's alive candidate writes (canonical JSON [{value, hlc}], oldest
-- first) when more than one is alive. Every replica must know both. Cleared
-- on delete. Local-only.
--
-- Do not edit this file once applied: its hash is recorded per store.
CREATE TABLE IF NOT EXISTS _sync_inbox (
  stream         TEXT NOT NULL,
  seq            INTEGER NOT NULL,
  txn_idx        INTEGER NOT NULL,
  replica_id     TEXT NOT NULL,
  replica_seq    INTEGER NOT NULL,
  device_id      TEXT NOT NULL,
  schema_version INTEGER NOT NULL,
  txn_json       TEXT NOT NULL,
  hlc            TEXT NOT NULL,
  status         TEXT NOT NULL CHECK (status IN ('staged','pending','applied','void','conflict','held-skew','refused-schema')),
  applied_frame  TEXT,
  reason         TEXT,
  staged_at      TEXT NOT NULL,
  applied_at     TEXT,
  PRIMARY KEY (stream, seq, txn_idx)
);
CREATE INDEX IF NOT EXISTS _sync_inbox_open ON _sync_inbox (stream, status, seq, txn_idx);
CREATE TABLE IF NOT EXISTS _sync_conflict (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  stream       TEXT NOT NULL,
  seq          INTEGER NOT NULL,
  txn_idx      INTEGER NOT NULL,
  op_idx       INTEGER NOT NULL,
  kind         TEXT NOT NULL,
  tbl          TEXT NOT NULL,
  uid          TEXT NOT NULL,
  columns_json TEXT NOT NULL,
  rule         TEXT,
  resolution   TEXT NOT NULL,
  op_hlc       TEXT NOT NULL,
  local_hlc    TEXT,
  origin       TEXT NOT NULL,
  created_at   TEXT NOT NULL,
  resolved_at  TEXT
);
CREATE INDEX IF NOT EXISTS _sync_conflict_open ON _sync_conflict (resolved_at, tbl, uid);
CREATE TABLE IF NOT EXISTS _sync_field_leave (
  tbl      TEXT NOT NULL,
  uid      TEXT NOT NULL,
  col      TEXT NOT NULL,
  leave    TEXT,
  frontier TEXT,
  PRIMARY KEY (tbl, uid, col)
) WITHOUT ROWID;
