// Auto-generated by @forge-ts/doctest — do not edit
// Source: /mnt/projects/cleocode/packages/contracts/src/errors.ts
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { normalizeError, getErrorMessage, formatError, isErrorType, createErrorResult, createSuccessResult, isErrorResult } from "../../packages/contracts/src/errors.js";

describe("doctest: errors.ts", () => {
	it("normalizeError example 1 (line 33)", async () => {
		try {
		  await riskyOperation();
		} catch (err) {
		  const error = normalizeError(err, 'Operation failed');
		  console.error(error.message);
		}
		
	});
	it("getErrorMessage example 1 (line 71)", async () => {
		const message = getErrorMessage(err, 'Unknown error');
		
	});
	it("formatError example 1 (line 108)", async () => {
		console.error(formatError(err, 'Database connection'));
		// Output: [Database connection] Connection refused
		
	});
	it("isErrorType example 1 (line 136)", async () => {
		if (isErrorType(err, 'E_NOT_FOUND')) {
		  // Handle not found specifically
		}
		
	});
	it("createErrorResult example 1 (line 163)", async () => {
		return createErrorResult(err);
		// Returns: { success: false, error: "Something went wrong" }
		
	});
	it("createSuccessResult example 1 (line 181)", async () => {
		return createSuccessResult();
		// Returns: { success: true }
		
	});
	it("isErrorResult example 1 (line 199)", async () => {
		const result = await someOperation();
		if (isErrorResult(result)) {
		  console.error(result.error);
		}
		
	});
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiX21udF9wcm9qZWN0c19jbGVvY29kZV9wYWNrYWdlc19jb250cmFjdHNfc3JjX2Vycm9yc190cy50ZXN0LnRzIiwic291cmNlcyI6WyIvbW50L3Byb2plY3RzL2NsZW9jb2RlL3BhY2thZ2VzL2NvbnRyYWN0cy9zcmMvZXJyb3JzLnRzIl0sInNvdXJjZXNDb250ZW50IjpudWxsLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7OztBQWdDQTs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFzRUE7Ozs7Ozs7QUEyR0E7Ozs7Ozs7OztBQXVJQTs7Ozs7Ozs7Ozs7QUFrS0E7Ozs7Ozs7OztBQW9MQTs7Ozs7Ozs7O0FBc01BIn0=
