// Auto-generated by @forge-ts/doctest — do not edit
// Source: /mnt/projects/cleocode/packages/core/src/lifecycle/resume.ts
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { findResumablePipelines, loadPipelineContext, resumeStage, autoResume, checkSessionResume } from "../../packages/core/src/lifecycle/resume.js";

describe("doctest: resume.ts", () => {
	it("findResumablePipelines example 1 (line 386)", async () => {
		// Find all active pipelines
		const resumable = await findResumablePipelines();
		
		// Find specific tasks
		const specific = await findResumablePipelines({
		  taskIds: ['T4805', 'T4806']
		});
		
		// Include blocked pipelines
		const withBlocked = await findResumablePipelines({
		  includeBlocked: true
		});
		
	});
	it("loadPipelineContext example 1 (line 531)", async () => {
		const context = await loadPipelineContext('T4805');
		console.log(`Current stage: ${context.currentStage}`);
		console.log(`Stage status: ${context.stages.find(s => s.stage === context.currentStage)?.status}`);
		
	});
	it("resumeStage example 1 (line 686)", async () => {
		const result = await resumeStage('T4805', 'implement');
		if (result.success) {
		  console.log(`Resumed ${result.taskId} at ${result.stage}`);
		}
		
	});
	it("autoResume example 1 (line 832)", async () => {
		const result = await autoResume();
		if (result.canResume) {
		  console.log(`Recommended: Resume ${result.taskId} at ${result.stage}`);
		} else if (result.options && result.options.length > 0) {
		  console.log('Multiple options available:', result.options);
		}
		
	});
	it("checkSessionResume example 1 (line 1071)", async () => {
		// On session start
		const resumeCheck = await checkSessionResume({ autoResume: true });
		if (resumeCheck.didResume) {
		  console.log(`Auto-resumed ${resumeCheck.resumedTaskId}`);
		} else if (resumeCheck.requiresUserChoice) {
		  console.log('Multiple options:', resumeCheck.options);
		}
		
	});
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiX21udF9wcm9qZWN0c19jbGVvY29kZV9wYWNrYWdlc19jb3JlX3NyY19saWZlY3ljbGVfcmVzdW1lX3RzLnRlc3QudHMiLCJzb3VyY2VzIjpbIi9tbnQvcHJvamVjdHMvY2xlb2NvZGUvcGFja2FnZXMvY29yZS9zcmMvbGlmZWN5Y2xlL3Jlc3VtZS50cyJdLCJzb3VyY2VzQ29udGVudCI6bnVsbCwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7QUFpWUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBa2hCQTs7Ozs7Ozs7Ozs7QUE2cUJBOzs7Ozs7Ozs7Ozs7O0FBK3pCQTs7Ozs7Ozs7Ozs7Ozs7Ozs7QUE4aUNBIn0=
