// Auto-generated by @forge-ts/doctest — do not edit
// Source: /mnt/projects/cleocode/packages/core/src/lifecycle/state-machine.ts
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { checkPrerequisites, validateTransition, executeTransition } from "../../packages/core/src/lifecycle/state-machine.js";

describe("doctest: state-machine.ts", () => {
	it("checkPrerequisites example 1 (line 187)", async () => {
		const check = await checkPrerequisites('implement', {
		  research: { status: 'completed' },
		  spec: { status: 'completed' },
		  decompose: { status: 'completed' },
		  // ... other stages
		});
		if (check.met) {
		  console.log('Ready to implement');
		}
		
	});
	it("validateTransition example 1 (line 301)", async () => {
		const validation = await validateTransition(
		  { from: 'spec', to: 'implement', initiatedBy: 'agent-001' },
		  pipelineContext
		);
		if (!validation.valid) {
		  console.log(validation.errors);
		}
		
	});
	it("executeTransition example 1 (line 402)", async () => {
		const result = await executeTransition(
		  { from: 'spec', to: 'implement', initiatedBy: 'agent-001' },
		  pipelineContext
		);
		if (result.success) {
		  console.log(`Transitioned to ${result.newState.stage}`);
		}
		
	});
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiX21udF9wcm9qZWN0c19jbGVvY29kZV9wYWNrYWdlc19jb3JlX3NyY19saWZlY3ljbGVfc3RhdGVfbWFjaGluZV90cy50ZXN0LnRzIiwic291cmNlcyI6WyIvbW50L3Byb2plY3RzL2NsZW9jb2RlL3BhY2thZ2VzL2NvcmUvc3JjL2xpZmVjeWNsZS9zdGF0ZS1tYWNoaW5lLnRzIl0sInNvdXJjZXNDb250ZW50IjpudWxsLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7OztBQTBMQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUE0U0E7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFpWkEifQ==
