// Auto-generated by @forge-ts/doctest — do not edit
// Source: /mnt/projects/cleocode/packages/core/src/lifecycle/pipeline.ts
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { initializePipeline, getPipeline, advanceStage, getCurrentStage, listPipelines } from "../../packages/core/src/lifecycle/pipeline.js";

describe("doctest: pipeline.ts", () => {
	it("initializePipeline example 1 (line 240)", async () => {
		const pipeline = await initializePipeline('T4800', {
		  startStage: 'research',
		  assignedAgent: 'agent-001'
		});
		console.log(`Pipeline initialized: ${pipeline.id}`);
		
	});
	it("getPipeline example 1 (line 343)", async () => {
		const pipeline = await getPipeline('T4800');
		if (pipeline) {
		  console.log(`Current stage: ${pipeline.currentStage}`);
		}
		
	});
	it("advanceStage example 1 (line 407)", async () => {
		await advanceStage('T4800', {
		  toStage: 'consensus',
		  reason: 'Research completed, moving to consensus',
		  initiatedBy: 'agent-001'
		});
		
	});
	it("getCurrentStage example 1 (line 554)", async () => {
		const currentStage = await getCurrentStage('T4800');
		if (currentStage === 'validation') {
		  console.log('Task is in verification');
		}
		
	});
	it("listPipelines example 1 (line 589)", async () => {
		const activePipelines = await listPipelines({
		  status: 'active',
		  limit: 10
		});
		
	});
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiX21udF9wcm9qZWN0c19jbGVvY29kZV9wYWNrYWdlc19jb3JlX3NyY19saWZlY3ljbGVfcGlwZWxpbmVfdHMudGVzdC50cyIsInNvdXJjZXMiOlsiL21udC9wcm9qZWN0cy9jbGVvY29kZS9wYWNrYWdlcy9jb3JlL3NyYy9saWZlY3ljbGUvcGlwZWxpbmUudHMiXSwic291cmNlc0NvbnRlbnQiOm51bGwsIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7O0FBK09BOzs7Ozs7Ozs7Ozs7Ozs7QUFzVkE7Ozs7Ozs7Ozs7Ozs7QUFzWkE7Ozs7Ozs7Ozs7Ozs7OztBQXlpQkE7Ozs7Ozs7Ozs7Ozs7QUE0a0JBIn0=
