/**
 * Engine Re-exports for Dispatch Domain Handlers
 *
 * Centralizes the dispatch layer's engine imports into a single barrel.
 * All imports use dispatch/engines/ (which delegate to src/core/).
 *
 * @epic T4820
 * @task T4815
 */

export type { MinimalTaskRecord, Session as SessionRecord, TaskRecord } from '@cleocode/contracts';
export type { OrchestratePlanResult } from '@cleocode/contracts/operations/orchestrate';
// Task operations — re-exported from @cleocode/core/internal (T1568 / ADR-057 / ADR-058)
// task-engine.ts was deleted in Wave 5; all symbols now live in core/tasks/.
// Orchestrate — types and functions from @cleocode/core/internal (T1570 ADR-057)
// System — type aliases for backward compat (T1571: system-engine.ts deleted, canonical sources = @cleocode/core/internal)
export type {
  ArchiveStatsResult as ArchiveStatsData,
  AuditResult as AuditData,
  BackupEntry as BackupEntryData,
  BackupResult as BackupData,
  CleanupResult as CleanupData,
  CompactTask,
  ComplianceData,
  ContextData,
  DashboardData,
  DiagnosticsResult as DiagnosticsData,
  FileRestoreResult,
  HealthResult as HealthData,
  HelpData,
  InjectGenerateResult as InjectGenerateData,
  IvtrHistoryEntry,
  LabelsResult as LabelsData,
  LifecycleStageEntry,
  LogQueryData,
  MigrateResult as MigrateData,
  OrchestratePlanInput,
  PathsData,
  PlanWarning,
  PlanWave,
  PlanWorkerEntry,
  RestoreResult as RestoreData,
  RuntimeDiagnostics as RuntimeData,
  SafestopResult as SafestopData,
  ScaffoldHubData,
  StatsData,
  SyncData,
  SystemMetricsResult as MetricsData,
  UncancelResult as UncancelData,
} from '@cleocode/core/internal';
// Pipeline manifest functions (moved from memory domain in T5241)
// Release engine (T1572 — ENG-MIG-5: migrated to @cleocode/core/internal)
// Session engine (T1573 — ENG-MIG-6: migrated to @cleocode/core/internal)
// Lifecycle engine ops — re-exported from @cleocode/core/internal (T1576 / ENG-MIG-9 / ADR-057)
// lifecycle-engine.ts shrunk to a shim; all symbols now live in core/lifecycle/engine-ops.ts.
export {
  addTaskWithSessionScope,
  completeTaskStrict,
  type DecisionRecord,
  filterEntries as filterManifestEntries,
  lifecycleCheck,
  lifecycleGateFail,
  lifecycleGatePass,
  lifecycleGates,
  lifecycleHistory,
  lifecyclePrerequisites,
  lifecycleProgress,
  lifecycleReset,
  lifecycleSkip,
  lifecycleStatus,
  type ManifestEntry as ResearchManifestEntry,
  orchestrateAnalyze,
  orchestrateBootstrap,
  orchestrateCheck,
  orchestrateContext,
  orchestrateCriticalPath,
  orchestrateHandoff,
  orchestrateNext,
  orchestrateParallelEnd,
  orchestrateParallelStart,
  orchestratePlan,
  orchestrateReady,
  orchestrateSkillInject,
  orchestrateSpawn,
  orchestrateSpawnExecute,
  orchestrateStartup,
  orchestrateStatus,
  orchestrateUnblockOpportunities,
  orchestrateValidate,
  orchestrateWaves,
  // Pipeline engine-ops (ENG-MIG-11 / T1578 — migrated to @cleocode/core/internal)
  // pipeline-engine.ts shrunk to a shim; all symbols now live in core/pipeline/engine-ops.ts.
  phaseAdvance,
  phaseComplete,
  phaseDelete,
  phaseList,
  phaseRename,
  phaseSet,
  phaseShow,
  phaseStart,
  pipelineManifestAppend,
  pipelineManifestArchive,
  pipelineManifestFind,
  pipelineManifestList,
  pipelineManifestPending,
  pipelineManifestShow,
  pipelineManifestStats,
  readManifestEntries,
  releaseCancel,
  releaseChangelog,
  releaseChangelogSince,
  releaseCommit,
  releaseGateCheck,
  releaseGatesRun,
  releaseIvtrAutoSuggest,
  releaseList,
  releasePrepare,
  releasePush,
  releaseRollback,
  releaseRollbackFull,
  releaseShip,
  releaseShow,
  releaseTag,
  sessionArchive,
  sessionBriefing,
  sessionChainShow,
  sessionCleanup,
  // T4959: Rich debrief + chain
  sessionComputeDebrief,
  sessionComputeHandoff,
  sessionContextDrift,
  sessionContextInject,
  sessionDebriefShow,
  sessionDecisionLog,
  sessionEnd,
  // T5119: Lightweight session discovery
  sessionFind,
  sessionGc,
  sessionHandoff,
  sessionHistory,
  sessionList,
  sessionRecordAssumption,
  sessionRecordDecision,
  sessionResume,
  sessionShow,
  sessionStart,
  sessionStats,
  sessionStatus,
  sessionSuspend,
  sessionSwitch,
  taskAnalyze,
  taskArchive,
  taskBatchValidate,
  taskBlockers,
  taskCancel,
  taskClaim,
  taskComplete,
  taskComplexityEstimate,
  taskCurrentGet,
  taskDelete,
  taskDepends,
  taskDeps,
  taskDepsCycles,
  taskDepsOverview,
  taskExists,
  taskExport,
  taskFind,
  taskHistory,
  taskImpact,
  taskImport,
  taskLabelList,
  taskLabelShow,
  taskLint,
  taskList,
  taskNext,
  taskPlan,
  taskPromote,
  taskRelates,
  taskRelatesAdd,
  taskRelatesFind,
  taskReopen,
  taskReorder,
  taskReparent,
  taskRestore,
  taskShow,
  taskShowIvtrHistory,
  taskShowWithHistory,
  taskStart,
  taskStats,
  taskStop,
  taskSyncLinks,
  taskSyncLinksRemove,
  taskSyncReconcile,
  taskTree,
  taskUnarchive,
  taskUnclaim,
  taskUpdate,
  taskWorkHistory,
} from '@cleocode/core/internal';
// Codebase map engine
export { mapCodebase } from '../engines/codebase-map-engine.js';
// Config engine
export {
  configGet,
  configListPresets,
  configSet,
  configSetPreset,
} from '../engines/config-engine.js';
// Hooks engine (ENG-MIG-12 / T1579 — logic in @cleocode/core/internal)
export {
  type HookMatrixResult,
  type ProviderMatrixEntry,
  queryCommonHooks,
  queryHookProviders,
  systemHooksMatrix,
} from '@cleocode/core/internal';
// Init engine
export {
  ensureInitialized,
  getVersion,
  initProject,
  isAutoInitEnabled,
} from '../engines/init-engine.js';
// Memory engine — brain.db cognitive memory (T5241 cutover)
export {
  memoryBrainStats,
  memoryContradictions,
  memoryDecisionFind,
  memoryDecisionStore,
  memoryFetch,
  memoryFind,
  memoryGraphAdd,
  memoryGraphContext,
  memoryGraphNeighbors,
  memoryGraphRelated,
  memoryGraphRemove,
  memoryGraphShow,
  memoryGraphStatsFull,
  memoryGraphTrace,
  memoryLearningFind,
  memoryLearningStats,
  memoryLearningStore,
  memoryLink,
  memoryObserve,
  memoryPatternFind,
  memoryPatternStats,
  memoryPatternStore,
  memoryQualityReport,
  memoryReasonSimilar,
  memoryReasonWhy,
  memorySearchHybrid,
  memoryShow,
  memorySuperseded,
  memoryTimeline,
  memoryUnlink,
} from '../engines/memory-engine.js';
// Template parser engine
export {
  generateTemplateConfig,
  getTemplateForSubcommand,
  type IssueTemplate,
  parseIssueTemplates,
  type TemplateConfig,
  type TemplateSection,
  validateLabels,
} from '../engines/template-parser.js';
// Validate engine
export {
  validateBatchValidate,
  validateCoherenceCheck,
  validateComplianceRecord,
  validateComplianceSummary,
  validateComplianceViolations,
  validateGateVerify,
  validateManifest as validateManifestOp,
  validateOutput,
  validateProtocol,
  // T5327 + T260: Protocol validation operations (12 protocols)
  validateProtocolArchitectureDecision,
  validateProtocolArtifactPublish,
  validateProtocolConsensus,
  validateProtocolContribution,
  validateProtocolDecomposition,
  validateProtocolImplementation,
  validateProtocolProvenance,
  validateProtocolRelease,
  validateProtocolResearch,
  validateProtocolSpecification,
  validateProtocolTesting,
  validateProtocolValidation,
  validateSchemaOp,
  validateTask as validateTaskOp,
  validateTestCoverage,
  validateTestRun,
  validateTestStatus,
} from '../engines/validate-engine.js';
