//! T9053 — SSoT cross-language equivalence tests.
//!
//! These assertions ensure the canonical pragma SQL generated from
//! `specs/sqlite-pragmas.json` is well-formed and matches the byte-level
//! contract that `packages/core/src/store/sqlite-pragmas.ts` consumes.
//! The TS side has a parallel test that re-renders the same JSON and
//! diffs the result against `CANONICAL_PRAGMA_SQL` — together they make
//! drift impossible by construction (per the ADR comment in the JSON file).

use signaldock_storage::sqlite_pragmas;

#[test]
fn pragma_set_is_non_empty() {
    assert!(
        !sqlite_pragmas::SQLITE_PRAGMAS.is_empty(),
        "SQLITE_PRAGMAS must contain at least one (name,value) pair — \
         empty SSoT would silently disable the pragma policy"
    );
}

#[test]
fn pragma_sql_renders_each_entry() {
    // The `;\n`-joined SQL must contain a `PRAGMA name = value` line for
    // every (name,value) pair declared in the SSoT.
    for (name, value) in sqlite_pragmas::SQLITE_PRAGMAS {
        let needle = format!("PRAGMA {name} = {value}");
        assert!(
            sqlite_pragmas::SQLITE_PRAGMA_SQL.contains(&needle),
            "SQLITE_PRAGMA_SQL missing rendered entry `{needle}` — \
             build.rs render rule diverged from JSON contract"
        );
    }
}

#[test]
fn pragma_sql_render_rule_is_byte_exact() {
    // Re-render from SQLITE_PRAGMAS using the documented rule
    // (`PRAGMA name = value` joined with `;\n`) and compare byte-for-byte
    // to the const generated by build.rs. Any divergence between the
    // pairs and the joined SQL is a bug.
    let rebuilt = sqlite_pragmas::SQLITE_PRAGMAS
        .iter()
        .map(|(n, v)| format!("PRAGMA {n} = {v}"))
        .collect::<Vec<_>>()
        .join(";\n");
    assert_eq!(rebuilt, sqlite_pragmas::SQLITE_PRAGMA_SQL);
    assert_eq!(
        format!("{rebuilt};"),
        sqlite_pragmas::SQLITE_PRAGMA_SQL_BATCH
    );
}

#[test]
fn pragma_set_includes_required_baseline() {
    // The Rust pool's post_create hook USED to inline four pragmas:
    // journal_mode, foreign_keys, busy_timeout, synchronous. The SSoT
    // must keep declaring all four — anything less is a silent
    // performance/concurrency regression for SignalDock.
    let names: Vec<&str> = sqlite_pragmas::SQLITE_PRAGMAS
        .iter()
        .map(|(n, _)| *n)
        .collect();
    for required in [
        "journal_mode",
        "foreign_keys",
        "busy_timeout",
        "synchronous",
    ] {
        assert!(
            names.contains(&required),
            "SSoT specs/sqlite-pragmas.json dropped required pragma `{required}` \
             — would regress concurrency/durability guarantees"
        );
    }
}
